### ISSUE TITLE
Support FIDO U2F security key in desktop client

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2178]
As a user i want to be able to use (login and register) my FIDO U2F security key as a second factor in the desktop client and in the mobile apps.  A security key that is registerd on mobile/desktop application should also be usable within the web version and vise versa.

**AC**
- [ ] Allow setting up a security key in Settings > Login 
- [ ] When security key is registered in desktop client it is always registered for https://mail.tutanota.com
- [ ] Authenticate with security key as second factor in desktop client/mobile app
- [ ] Authenticate with the same key in web client on https://mail.tutanota.com
- [ ] Autenticate with key that has been registered on whitelabel domain.

**Task**
* [x] Implement an ApplicationWindow variant that can be opened from the main thread to a website/url and return some result
* [x] Change the 2F settings to send a request to open `mail.tutanota.com/webauthn`to add a key
* [x] Change login process to authenticate on `mail.tutanota.com/webauthn` with second factor to use built-in webauthn implementation.
 
**Development notes:**
~~We are currently migrating from U2F Api to WebAuthn Api because chrome is dropping support for U2F API. We also should use WebAuthn standard if possible. See also: #2140~~

Instead of implementing the device communication in the native part of the application using different libraries we prefer to use the WebAuthn API of the browser or web view. WebAuthn only works in a secure context (https) and the devices must be registered for a certain domain. In our case the devices are registered for the domain https://tutanota.com when adding a security key in the web client on https://mail.tutanota.com.

The desktop/mobile apps are not running in that secure context. We are creating a web view/browser window and serving the application files from the local file system.

We cannot just create such a secure context for https://tutanota.com locally so the idea is to open another browser window/web view which opens a site on https://mail.tutanota.com whenever we need to confirm the second factor and and just use this window to confirm the second factor.

A conflict occurs when the security key was set up on a whitelabel domain. This key cannot be used to authenticate on http://mail.tutanota.com because it is a different domain. We probaly can also not allow to authenticate within the desktop/mobile app for such keys. They have to register the key for the app again, which then will be registed for http://mail.tutanota.com.

**More information about integrating WebAuthn**
https://developers.yubico.com/WebAuthn/WebAuthn_Developer_Guide/
https://developers.yubico.com/WebAuthn/WebAuthn_Developer_Guide/Desktop_and_Mobile_Authentication.html

**Electron spec:**
https://github.com/electron/electron/issues/15404

Same as https://github.com/tutao/tutanota/issues/443 for desktop client.

## Test notes
 - [ ] Regression testing for web client: adding webauthn keys, authentication with webauthn and legacy U2F keys (might need old client build)
 - [ ] Desktop app:
   - [ ] Add U2F key in settings
     - [ ] Can use cancel button
     - [ ] Can add a key
   - [ ] Authenticate with the key:
     - [ ] key from Tutanota domain (priority 1)
     - [ ] key from whitelabel domain (priority 2)
     - [ ] legacy key from Tutanota (priority 3)
     - [ ] legacy key from whitelabel domain (priority 4)
     - [ ] Can cancel manually
     - [ ] Errors are handled (invalid key)
     - [ ] Automatically cancelled and prompt is closed when confirming from another client
   - [ ] Interactions:
     - [ ] keys registered in desktop work in web client
     - [ ] keys registered in web client work in desktop
   - [ ] Check WebDialog window behaviour (on win, mac, linux)
     - [ ] blocks interaction with the parent window
     - [ ] always is parented to the window we're logging in from, even when quickly changing window after opening
     - [ ] can't be moved independently
     - [ ] is invisible in taskbars and other window lists
     - [ ] looks like a tutanota modal otherwise
   - [ ] regression test #2766

**Comment by ganthern** [comment]
related issue that needs to be tested for regression when this is implemented: https://github.com/tutao/tutanota/issues/2766

**Comment by 61Mv24** [comment]
I am using a YubiKey with Tutanota on my Desktop with Firefox, works well.

**Comment by jrm523** [comment]
Is this still in the works? Chrome states they are dropping the current U2F api login method in two months (2/2022)

**Comment by charlag** [comment]
@jrm523 it wil be via WebAuthnetication which we are finishing up

**Comment by johnbotris** [comment]
I'm testing locally against a local server. When I try to setup u2f from the desktop client then I get a 404 error. The dialog shows this:
![Screenshot from 2022-02-17 14-27-48](https://user-images.githubusercontent.com/22109738/154491471-55d8f520-0a15-4b22-a52a-bb67cf0b7052.png)

There's no way out except for closing the whole window (or alt+f4). Did i forget to get server changes or something? @ganthern

**Comment by johnbotris** [comment]
* The first time opening the webauthn dialog from settings, it was blank with this message in the console:
![Screenshot from 2022-02-24 14-44-37](https://user-images.githubusercontent.com/22109738/155538538-79a55090-ac94-4f95-ac54-20114897a8dc.png)
However, I see the correct dialog on subsequent tries

* The `CancelledError` from the cancel button is unhandled and shows an error dialog
* My U2F key is not recognised
* #3914 is still not fixed

**Comment by sarashub** [comment]
found this issue #3938
