### ISSUE TITLE
ToDo's for the Text Template Feature

### ISSUE THREAD

**Issue by Pa7Hub** [tutao/tutanota#2386]
This will allow us to stay updated together during Home Office.

**Done:** 

- [x] the displayed content still gets cut with a "..." even though the length does not exceed the limit. 
- [x] when creating templates with the same title and Id, they are seen as "one" element in the list. Clicking one will highlight all of them, deleting one will however only delete the selected, same with editing. The List also stops updating when such a template is created. (This problem will stay until server operations are implemented. We use a unique Id with the templates title, so using a title twice will give two templates the same unique Id, causing them to be "one element")
- [x] discuss with Bernd regarding Language implementation 
- [x] add language not working
- [x] List of languages not updating after choosing a new language
- [x] Editor should save for each language and clear if a new is selected
- [x] allow user to see language content in detailsviewer
- [x] somehow only saves the first language you edited, the rest is discarded
- [x] list in settings still doesn't sort by alphabet, because its not implemented yet. 
- [x] Popup not yet implementing languages correctly
- [x] fix bug with backgroundclick on modal
- [x] rework filter function (Not sure yet)
- [x] rework mouse compatibility 
- [x] Add feature to type text in mail, mark and open template feature and directly insert text into filter for easy usability
- [x] discuss how to navigate between input field and dropdown
- [x] Keyboard functionality? 
- [x] filter rework? (we think its overkill)
- [x] remove Submit button 
- [x] change color from Group Key (then Tag) Tags from red to grey (like in FAQ)
- [x] re-do the way we import languages and sorting
- [x] When you write "#" followed by text in the Editor and open the Popup, it should instantly open the Popup with the Hashtag and text inserted (allows for easier usage)
- [x] use HTMLEditor that allows changing things like Bold, italic, etc. 
- [x] change name from Group Key -> Tag
- [x] format of pasted text stays the same (no default font)
- [x] use language Code in Template Object instead of just a string
- [x] refactor the Editor 
- [x] CSS: change width to be dynamic
- [x] CSS: nested components shouldn't use set heights/widths anymore, both should be relative to their parent/the popup
- [x] Add TranslationKeys

---------------------------------------------------------------

**Open:**

---------------------------------------------------------------

**For future reference:**

- [ ] consider adding support for multiple tags
- [ ] Removing entries in the list does not actually remove them sometimes. After refreshing they re-appear
- [ ] discuss how the knowledge base shall be implemented
- [ ] rework the Language View model (things like automatically sorting stuff, excluding certain languages)
