### ISSUE TITLE
Support Apple M1 devices

### ISSUE THREAD

**Issue by ark-** [tutao/tutanota#2625]
As a user of desktop mac application i want to have support for arm architecture so i don't have to enable legacy support for my applie silicon mac.

## AC
* User can use the desktop application without rosetta
* Intel macs are still supported
* There is one binary which supports both architectures.

## Tasks
- [x] Test whether running `node desktop -a universal` builds a universal binary on Mac
- [x] Adjust Jenkins job to build a universal binary on M1 mac
- [x] Try merge option
- [x] Test whether the desktop client runs on older versions of macOS (BigSur & Monterey)
 
## Notes

* We might need to setup the build environment on the new mac if we cannot build apple silicon binaries on the old one.

* We need to include arm precompiled binaries for openssl/sql cipher.

## Notes (issue reported by user)

**Describe the bug**
There is no arm64 binary available for Apple M1 devices. Currently the app needs to be run through Rosetta translation. This is important as all Apple desktop/laptop devices will be using this chip going forward and they *claim* it's as easy as adding an additional target in the build process. 

**To Reproduce**
NA

**Expected behavior**
Native binary available for Apple Silicon (currently only M1). 

**Screenshots**
![2021-01-16 at 10 20](https://user-images.githubusercontent.com/6353339/104809349-96420080-57e4-11eb-98e2-e6f30630ba88.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 3.80.4

**Additional context**
http://doesitarm.com shows a bunch of apps which have already implemented native support.

## Test Notes
 * [ ] the dmg does work on MacOS 
   * on the M1 chip
   * also for intel
* [ ] linux desktop client starts
* [ ] on all desktop platform, it's possible to use previously stored credentials to log in

**Comment by thinkofher** [comment]
Being able to use tutanota as native application for M1 based macs would be terrific. Especially because, as far as I know, electron already supports M1.

Is building tutanota for M1 something more than digging in CI?

**Comment by ark-** [comment]
Hi all. 

The ARM binaries were previously held up by Tutanota building keytar themselves. That PR is merged now: https://github.com/tutao/tutanota/pull/3016

Is there a plan to continue with https://github.com/tutao/tutanota/pull/3020? I'm noticing a few bugs with my M1 mac and wanted to wait for the ARM64 release before reporting them all.

**Comment by johnbotris** [comment]
Once we change to use `safeStorage` and drop keytar (https://github.com/tutao/tutanota/issues/3676), will we then get this for free?

**Comment by charlag** [comment]
@johnbotris still need to build for it

**Comment by EVLRBT-01** [comment]
+1 for arm64 support, for general Linux also!

**Comment by RyanRoberts** [comment]
Another +1 for M1 support. The current Intel app is very slow to start (not a big issue).

**Comment by CalvoUTN** [comment]
+1 For this too! I'm using the browser till we get a native app. Thanks!

**Comment by Universal-Igloo** [comment]
+1 Please prioritize this, it would make my premium subscription much more useful!

**Comment by ark-** [comment]
> Once we change to use `safeStorage` and drop keytar (#3676), will we then get this for free?

`safeStorage` seems to be implemented now, or at least the referenced issue is closed. Is there anything else now that would prevent a arm64 build?

**Comment by charlag** [comment]
We do not use `safeStorage` as it is tied very tightly to how Chromium works and doesn't cover all our cases.
I don't think there are strictly technical reasons now. Just needs a lot of time investment and we are trying to push other things towards completion (e.g. offline)

**Comment by ark-** [comment]
My bad, I assumed it would be a quick win.

**Comment by ark-** [comment]
For watchers of this issue, seems to be activity over on #357 :-)

**Comment by ylluminate** [comment]
> For watchers of this issue, seems to be activity over on [vladimiry/ElectronMail#357](https://github.com/vladimiry/ElectronMail/issues/357)

Achieved resolution. Works great.

**Comment by ark-** [comment]
Reports show that it's making a massive difference to ElectronMail users. I'm fairly bored of the slow start up times and having to force close and reopen Tutanota every time I put my mac to sleep.

**Comment by Universal-Igloo** [comment]
@charlag Any update on this from your end? Or an expected timeline?

Thank you for all the great work you do!

**Comment by artskeit** [comment]
@charlag any update on Apple Silicon support? 
It is basically the only application I have which still lacks support.

**Comment by jactmp** [comment]
> @charlag any update on Apple Silicon support?
> It is basically the only application I have which still lacks support.

It _is_ the only application I have which still lacks ARM64 support. I'm currently using web interface and am going to wait for arm version.

**Comment by JanWorks** [comment]
Really, Tutatnota _is the very last_ application on my M1/M2 Macs without ARM64 (aka Apple Silicon) native support, using browser-based app as a stand-in in the meantime.

Frankly, I refuse to use Rosetta for several security and performance reasons. In a way it is a temporary solution, a translation layer adding attack surface (and potential bugs) and so is in direct conflict with the security-first approach of Tutanota. On a different note, it is like dragging a diesel generator trailer behind an electric car as there are no chargers anywhere near enough.

**Comment by JanWorks** [comment]
Another month, no change, no Apple Silicon support. Tutanota is REALLY the last of my apps not having M-Series native support. 

With the recent hike in pricing, any news on this front, please?

**Comment by thinkofher** [comment]
Hard to believe that I commented here more than 2 years ago. To be honest: I am not using tutanota as native app anymore on my Mac, because of lack of support for apple silicon.

**Comment by doczipeter** [comment]
This is something I'm looking forward to.

**Comment by JanWorks** [comment]
So, yet another 2 months passed. Still **no M-Series Mac (macOS) app** available. Frankly, this seems to be either complete ignorance or outright intention to single-out M-Series Mac users. 

BTW: boasting about PQ-crypto project is fine, even getting money from the German state (!) for this purpose **might** be O.K., but full omission of M-Series Macs is beyond comprehension, sorry.

**Comment by charlag** [comment]
I promise we didn't forget about new macs, sorry that it takes so long

**Comment by arcc1845** [comment]
The M3 was announced today, but there's nothing on Tutanota about support. I think you guys forgot about the new macs.

**Comment by doczipeter** [comment]
@arcc1845 I use Tutanota as a Safari Web App now. Give it a try, maybe you'll like it.

**Comment by JanWorks** [comment]
@doczipeter I am sorry to write that web app is not a native app, hope you understand. 

Once again: a NATIVE APP, if written according to secure coding practices (and, also, not using something like TypeScript or similar BS) is inherently more secure than a web app, which drags in all potential security bugs of the underlying  browser.

Real secure native apps for iOS/macOS would use something like Rust and/or Swift and/or C/C++/ObjC or alike.

Tutanota is a complete ignorant in this respect. And, again, I am sorry for that.

**Comment by arcc1845** [comment]
I found a surprising post on Reddit today: [post](https://www.reddit.com/r/tutanota/comments/17icd94/2023_is_nearing_its_end_and_still_no_native_apple/)

And the Tutanota team says:
> "Thank you for your feedback. I'll pass this on to the development team, but we definitely need to work on the import feature first."

Wow! They really were forgetting about us!

**Comment by markrossington** [comment]
Just tested the Universal binary build and it's very snappy. Much better.

Thanks
