### ISSUE TITLE
Calendar notification for all day events

### ISSUE THREAD

**Issue by yellowhat** [tutao/tutanota#2846]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
If I create an event with "All Day" ticked and "Reminder before event" to "1 day", I do not get any notifications.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Calendar'
2. Create an event
3. Click on 'All Day'
4. Set "Reminder before event" to '1 day'
5. No notification is showed

**Expected behaviour**
A notification the day before, not sure at what time, maybe 17.00?

**Smartphone (please complete the following information):**
Tutanota v3.82.8

---
## Task list

- [ ] Reproduce issue (check with support)
  - Not receiving notifications
  - Receiving at wrong time
- [ ] Investigate source code
- [ ] Implement first proposal
- [ ] Improvement: Don't show event time at notification

**Comment by andrehgdias** [comment]
Might be related to this reddit report:
- https://www.reddit.com/r/tutanota/comments/1l4l90h/calendar_event_notification/
- https://www.reddit.com/r/tutanota/comments/1p2vc0u/all_day_event_notifications/
