### ISSUE TITLE
Refactor IPC implementation

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2890]
As a developer I want to easily and safely call into native code and back without manual dispatch or serialization.

**Acceptance criteria**
 - There should be a single definition of a facade that is usable for each platform
 - For each platform we can specify what facades it supports
 - From platform definition code should be generated that makes sure all facades are implemented/added
 - There is a code generator for each platform that generates data types and interface types
 - There should be an automatic dispatcher for each facade that knows how to serialize/deserialize and call the implementation of the facade (given the implementation)
 - If the facade definition fails then type checking for the platform that implements it should not succeed

**Context**
All the apps are using message passing pattern to communicate to different parts of the application:
 - all platforms have page - worker communication
 - mobile and desktop apps have native - web communication

Current implementation of native - web communication is hand-written: we manually dispatch to correct functions and unpack arguments. There's no interface definition for this communication (we don't know which methods are available on which platform or which arguments they need, which types they return). This leads to a lot of manual code and frequent bugs when implementations go out of sync.

Proposed solution: use Interface Description Language to generate code for each platform:
 - facade with methods
 - arguments and return types of such methods
 - the data types used for transfer

We should define what methods are available for each platform.

**Implementation hints**
What we are doing is similar to RPC but is actually IPC. We don't need any code to send the requests, we just need to generate interfaces and data types. Serialization can be plugged in or provided by the library itself.

There are multiple libraries which support description and code generation:
 - protobuf can describe data types and services
 - [quicktype](https://github.com/quicktype/quicktype)
 - Probably more

## Tasks
 - [x] Decide on data types generation approach (quicktype/protobuf/custom)
 - [x] Decide on serialization framework (related to previous)
 - [x] Decide whether we want do definite a specific type for each method parameters
 - [x] Define facade description format
 - [x] Define point where generator is invoked (each build? manually?)
 - [x] Implement data type generator
   - [x] typescript
   - [x] android
   - [x] ios
 - [x] Implement facade interface generator
   - [x] typescript
   - [x] android
   - [x] ios
 - [x] Decide on native message format (JSON like now, separate messages/lines for arguments)
 - [x] Implement dispatcher generator (code that calls the facade)
   - [x] typescript
   - [x] android
   - [x] ios
 - [x] Invoke generator
 - [x] adapt existing code for facade-based interfaces
   - [x] web
   - [x] desktop
   - [x] android
   - [x] ios
  - [ ] Remove all old style calls from web to native

**Comment by ganthern** [comment]
## Test Notes

all ios, android, desktop:
* [ ] display of attachment bubble in mail viewer works (size, filename)
* [ ] opening attachments
* [ ] downloading attachments
* [ ] sending attachments
* [ ] saving credentials
* [ ] deleting credentials
* [ ] getting push notifications
* [ ] sending logs
* [ ] changing the color theme

ios:
* [ ] keyboard size change handling (ie during mail folder rename, password change)
* [ ] display of attachment bubble in mail viewer works (size, filename)
* [ ] getting push notifications
* [ ] opening a link
* [ ] changing the color theme
* [ ] sending mail with contact suggestion from contact app

android:
* [ ] handling the back button to go back to home
* [ ] handling back button to go back inside the app
* [ ] putting app in background and coming back to it
* [ ] sharing from other apps to tutanota
* [ ] sharing from tutanota to other apps (select text, hit share)
* [ ] sending mail with contact suggestion from contact app

desktop:
* [ ]

**Comment by ganthern** [comment]
### Testing

NativeFacade (Desktop)
* [ ] mailto handling works
* [ ] (windows) sending files from file explorer to tutanota works (send as... -> mail)
* [ ] clicking on a notification to open the corresponding mailbox/calendar works
* [ ] calendar alarms are not firing after deleting credentials
* [ ] changing the spellcheck lang from mail editor works (context menu)
* [ ] shortcuts for native operations (new window, ctrl+f) are shown in f1 menu
* [ ] links reveal link address in lower right corner on hover
* [ ] 

NativeFacade (iOS)
* [ ] mailto handling works
* [ ] clicking on a notification to open the corresponding mailbox/calendar works
* [ ] calendar alarms are not firing after deleting credentials
* [ ] keyboard resize (ie during mail folder rename) moves the input dialog

NativeFacade (Android)
* [ ] mailto handling works
* [ ] clicking on a notification to open the corresponding mailbox/calendar works
* [ ] calendar alarms are not firing after deleting credentials
* [ ] back button works as expected
* [ ] app continues to work when put in the background and brought back

SystemFacade (Desktop)
* [ ] logging out reloads the webview
* [ ] getting logs from "about" dialog attaches native logs
* [ ] open new window from drawer menu button works

SystemFacade (iOS)
* [ ] logging out reloads the webview
* [ ] getting logs from "about" dialog attaches native logs
* [ ] contacts from system contact app are suggested in mail editor
* [ ] adding an OTP 2nd factor to the system OTP app works

SystemFacade (Android)
* [ ] logging out reloads the webview
* [ ] getting logs from "about" dialog attaches native logs
* [ ] contacts from system contact app are suggested in mail editor
* [ ] sharing a link to a gift card works

ExportFacade (Desktop)
* [ ] exporting mail as msg works (check desktop settings)
* [ ] exporting mail as eml works 
* [ ] dragging mail(s) to the file system to export works

FileFacade (Desktop)
* [ ] opening attachments from viewer works
* [ ] downloading attachments works
* [ ] selecting a save location for an attachment works
* [ ] selecting a default save directory for attachments works
* [ ] attachments are displayed correctly (name, size)
* [ ] sending attachments works

FileFacade (iOS)
* [ ] opening attachments from viewer works
* [ ] downloading attachments works
* [ ] attachments are displayed correctly (name, size)
* [ ] sending attachments works

FileFacade (Android)
* [ ] opening attachments from viewer works
* [ ] downloading attachments works
* [ ] attachments are displayed correctly (name, size)
* [ ] sending attachments works

CredentialsFacade (Desktop)
* [ ] credentials can be saved
* [ ] credentials can be deleted

CredentialsFacade (iOS)
* [ ] credentials can be saved
* [ ] credentials can be deleted
* [ ] using biometrics for credentials works
* [ ] using device pin for credentials works

CredentialsFacade (Android)
* [ ] credentials can be saved
* [ ] credentials can be deleted
* [ ] using biometrics for credentials works
* [ ] using device pin for credentials works

CryptoFacade (Android)
* [ ] sending mail to another tutanota user works
* [ ] opening mail from another tutanota user works

CryptoFacade (iOS)
* [ ] sending mail to another tutanota user works
* [ ] opening mail from another tutanota user works

PushFacade (iOS)
* [ ] extant alarms are scheduled on logging in with a new account
* [ ] new alarms are scheduled while logged in

PushFacade (Android)
* [ ] extant alarms are scheduled on logging in with a new account
* [ ] new alarms are scheduled while logged in

PushFacade (Desktop)
* [ ] extant alarms are scheduled on logging in with a new account
* [ ] new alarms are scheduled while logged in

SearchTextInAppFacade (Desktop)
* [ ] the ctrl+f search bar updates its content as expected
* [ ] it can be closed with the button, ctrl+f and esc

SettingsFacade (Desktop)
* [ ] desktop settings are displayed correctly 
* [ ] autolaunch can be enabled/disabled
* [ ] desktop integration can be enabled/disabled
* [ ] launch on boot can be enabled/disabled
* [ ] (un)registering as a mailto handler works

ThemeFacade (iOS)
* [ ] custom themes can be applied
* [ ] color theme can be changed and is persisted

ThemeFacade (Desktop)
* [ ] custom themes can be applied
* [ ] color theme can be changed and is persisted

ThemeFacade (Android)
* [ ] custom themes can be applied
* [ ] color theme can be changed and is persisted

**Comment by ganthern** [comment]
### Testing (iOS)

NativeFacade (iOS)
* [ ] mailto handling works
* [ ] clicking on a notification to open the corresponding mailbox/calendar works
* [ ] calendar alarms are not firing after deleting credentials
* [ ] keyboard resize (ie during mail folder rename) moves the input dialog


SystemFacade (iOS)
* [ ] logging out reloads the webview
* [ ] getting logs from "about" dialog attaches native logs
* [ ] contacts from system contact app are suggested in mail editor
* [ ] adding an OTP 2nd factor to the system OTP app works

FileFacade (iOS)
* [ ] opening attachments from viewer works
* [ ] downloading attachments works
* [ ] attachments are displayed correctly (name, size)
* [ ] sending attachments works

CredentialsFacade (iOS)
* [ ] credentials can be saved
* [ ] credentials can be deleted
* [ ] using biometrics for credentials works
* [ ] using device pin for credentials works

CryptoFacade (iOS)
* [ ] sending mail to another tutanota user works
* [ ] opening mail from another tutanota user works

PushFacade (iOS)
* [ ] extant alarms are scheduled on logging in with a new account
* [ ] new alarms are scheduled while logged in

ThemeFacade (iOS)
* [ ] custom themes can be applied
* [ ] color theme can be changed and is persisted

**Comment by johnbotris** [comment]
**iOS**: receiving a mail while logged in caused the app to logout and then back in. Doesn't happen consistently

**Comment by johnbotris** [comment]
**ios**:  clicking on email notification does not open the respective mailbox

**Comment by charlag** [comment]
> **ios**:
> 
>     * clicking on email notification does not open the respective mailbox
> 
>     * alarms from deleted credentials still fire

alarms are expected, notifications need to check

**Comment by ganthern** [comment]
> alarms are expected

that's a bug, right?

I could only find this https://github.com/tutao/tutanota/issues/2523, which is a little different, so should we make a new one?

**Comment by ganthern** [comment]
> **iOS**:
> 
>     * receiving a mail while logged in caused the app to logout and then back in. Only happened once so far
>       
>       * also happened when clicking on an item in the mail list

doesn't seem to be a problem with 3.98.3
