### ISSUE TITLE
Allow generating password when signing up for account

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#327]
As a user i want to have the option to generate a strong memorize-able password to pass the password check when signing up for a new account so that i don't have to use a password manager to create a Tutanota account.

**Acceptance criteria**
- Option to generate password is available on signup page when password input is required.
- Generated password must be good enough to pass the password check.
- Generated password must be secure.
- Generated password should be memorize-able.

**Tasks** 

* [x] rebase branch
* [x] fix word library location so that it can be retrieved by the client when generating passwords
* [x] rearrange buttons in the passphrase generation dialog: confirm to the bottom, copy and regenerate to bottom
* [x] write FAQ entry
* [x]  link FAQ entry in the dialog
* [x] redesign reveal button to align with other inline buttons
* [x] remove password confirm input field as we now have a reveal button.

## Test notes
 - [ ] Passphrase generator dialog can be opened during signup
   - [ ] web
   - [ ] desktop
   - [ ] ios
   - [ ] android
- [ ] Regression: send contact form request, password field works as expected
- [ ] Changing own password
- [ ] Changing password of another user as an admin
- [ ] Password during signup is still checked for strength, it is indicated by completeness bar and status message
- [ ] Password can be hidden/shown (test in any place)
- [ ] Passphrase generator can regenerate passwords
- [ ] Passphrase generator can copy password
- [ ] Passphrase generator does replace password in the password field
