### ISSUE TITLE
Calendar navigation improvements

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3508]
As a user of the Tutanota calendar i want to have a view selector visible on each calendar view so that i can easily switch between the views and don't have to deal with back and forth navigation to see events of one day.

## AC  
* There is an option to switch between views in the toolbar  
   * 1 column layout: (Agenda, Day, Month)
   * 2 column layout: (Agenda, Day, Week, Month)
   * 3 column layout: (Agenda, Day, Week, Month)
* A day selector appears for day and agenda view
    *  First row shows weekday name. Week starts on monday or sunday depending on the setting.
    * Day of the month number appears below the week day name.
    * A dot should appear below the day of the month number to indicate that there is at least one event on that day
    * Left/right swipe gesture changes the week
    * When the week changes the selected day changes to the same week day of that week.
* Agenda view shows only the events of the selected day
   * First row shows event title
   * Second row shows start and end time
   * Second row shows "all-day"/ "Ganztägig" for all day events
   * For long/multi day events it shows 
       * start time if the event starts on that day and is not an all day event
       * end time if the event  ends on that day and is not an all day event
       * "all-day"/ "Ganztägig" in all other cases
* There is a "Today" selector in the toolbar which always sets the selected day to the current day. The icon shows the current day number.
* There is a button to extend the day selector to a day of month selector
* Selecting a day in the month view opens the agenda view for that day.

## Images

![calendar-navigation](https://github.com/tutao/tutanota/assets/8296817/431753cc-d2fc-4b2e-bd86-332708d105dd)

## Tasks
- [x] Add option to switch between views in toolbar
   - [x] Single column layout as shown in picture above
   - [ ] Today selector with icon showing current day number
- [x] #6099
- [x] Day selector can be extended to month selector
   - [x] Selecting day in the month opens that day
   - [x] Single dot indicator below days with at least one event 
- [x] Agenda view
  - [x] Entry with First row being event title and second row showing time
  - [x] "All day" for all day events (make sure translations work)
- [x]  Selecting a day in the month view opens the agenda view for that day (instead of day view)

## ui team review changes
- [x] Different color for padding days and header, try lighter grey (Month View - 1/2C Layout)
- [x] Make text for week day names bold, always use one row for week day name and one row for the day in all views.
- [x] Use only one letter for week day name in mobile layout, for two and three column layout use three letter. 
- [x] Reduce the distance between week day names and days
- [x] Change icon for  "today" action so that it looks like the proposed one. Ensure that the size is the same as the week selector.
- [x] Only show month name next to the hamburger menu in each view.
- [x] Use pop up as month day selector on larger screens (2 column layout)
- [x] Change selected/current day indication
   - [x] Use light red background for selected days
   - [x] Try grey background for current day
   - [x] Remove bar indicator from all views
   - [x] Only show selected day in day and agenda view 
- [x] Try to remove line below the header in time based views.
- [x] Allow week view for 1 column layout.
- [x] Make smaller time column. Use only two letters for time. am/pm should be rendered below
- [x] Shift day selector to the right by the size of the time column, so week day names align with week columns
- [x] Apply same shifting for the day selector in day/week and agenda view.

## Review 22.11
- [x] Highlight today on Day Selector in all views
- [x] On Week/Day view, always display long events for the current week and size them according to the size of the days in Day Selector
- [x] Fix the Day Selector expanded when the user turns the device
- [x] Fix the Week day names on Month view
- [x] Highlight the entire selected week in the Day Selector when expanded on the week view

## Review 24.11
- [x] Month view padding days:
  - [x] Try lighter grey for day numbers.
  - [x] Keep white background.
  - [x] Remove line below header.
  - [x] Change border color to #e1e1e1
- [x] Day /Agenda
  - [x] Not use different color for days when the day selector just shows one week.
  - [x] Change opacity for selected day indicator to 0.20
  - [x] Agenda. Align events to content week grid
  - [x] Agenda (two column layout): fix padding-left for day selector.
- [x] Day view
  - [x] Show only long/all day events of that day.
- [x] View selector
  - [x] Change order of items to Agenda, Day, Week, Month.
- [x] Week view
  - [x] Use rounded corners for week selection in expanded day selector
- [x] Fix today button tooltip

## Notes

| Problem | Platform | Suggestions |
|--------|--------|--------|
|When in day view i cannot easily switch to another day, i have to go back/select to the month view and then pick another day.| mobile | 1. Allow opening a date picker from the day view, 2. Show days of the week on top of the day view.|
| Week view for mobile devices. Possible implementations: | mobile | 1. Put day numbers at top of day view that allow for selecting a specific day 2.  A week view that looks like a small version of month view (3x3 or 2x4) 3. Show existing week view on larger mobile devices (two column layout)|
| Switch between views should be accessible without opening the side menu so it is clear from the user interface how to change views. Example: when i am in the day view on mobile i have to go back to the month view, then open the side menu and then select agenda to have an agenda style view. | mobile | Add view switcher to the toolbar. |
| On mobile devices the month view opens by default and i have to navigate to the day view by clicking on the tile. | mobile | Show day view by default, introduce date picker, show days of the week on top of the day view. |
| In the month view i often cannot see all events of the current day because they don't fit into one tile, more events are marked with (+x). | mobile/desktop | 1. Desktop: Introduce third column which shows a day view of the selected day. 2.Mobile Do not navigate to day view but rather show larger tile/dialog with all the events on that day. 3. Navigate to agenda view| 
| In the day view we show a time based calendar. To get an overview of what is happening on that day it would be better to have agenda style view.  | mobile | 1. Allow switching between agenda and time based calendar from day view 2.Reduce the size for one hour so more hours fit on screen 3. Scroll to the first event of that day. | 
| In desktop layout i have to select the day or week view from the nav column explicitly to see all entries of that day. | desktop | Introduce third column in desktop layout which shows a day view of the selected day. | 

## Test Notes
- [ ] A day picker is shown in Day view
- [ ] A day picker is shown in Agenda view
- [ ] The user can expand/contract the day picker
- [ ] The day picker is only shown in single column layout
- [ ] The other layouts doesn't appears
- [ ] Days if events have a dot bellow the day number
- [ ] Adding an event will add a dot to the respective day
- [ ] All the functions of the agenda and day view still working
- [ ] The week in the day picker starts according to user's config
- [ ] Swiping the day picker while expanded:
   - [ ] To the right, goes to the previous month
   - [ ] To the left, goes to the next month
   - [ ] The selected day should be the same day of month
 - [ ] Swiping the day picker while contracted:
   - [ ] To the right, goes to the previous week
   - [ ] To the left, goes to the next week
   - [ ] The selected day should be the same day of week
 - [ ] View type selector is shown in the leftmost column on desktop
 - [ ] View type selector is show in the header on mobile and it works
 - [ ] Today button works is displayed in header on mobile and it works
 - [ ] Clicking on a day (anywhere, including day number) in month view on mobile opens agenda for that day
   - [ ] it still creates an event on desktop when clicking not on  day number
   - [ ] It still opens day view on desktop if you click on the day number
 - [ ] On desktop agenda always shows  events of the next days, independent of the selected date
 - [ ] Mobile agenda only displays the part of the event that falls on the day
 - [ ] Mobile & desktop agenda shows "all day" correctly

**Comment by ganthern** [comment]
I'll just drop a mention here https://github.com/tutao/tutanota/issues/2429

**Comment by kibhub** [comment]
updating event in day and agenda view throws error but updates event successfully:
![image](https://github.com/tutao/tutanota/assets/104761667/dc2fd91f-9a8a-4dc6-85c7-ef9c9ccc5f38)

**Comment by kibhub** [comment]
day numbers in month view on desktop are not highlighted on hover any more

**Comment by murilopereirame** [comment]
> day picker is available in two column layout, in contradiction to test notes. But I think that this was an intentional change?

yes, forgot to update, thanks for informing

> updating event in day and agenda view throws error but updates event successfully

Related to #6207 and already have a fix for it #6208 


Have to take a look on the other ones

**Comment by olof-nord** [comment]
This is such an improvement. Christmas came early this year, thanks!
