### ISSUE TITLE
Enable calendar when offline

### ISSUE THREAD

**Issue by vaf-hub** [tutao/tutanota#3699]
As a user, I want to have access to my calendar when i am offline.

**Acceptance criteria**
- [ ] Calendars are always completely downloaded and stored locally
- [ ] Calendars are available when the device is not online.
- [ ] Local calendar events are updated and new events are downloaded whenever connected to the server

**Tasks**
- [x] Ensure calendars are downloaded when offline storage is enabled (not yet events)
- [x] Decide how to support calendar event customIds in range requests. (some kind of range request or load complete range)
- [x] Decide when to load calendar events and load all calendar events
- [x] Implement opt-in for customId types, start with CalendarEvent

**Implementation hints**
CalendarEvents have custom Ids. This means that currently we do not keep track of ranges requested in the EntityRestCache. Since it is possible to make range requests for CalendarEvents we should also keep track of which ranges were requested and then automatically load them into cache when we receive and entity event update that falls into that range.

We would benefit from this behavior after #2946 has been implemented, because we could reduce the number of requests by using get multiple just in one place (most relevant for calendar imports). Currently, entity updates for CalendarEvents are handled and the events are loaded in the CalendarModel and CalendarViewModel, which may lead to making GET requests for single CalendarEvents instead of loading them all in one request. In the CalendarViewModel all updates are loaded while in the CalendarModel only those with alarms are loaded. Without EntityRestCache making the decision which events should be loaded into cache, we have to collect and make get multiple requests for those events in several places.

Also we should evaluate if we really want to continue to schedule alarms locally in the browser in the CalendarModel. Getting rid of browser event reminders might help not loading events after entity updates in the CalendarModel at all and it might be  a rarely used functionality as reminders are most relevant to the apps.

We should take into consideration that the way we load and cache CalendarEvents also affects #590 and it should carefully be decided what is the desired behavior with that in mind.

**Comment by charlag** [comment]
As discussed with @sarashub @armhub @ganthern 

There are multiple options to cache calendar events:
 - extend existing cache one way or another to handle calendar events:
   - one option is to convert all custom IDs into Base64ext to make them sortable. Seems to be error prone to change it anywhere
   - another option is to add SQL function to load all entities without filtering
 - completely custom cache for offline
   -  still needs custom SQL
   - hard to integrate with entity event handling: out of sync, last processed event etc

We decided to try option with custom SQL in the existing cache, do sorting there (injected?) and throw away the rest.

**Comment by charlag** [comment]
With test 1 (first login, offline, calendar) I still get an offline error (usergrouproot) even thought calendars open. I think it's about invitations. Not sure if we need to handle it somehow
