### ISSUE TITLE
Handle connection errors when in offline mode

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3813]
As a user i want to be able to read my emails while in offline mode without showing any blocking error message. 
Server request that are made while navigating through the application should not lead to a blocking connection error dialog.

**Acceptance criteria**
- Selecting an email from the list does not change read state and does not show offline dialog.
- Modifing operation in the background should not trigger errors (Inbox rules, entropy update, queued entity updates, scheduling alarm notifications)
- For specific modifing user interactiona ( e.g. creating folder) a connection error dialog is shown.
- Read operation of not offline available MailBody should show message in place of MailBody.
- Loading of list should show retry option as last element of the in case of connection error.

**Tasks**
- [x] Catch ConnectionErrors when selecting an email
- [x] Check which user interactions leads to connection error in the mail view. 
- [x] Show offline error as list item when loading/extending list. Allow retry.
- [x] Catch connection errors when loading all parts of an email (body, attachments, conversation entry) and allow retry if parts of them are not available.
- [x] Cleanup maintenance.png.

**Implementation hints**
To have non blocking connection error messages we had the idea to use the snack bar. We will show it in case a ConnectionError appears but it should not show up every time when open an unread email. We need to check if this idea works out. 

Actual write operations that are allowed while offline will be implemented with this issue:
https://github.com/tutao/tutanota/issues/3443

**Test notes**

- [ ] have a partially loaded mail list, go offline and scroll down, observe  that offline error is shown as list item and contains a retry button
- [ ] go online again, click on retry button in the mail list and observe that everything is loaded correctly
- [ ] have a mail list, go offline, click on a mail, observe that it shows retry banner in mail body
- [ ] have a mail list, click on a mail, go offline after the body but before attachments are loaded, observe that it shows retry banner in mail body
- [ ] go online again, click on retry button in the mail body and observe that everything is loaded correctly
- [ ] select a different mail folder while offline, observe that offline error is shown as list item and contains a retry button
- [ ] go online again, click on retry button in the mail list  and observe that everything is loaded correctly
- [ ] open contacts while offline, observe that offline error is shown as list item and contains a retry button
- [ ] go online again, click on retry button in the contact list  and observe that everything is loaded correctly
- [ ] Enable search while offline, observe that the error dialog contains the reason and a retry button
- [ ] go online again, click the retry button, observe that indexing works correctly
- [ ] have search enabled, delete offline database (from config folder), search and go to search list, observe  that offline error is shown as list item and contains a retry button
- [ ] go online again, click on retry button in the search list  and observe that everything is loaded correctly
- [ ] Try sending a mail while offline, observe that error message contains the correct reason
- [ ] Try saving a draft while offline, observe that error message contains the correct reason
- [ ] Log out while offline without saved credentials, observe that you go back to login view
- [ ] verify that other unhandled connection errors result in a snack bar being shown

Regression testing is required as MailViewer and List were refactored in the scope of this issue

- [ ] Loading spinner should always show in the list when it is loading and we still have a connection
- [ ] Neither connection error nor loading spinner should be shown, when we have a fully loaded list
- [ ] Lists in the admin client work as expected
- [ ] Connection errors are shown in the snack bar by default in the admin client

MailViewer actions:

- [ ] mark read (from top menu)
- [ ] move mail (drag and drop, top menu, or via shortcut)
- [ ] delete mail (drag and drop, top menu, or via shortcut) 
- [ ] archive mail (drag and drop, top menu, or via shortcut)
- [ ]  report 
- [ ]   show email headers (from top menu or shortcut)
- [ ]   Add spam rule
- [ ]  add inbox rule 
- [ ]  reply or forward (click or shortcut)
- [ ]  add folder 
- [ ]  export (from top menu or drag and drop) 

- [ ] loading a mail 
- [ ] inline images are downloaded
- [ ] loading attachments
- [ ] downloading and opening attachments
- [ ] printing a mail
- [ ] banners are shown for: spam, phishing, authentication state,  external images, events
- [ ] set rules for external images and verify that everything behaves correctly
- [ ] receive calendar event invite and update and make sure that all renders and behaves correctly
- [ ] Sanitization still works
- [ ] Forwarding emails with inline images that are loaded or not loaded works
