### ISSUE TITLE
Offline indicator

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3815]
As a user i want to be informed about the current offline/online state so that I am aware that not every interaction with the application leads to a valid result (e.g. creating an email folder).

The indicator should also not visually distract me (like the current candy bar) and should be non blocking.

**Acceptance criteria**
- Show offline indicator if application state is in offline mode.
- Switch to offline mode if initial downloading session fails during the login process.
- Switch to offline mode when websocket connection is lost.
- Switch back to online mode if websocket connection is established (use same exponential backoff).
- Switch back to online mode if a successful request is made
- If the initial attempt to resume the session fails and it falls back to offline login, then a reconnect button is shown as part of the offline indicator

**Tasks**
- [x] Create and discuss a mockup of the offline indicator
- [x] Replace candy cane/bar with new indicator.

**Implementation hint**
We need to  create a proposal for an offline indicator. It should be always visible and not distracting. Just showing the text "offline" instead of the candy bar might be sufficient but we need to find a good spot for it (bottom of navigation column, header bar).

**Comment by ganthern** [comment]
## Testing
this needs to be tested in all browsers and in the desktop client.

* [ ] the offline indicator doesn't show on the login screen
* [ ] tbd

### Offline Indicator

### Regressions
 * [ ] calendar navigation in title still works
 * [ ] tbd

**Comment by charlag** [comment]
I tested on Safari & mac Desktop
