### ISSUE TITLE
Encrypt persistent email cache for desktop client

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3816]
As a user of the desktop client i want my offlline data to be encrypted so that it is secured from mallicious actors who has access to the device.

**Acceptance criteria**
- Offline data is stored encrypted.

**Tasks**
- [x] Select SQLCipher lib 
- [x] Compile lib for all operating systems (win, macOS, linux), integrate into application build process
- [x] Integrate lib into native part of Tutanota
- [x] Secure database key with credentials key
- [x] Configure SQLCipher lib 

**Implementation hint**
The offline data should should be stored in encrypted database using database key which is then secured with the credentials key which is stored in a secure way (#3733). The encrypted data can be access by anyone who has access to the keychain.
