### ISSUE TITLE
Persistent email cache in the desktop client

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#3823]
As a user, I want to be able to read my emails in the desktop app even after I lose my internet connection so that I can find information to do my work no matter what my connectivity is.

**Acceptance criteria:**
 - [ ] When no mail index is enabled and I loaded mail list during previous usage I can view it again, even if I didn't view it this time
 - [ ] When no mail index is enabled and I viewed mail body during previous usage I can view it again, even if I didn't view it this time
 - [ ] When search index is enabled I can view all the mails and mail bodies that are in the indexed time period

**Tasks**
- [x] Select and integrate SQL-Lite database
- [x] Define a database model
- [x] Implement native wrapper around database (OfflineDbFacade)
- [x] Implement CacheStorage for offline (connect EntityRestCache to native database)
- [x] Adapt EntityRestCache to replay entityUpdates between different times the user is logged in
- [x] Make sure offline cache is used in mail indexer
- [x] Handle out-of-sync situation for EnityEventUpdates (need to delete database and start caching again)
- [x] Make sure indexer works together with downloading entityEvents between logging in (for offline)

**Implementation hints:**
Data should always be read from the offline storage first even if the user is online.
This is a minimal version of what offline will be and it does not include encryption or offline login. This also does not include any of the UI changes (error handling, retry mechanisms etc).
This does not imply that search index data is stored in the same database.
