### ISSUE TITLE
Handle out of sync offline database

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3852]
A user's offline database may go out of sync with the server (in the same way that the search index does). When this happens, we need to avoid that the user's local database will be in an out of sync state, without disturbing the user with too many technical details, and also avoiding triggering the DDOS mitigation.

We have decided that the strategy to handle out of sync is to purge the existing local database. Whether we refill the database afterwards will be determined by how we decide to initialise a new database (either pre-emptive or save as we go)

### Acceptance criteria
 - When logging in and the database is detected as being out of sync, the database is purged
 - The user should be informed that their offline data has been deleted due to being out of sync.
 - The database will then be newly rebuilt as the user accesses their data.

### Tasks
- [x] detect that the database is out sync when restoring a session
- [x] delete the database when out of sync it is detected
- [x] create a new database before the user makes any more requests
- [ ] inform the user in a non-obstructive way 

### Notes
 - Once offline login is enabled in the future we will have to deal with: 
     - When logging in while offline, once the user comes back online and out of sync is detected, the database is purged

**Comment by johnbotris** [comment]
# Test notes

The TTL for entity events is 45 days, which means if a client hasn't processed entity events in 45 days, then it's offline database will no longer be synchronised with the server. This should be detetcted both at login as well as on websocket reconnect.

You probably won't be able to test this properly on the test system, as  the out of sync time is hard coded. You will want to build a test client locally with a reduced out of sync duration and test with that

- [ ] When logging in and the client is not out of sync, offline data is not purged
- [ ] When logging in and the client is out of sync, offline data is purged
- [ ] When reconnecting to websockets and the client is not out of sync, offline data is not purged
- [ ] When reconnecting to websockets and the client is out of sync, offline data is purged
