### ISSUE TITLE
Provide option to protect saved credentials with application pin

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3853]
As a user of the desktop client i want to be protect my stored credentials with an application pin so that other people that are using my device are not able to read my emails.

#### acceptance criteria
- [x] Add another encryption method for credentials that uses a custom device password (e.g. "own pin", "device pin", "custom password"). 
- [x] If using "own pin" encryption, then the pin will be requested from the user when trying to login.
- [x] The PIN is per device

#### Tasks
- [x] Decide whether show the dialog in the renderer process or in the main process
- [x] Decide whether to do argon2 in the renderer process or in the main process
- [x] Add another credential encryption method for desktop
  - [x] generate a salt and use it with argon2 to create a password hash
  - [ ] ~persist the salt and hashed password~
- [ ] Verify if App-Passwort / App password is ok or if we should App-Lock

#### implementation hint
 -  The device key encrypts the stored credentials and the device key is stored in the keychain of the device. As soon as the keychain is unlocked someone can decrypt the credentials. As we cannot rely on having "biometrics/system password" available like we have witihn the mobile application we want to at least provide an option to secure the saved credentials for desktop applications.

 - Do not  take care of changing pin explicitly in this iteration, users can switch to automatic and back to pin as a workaround

This is a followup up issue of https://github.com/tutao/tutanota/issues/3733

## Test Notes
* [ ] no encryption options are shown in the browser and all old and new saved credentials can be used
* [ ] on android and ios, biometrics/device pin/device lock optios still work as expected
* [ ] on desktop, we have device lock and app pin
* [ ] when activating app pin, all credentials are migrated and still work (using them requires the pin)
* [ ] when deactivating app pin, all credentials are migrated and using them does not require the pin anymore
* [ ] while app pin is active, all operations that try to use or change credentials require the app pin
  * deletion
  * storing
  * deactivating the pin
* [ ] cancelling any of the prompts or typing in the wrong pin doesn't cause errors
* [ ] chaos test with multiple windows and credentials in various states, turning on and off the app pin feature at different points

**Comment by murilopereirame** [comment]
- Desktop issue:
  - If I enable the App Password and try to add an account, cancel when the pin is requested and hit login again, the app stucks at "Logging in..." dialog and I've to restart the app. The same happens if I enter an invalid password.
  - The error in console is "Offline db is closed"

Is this ```device lock``` the macOS keychain password that is asked when we open the app?

**Comment by rezbyte** [comment]
Not really an issue but if you remove the pin before you press 'ok' on the login dialog, the client is logged in without pressing anything & another dialog saying 'Try again' appears.

Another one I found is that if you remove the pin while you have the pin dialog open (same as above) then press 'ok' without anything typed into the text field, an uncaught failed promise occurs in `MessageDispatcher.ts` line 110.

**Comment by ganthern** [comment]
> Not really an issue but if you remove the pin before you press 'ok' on the login dialog, the client is logged in without pressing anything & another dialog saying 'Try again' appears.

working as intended, we detect the change in the credentials storage method. there's just no way to cancel the password prompt currently, so it's not doing anything.

> Another one I found is that if you remove the pin while you have the pin dialog open (same as above) then press 'ok' without anything typed into the text field, an uncaught failed promise occurs in `MessageDispatcher.ts` line 110.

I can't reproduce this when using a stored account or a new login to submit the empty password, is any additional setup required or  is it timing dependent? A step by step or screencast would be helpful :)

**Comment by rezbyte** [comment]
> I can't reproduce this when using a stored account or a new login to submit the empty password, is any additional setup required or is it timing dependent? A step by step or screencast would be helpful :)

I just tried reproducing this now & got a completely different error:
```
Feedback v3.119.2 - Error - UNKNOWN - linux



 Client: linux
 Type: UNKNOWN
 Tutanota version: 3.119.2
 Timestamp (UTC): Tue, 05 Dec 2023 06:29:34 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop-debug/3.119.2 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
Error
 Error message: can't remove app pass wrapper without salt
Stacktrace: 
Error: can't remove app pass wrapper without salt
    at DesktopNativeCredentialsFacade.removeAppPassWrapper (/home/jat/dev/repositories/tutanota-3/build/desktop/DesktopMain.js:77340:13)
    at async DesktopNativeCredentialsFacade.decryptUsingKeychain (/home/jat/dev/repositories/tutanota-3/build/desktop/DesktopMain.js:77325:27)
    at async ipc (/home/jat/dev/repositories/tutanota-3/build/desktop/DesktopMain.js:77801:18)
```

As for the steps:
1. Open an account in a window (1)
2. Set a pin in the settings in window 1
3. Open another window (2) on the saved credentials screen
4. Click on the same account in window 2 so the pin entry dialog will open
5. Set the unlock method back to 'Automatic Unlock' in window 1
6. Click ok on the pin dialog in window 2
7. See the error dialog that appears in window 2
