### ISSUE TITLE
Support for FIDO U2F devices in mobile/desktop apps

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3865]
As a user i want to be able to use (login and register) my FIDO U2F security key as a second factor in the desktop client and in the mobile apps. A security key that is registerd on mobile/desktop application should also be usable within the web version and vise versa.

**Acceptance criteria**
- Allow setting up a security key in Settings > Login
- When security key is registered in desktop client it is always registered for https://mail.tutanota.com/
- Authenticate with security key as second factor in desktop client/mobile app
- Authenticate with the same key in web client on https://mail.tutanota.com/
- Autenticate with key that has been registered on whitelabel domain.

**Tasks**
- [x] Add support for desktop client #2178 
- [x] Add support for androip app #443 
- [x] Add support for ios app #2177

**Comment by bedhub** [comment]
Hey, we have support within all supported apps now, so we can close this issue!
