### ISSUE TITLE
Offline login process

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3888]
As a user i want to have access to my offline data after the application start so that i don't have to ensure that an internet connection is available to read my emails.

**Acceptance criteria**
- Offline login is only available for Premium users
- After application start the list of accounts with offline data is visible.
- Selecting one of the accounts provides access to the stored offline data.
- When there is no internet connection there should be no error dialog and offline data is shown.
- When there is a internet connection the usual login process with the stored session continues and the application synchronises with the server state.
- When there is an internet connection and the stored session is not valid anymore the application should ask for authentication.
- Offline data will not be removed because of an invalid session.
- Out of sync is handled once the internet connection is restored #3852

## Tasks
 - [x] Always put user into the cache, also on the first login
 - [x] Add a listener for online state to attempt to log in in background if the first attempt fails
 - [x] Change `isLoggedIn()` logic to be more granular, to be able to handle states: not logged in, logged in offline, fully logged in
 - [x] Implement UI for auth if needed while already in mailbox to avoid losing local data
 - [x] If we are calling something that needs authentication, we should handle it instead of kicking user out of the app
 - [x] Adjust logic to only allow premium users to log in offline
 - [x] Be able to change cache parameters during runtime (e.g. error happens during login and then user selects another account, we need another cache)

## Test notes
 - [ ] Test that old recovery codes can still be used
 - [ ] Test that recovery codes can be viewed correctly (same as before)
 - [ ] Test that recovery codes can be used and do work
 - [ ] Regression: sending/receiving emails as external user
 - [ ] Regression: can decrypt e2e emails from other people and read them afterwards
 - [ ] Regression: can read sent e2e emails
 - [ ] Test that domain verification entries are generated and shown correctly (the t-verify ones): try to add custom domain
 - [ ] As a free user, enable offline, log out, disable network, log in with saved credentials. Should see error message about offline for premium.
 - [ ] As a premium, enable offline, log out, disable network, log in with saved credentials. Should see offline mailbox.
 - [ ] Once eventually online the search is available
 - [ ] Registering for push notifications (remove config, log in, receive notification)
 - [ ] Test failed login after the offline login
   - Save credentials as a premium user
   - Log in from another device/browser
   -  Log out in the first app, go offline, do offline log in
   - Close original session from that other device/browser
   - Go online in the first app, see that there's a login prompt and after typing correct password we re-login, credentials are re-saved and database is not purged
   - [ ] Also check that the scenario above works with 2FA
 - [ ] Try out scenario: persistent credentials are no longer valid (with sync login of free account) and log in via form afterward
   - [ ] log into the same account
   - [ ] log into another account
