### ISSUE TITLE
Only store required/desired data in offline cache

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3992]
As a user I want to be able to configure a time range for offline data to be stored. I also don't want that data is stored forever, or that my spam or trash folders are saved offline. I may also want to guarantee that I have some data available after enabling offline mode, without having to manually open every mail. If my database goes out of sync with the server, I probably still want to have some mails available after having logged in again.

#### Acceptance criteria
 - Premium users are able to decide how far back in the past their offline data is stored
 - Spam and trash folders are not saved locally
 - Free users have a limited time range for stored data of up to 31 days
 - Data that is older than the configured time range is removed from the cache

#### Tasks
- [x] Add option to email settings specifying how many days back in time to store data.
- [x] Implement cleanup logic for entities outside of time range
- [x] Implement cleanup logic for trash and spam folders
- [x] Store specified time range
- [x] Clean up unwanted data on login
- [x] Take care of partially returning range.

**Comment by ganthern** [comment]
I think this should have been closed when https://github.com/tutao/tutanota/pull/4051 was merged

**Comment by johnbotris** [comment]
Loaded data will always be stored in the offline cache, and is cleared upon login
### Test Notes
- [ ] When offline mode is not enabled, no "Local data" section is shown in "Email Settings"

Test these with offline mode enabled (on desktop, login for the first time, go to Desktop settings, enable offline mode, log out and back in):
- [ ] A free user is not allowed to configure the time range, it is always set to 31 days
- [ ] A premium user is allowed to configure the time range
- [ ] If a premium user changes their time range, and then downgrades, the time range will be reset to 31 days at next login
- [ ] when loading a mail list while offline, only mail data that falls within the configured time range is available. All of those mails are totally available - mailbody, mailheaders, attachments list (but not the attachments or inline images themselves)
- [ ] When only part of a mail list successfully loaded, the retry button still shows.
- [ ] When coming back online, the retry button will successfully load the rest of the mail list
- [ ] trash and spam folders are always completely cleared
- [ ] only mail data is cleared: things like contacts and such will be available offline, regardless of the configured timerange
- [ ] when the offline data is cleared, the sqlite database itself should see a decrease in size (by default, sqlite doesn't shrink the database when doing `DELETE FROM`)
- [ ] #4079 

#### Regression tests
- [ ] loading of all lists. Lists should :
    - [ ] Contacts
    - [ ] Users
    - [ ] Templates
    - [ ] Search



##### Testing hints:
- [ ] You should test offline mode by actually disabling your network connection; some download requests (i.e. attachments) go via the native part, so turning off the network in dev tools will not correctly simulate being offline
