### ISSUE TITLE
Offline mode for android application

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#4030]
As a user, I want to be able to access my data from my phone when I have an unstable internet connection.

**Acceptance criteria**
- Offline data is stored encrypted on the device
- Same offline login and caching behavior as the desktop client
- The sqlite-sqlcipher build is part of the android build
- Storing and reading mail bodies from the offline db should be faster then reading from the server.

**Tasks**
- [x] Move SQL code from platform-specific code into the web part (use generated facade)  #4293 
- [x] Native sql lib #4294 
- [x] Adapt native android app. #4295

#### Implementation hints
We should only need to implement an offline database on the native side, and the rest should *just work*
Large mail bodies could cause lag when encoded for transfer to the DB, but we will try it this way anyway

**Comment by nif-tutao** [comment]
All the tests have been passed, however when restoring connection and being prompted for the account password due to a session closure from another instance of the account (another app or web/client) the following error message appears:

Feedback v3.98.22 - java.lang.NullPointerException - PREMIUM - android

The app can still function after entering the password despite the error message shown.
