### ISSUE TITLE
Fix out of sync handling

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#4067]
We had a gap in our offline design.
Currently we handle out-of-sync in two places:
 1. On cache init (on offline login)
 2. On websocket connection being established

The problem with 1. is that we can't check out-of-sync there yet as we don't have server timestamp at that point.
The problem with 2. is that there might be concurrent writes (possibly in other windows).

## Acceptance criteria
 - [x] After logging in offline when the db would be out of sync the client works normally
 - [x] After logging in offline and then coming online when db is out of sync the dialog is shown which informs user about the situation.
 - [x] After dialog is closed the user is logged out and the database is cleared
 - [x] If the user is logged in in multiple windows all of them will be logged out
 - [x] Tentative: keep configured offline time range when deleting database

## Implementation hints
Currently configured offline time is stored in the database. If we want to keep it we should move it to the deviceConfig as it will be harder to do later

## Tasks
 - [ ] Move configured offline time to deviceConfig
 - [ ] Invoke deletion of database instead of clearning in out of sync handling in EventBus
 - [ ] Implement dialog with user information

## Context
note: out of sync occurs after 45 days of not synchronising with the server
We already handle multiple windows when deleting the database.

**Comment by johnbotris** [comment]
#### Test notes
You will need to test this with a locally built client because the out of sync time is hardcoded to 45 days (`ENTITY_EVENT_BATCH_EXPIRE_MS`)

- [ ] Login with an account with an out of sync offline database. A popup will show informing the user that their local data will be deleted and they will be logged out.
- [ ] upon clicking the button, they are logged out and their local database is deleted
- [ ] upon clicking the button, any other windows logged in to the same user will also be logged out
- [ ] any open windows of a different user will be unaffected
- [ ] logging in to an account that is not out of sync will not trigger any of this

**Comment by johnbotris** [comment]
I was able to get the "Trying to delete database that is opened * times" message when handling out of sync after playing around with the app for a while. Not sure which sequence of events lead to this

**Comment by ganthern** [comment]
logged in with an account that had an offline db from previously, immediately got an out of sync (since it was set to 30s) and this error:

```
Feedback v3.96.4 - Error - PREMIUM - linux
Client: linux
Type: PREMIUM
Tutanota version: 3.96.4
Timestamp (UTC): Tue, 17 May 2022 11:55:46 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop-test/3.96.4 Chrome/100.0.4896.143 Electron/18.2.3 Safari/537.36
Error
Error message: Did not update row
Stacktrace:
Error: Did not update row
at Nh.setLowerRange (/tmp/.mount_tutano1EYc5g/resources/app.asar/desktop/DesktopMain.js:13:900495)
at Df.setLowerRange (/tmp/.mount_tutano1EYc5g/resources/app.asar/desktop/DesktopMain.js:13:881226)
at /tmp/.mount_tutano1EYc5g/resources/app.asar/desktop/DesktopMain.js:13:122295
at ai._invokeMethod (/tmp/.mount_tutano1EYc5g/resources/app.asar/desktop/DesktopMain.js:13:121979)
at /tmp/.mount_tutano1EYc5g/resources/app.asar/desktop/DesktopMain.js:13:116435
at node:electron/js2c/browser_init:189:579
at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:11093)
at EventEmitter.emit (node:events:390:28)
```
