### ISSUE TITLE
Ensure that all contacts are available in offline storage

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#4134]
As a user, I want to have access to my contacts when i am offline.

**Acceptance criteria**
- Contacts are always completely downloaded and stored locally
- Contacts are available when the device is not online.
- Contacts are updated and new contacts are downloaded whenever connected to the server

**Tasks**
- [ ] Decide were to initially load all contacts in case offline is enabled.
- [ ] Load all contacts from a single place and not load them concurrently (search index, login)

**Notes**
Users which already have a search index but have not enabled offline storage might not have all contacts offline available. We need to trigger loadAll for contacts explicitly.

**Test notes**
- [ ] log in to desktop client (for 2+nth time), go offline, switch to contact view and observe that contacts are not available
- [ ] enable offline storage log in again, go offline, switch to contact view and observe that contacts are available
- [ ] log in to desktop client offline, switch to contact view and observe that contacts are available
- [ ] log in to desktop client online, add new contacts from another client, go offline in desktop client and switch to contacts view, observe that new contacts are available
