### ISSUE TITLE
Offline mode for ios application

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#4135]
As a user, I want to be able to access my data from my phone when I have no/unstable internet connection

**Acceptance criteria**
- Offline data is stored encrypted on the device
- Same offline login and caching behavior as the desktop client and android

**Task**
 - [x] Try to use prebuild sqlcipher for ios and see if it conflicts with our openssl
 - [x] Build sqlcipher for iOS and make sure that it works with our existing openssl
 - [x] implement the generated sqlfacade for the ios app
 - [x] Make sure we can transport big data (mail bodies) using the current native interface 
 - [x] the UI performance is acceptable

### Test Notes
* [ ] Upgrade from version without offline works and maintains saved credentials (can still log in)
* [ ] Logging in without saving the credentials works
* [ ] Logging in with saving the credentials works 
* [ ] can view mails 
* [ ] can view calendar
* [ ] can view contacts
* [ ] previously viewed items can be viewed after logging in offline
* [ ] can sign up
* [ ] can send mail to internal
* [ ] can receive mail from internal
* [ ] attachments send/receive
* [ ] logging in with saving credentials, then deleting credentials and logging in again with saving works
* [ ] logging in from the form with saving the credentials while the account is already in the saved credentials works
