### ISSUE TITLE
Enable offline mode by default

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#4205]
As there  are no major issues when enabling offline caching we can enable it by default for all users of the desktop application when there are stored credentials.

**Acceptance criteria**
* Offline mode is turned on by default
* Setting for turning offline mode on/off is removed
* Offline db is created when users selects "store credentials"
* Offline db is created for accounts that already have stored credentials

**Tasks**
- [ ] Remove ui from Settings > Desktop to activate/deactivate offline storage
- [ ] Delete config value from desktop settings and adapt existing code

**Comment by johnbotris** [comment]
# Testing
- [ ] previously stored accounts with offline mode enabled are unaffected
- [ ] previously stored accounts with offline mode disabled now have offline mode enabled
- [ ] newly stored accounts always have offline mode enabled
- [ ] the offline mode toggle does not show up in desktop settings
