### ISSUE TITLE
Move SQL code from platform-specific code into the web part (use generated facade)

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#4293]
As part of https://github.com/tutao/tutanota/issues/4030 we need to generated the facade for accessing the SQL database. The SQL logic to store and read from offline db should be within the web part of the application so that we have one implementation for all platforms.

**Tasks**
- [x] Decide which operation are necessary.
- [x] Define facade in LICC and generate facades
- [x] Adapt desktop client implementation.
