### ISSUE TITLE
Build OpenSSL for android architectures

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#4294]
As part of #4030 we need to generate the openssl/sqlite-sqlcipher libs for the android architectures.

**Tasks**
- [x] Define which architectures we want to build app for arm7 (armeabi-v7a) and arm8 (arm64-v8a)
- [x] Build OpenSSL for architectures
- [x] Build sqlite-sqlcipher as part of the Android build
- [x] Integrate native lib into deployed apk

**Implementation hint**
https://github.com/sqlcipher/android-database-sqlcipher
