### ISSUE TITLE
Implement native android part

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#4295]
As part of #4030 we need to adapt the native android part to support offline access.

**Tasks**
- [x] Implement offline db facade
- [x] Disable offline access for architectures that don't have a sql-cipher lib.
- [x] Check performance of big data transport (web <-> native)
