### ISSUE TITLE
Create design document for offline mode including threat model for unauthorized db access.

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#4501]
The design document and threat model was created in the confluence wiki (Offline storage / Offline mode) and should be revisited now that the actual implementation is almost done.

### Acceptance Criteria:
* the final design is laid out on a page in the documentation project
* the threat model is also on that page
* both of these are in sync with the implementation

### Tasks
* [x] review documentation of the offline implementation in comments and on the doc project
* [x] fix any differences with the implementation
* [x] explain what we're trying to protect from with the encrypted offline db (on the doc page)
