### ISSUE TITLE
Absolute threshold of users participating in Usage Tests

### ISSUE THREAD

**Issue by nowhub** [tutao/tutanota#4557]
As an operator, I want to be able to optionally set the max. number of users that participate in a test.

### Acceptance criteria
* New text input in Usage Test configuration that lets operators specify a threshold of users participating (absolute number)
* This setting is in addition to percentageParticipating and should work in parallel
* When the threshold is reached, new users are not assigned anymore (i.e., handle it as if the test were paused), but already participating users can still send pings

### Tasks
- [x] Modify UsageTestConfig model, add threshold value
- [ ] Modify UsageTestAssignmentService so that it does not assign variants to new clients after reaching the threshold
- [ ] Add a new text input for configuration of threshold in admin client
- [ ] Add tests to ensure that threshold and percentageParticipating work without interfering with each other

### Notes
* Future story: make this setting changeable after the test has been started

**Comment by nowhub** [comment]
After discussion we decided not to implement this functionality since we are not sure if it's actually needed or what the best implementation would be. For now, setting the percentage, observing the results, and pausing as needed works.
