### ISSUE TITLE
Expand counts in results to multiple columns

### ISSUE THREAD

**Issue by nowhub** [tutao/tutanota#4558]
As an admin, I want each count of a count metric in a separate column in usage test results.
This makes it easier to work with the data later, since spreadsheet software expects single numeric values in each cell.

### Acceptance criteria
* In the results table and the exported CSV file, count cells are *exploded* to multiple columns

### Tasks
- [x] Make sure that usage test metric types know how many columns they will produce in advance
- [x] Generate multiple columns per metric (e.g., for enum) 

### Notes
Right now, counts are exported as follows in a single cell:

```
Paypal: 3\nCredit Card: 4\nInvoice: 1
```

### Test notes
- [x] Create a test with both Likert and Enum metrics, compute results, check that a separate column exists for each value
- [x] Check out `usage-tests-explode-smoke` (tutanota-3) locally
  - [x] Configure the mail viewer test: name 'test', 3 variants, 100% unlimited participations, one stage, enum-type metric 'paymentMethod' with values 'paypal', 'bankTransfer', 'invoice', and metric 'likert'.
  - [x] Log in, click the "more" button in the mail viewer, click the new button, compute results, confirm that pings are being counted correctly (variant 1: paypal, likert==1; variant 2: credit, likert==2; variant 3: bankTransfer, likert==3), log out
  - [x] Do the above a few times
