### ISSUE TITLE
Opt-in for usage test

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#4589]
As a user I want to be able to opt-in for usage tests after the first login after introducing usage tests into the client. I want to be able to change my decision in the settings.

As a customer admin I want to be able to deactivate usage test participation for my whole account so users don't have to make a decision and always not participate in usage testing.

## Acceptance criteria
* There should be a "news" entry in drawer menu which indicates that users can opt-in. The entry should be visible until the user made the decision.
* The opt-in dialog shall explain what the usage tests are needed for to convince the user to opt-in. The dialog shall require an explicit action by the user (accept, decline, decide later). 
* In the settings there is the option to change the usage test decision for the user between accept, decline. If no decision was taken "Not decided" is shown Settings > Login > Usage data/Nutzungsdaten.
* The users decision is stored on the server and is valid for all devices.
* When the first user on a device accepts the opt-in we store the usage test information, like variant, locally.
* A user who does not opt-in does not participate and gets the default variant shown.
* We keep the locally stored data even if all users on the device opt out later.
* Settings to to disable usage test opt-in for all users is available in "Settings > Glob settings > Usage data/Nutzungsdaten"
* At login if either the user did not opt-in or the customer admin opted out for the whole account, then we disable usage tests for this session.

## Task

* [x] add extra button with dot to drawer menu 
* [x] create modal opt-in dialog
* [x] Add settings values. Store user settings on UserSettingsGroupRoot instance, store customer settings on CustomerProperties

**Comment by nowhub** [comment]
I think this needs some additional refinement.

- What does the "news" entry look like? Is this just an additional icon in the left sidebar that directly opens the opt-in dialog? 
![image](https://user-images.githubusercontent.com/97233129/174618177-1f896c7e-5c09-473c-a79f-7a369171fbec.png)
-> use ios-bulb-outline or md-bulb from ionicons icon set. 
- Where in the settings should the usage test opt-in decision be?
-> Settings > Login > Usage data for user settings
- On what model is the user's decision stored (Customer, CustomerInfo)?
-> UserSettingsGroupRoot
- Where in the admin settings should the opt-out for all users of that account be?
-> Settings > Global settings > Usage data for customer, model: CustomerProperties

**Comment by nowhub** [comment]
### Branches for smoke testing: 
* tutadb, next: `usage-tests-opt-in`
* tutanota-3: `usage-tests-opt-in-enabled`
### Tests
Unauthenticated test: `signup.free`
Authenticated test: `test` (MailViewer)

**Comment by nowhub** [comment]
### Test notes

Branch tutanota-3: `usage-tests-opt-in-enabled`
Others: `usage-tests-opt-in`

Setup admin client:
Create test `test` with one stage, 3 variants, unlimited participations.
Only metric 0th stage: `paymentMethod`, type enum, values: `bankTransfer`, `paypal`, `credit`

- [ ] Confirm that a new user is shown a (1) near the hamburger menu and a light bulb in the left navigation bar
- [ ] Confirm that the opt-in dialog opens on click on the light bulb
- [ ] Confirm that "decide later" closes the dialog without removing the light bulb or hamburger indicator
- [ ] Confirm that "Activate" shows the corresponding dialog message
- [ ] Navigate to login settings, Click more info on opt-in setting, confirm that "Deactivate" shows the corresponding message and instantly changes the setting's dropdown label, too
- [ ] Navigate to global settings, activate "opt-out for all users" setting (first option)
- [ ] Create a sub-user, log in, confirm that opt-in dialog is not indicated by hamburger (1) or light bulb
- [ ] Change back global setting on admin account, set opt-in for user, re-log, confirm that pings are sent (MailViewer more menu, Variant X button)
- [ ] Opt out, do not re-log, attempt to send more pings, confirm that none are being recorded in admin client
- [ ] Clear local storage
- [ ] Create sign.up free test with 3 stages, no metrics
- [ ] Start new registration process, confirm that pings are being sent and that no `_testDeviceId` is being set in local storage
- [ ] Cancel registration, log in with existing user, opt in, confirm that pings for MailViewer test are being sent and that `_testDeviceId` is now set in local storage

#### Regressions

- [ ] Make sure that the app's header (with Tutanota logo/hamburger on mobile) is not broken for, e.g., the whitelabel feature
