### ISSUE TITLE
Email domains usage test

### ISSUE THREAD

**Issue by nowhub** [tutao/tutanota#4597]
As an operator, I want to test different methods for finding available email addresses (on possibly different domains) during signup. 

### Acceptance Criteria
- Create a new usage test that allows A/B testing the following GUI variants of the email address input
  - Variant 1: Leave as is
  - Variant 2: Extend the supporting text: "[...] Try another domain from the dropdown"
  - Variant 3: Have the user enter the email's local part (before @), check availability on all domains, display availability state for the email address for each possible domain as a suggestion list. Keep the current custom domain order for displaying the availability. The existing custom domain dropdown field shows the selected domain. 
  - Variant 4: Have the user enter the email's local part (before @), check availability on all domains, display the available complete email addresses in a suggestion list. The existing custom domain dropdown field shows the selected domain.

- Stages
  - Stage 1: Enter email form page
  - Stage 2: Repeatable: When entering an unavailable email (max: 10)
  - Stage 3: The first time an email is available (metric: time diff to stage 1)
- Adapt MailAddressAvailabilityService to receive a list of email addresses and return the list of email addresses with their availabilities
  - `[{"emailAddress": "abc@tutanota.com", "available": "0"}, {"emailAddress": "abc@tutanota.de", "available": "1"}, ...]`

### Implementation Details
- Checking the availability in variant 3 might require consideration of the server rate limit for the email address service. Another option is implementing a new service that checks availability on all tuta domains at the same time

### Notes
Depends on #4596. We want to measure first if it is a problem that users cannot find an email address to signup for an account.

### Tasks
- [x] Adapt the MailAddressAvailabilityService to take a list of email addresses and return whether it is available for each
- [x] Change the debounce logic and the email address availability label to account for multiple addresses being checked
- [x] Implement the new variants
  - [x] Adapt the suggestion list (contacts) to work with email addresses and their availability statuses
- [x] Take stages from the signup.unavailableemails test

**Comment by nowhub** [comment]
### Test notes
- Create test `signup.emaildomains` from the presets dropdown in the admin client
- Start signup process for each variant (1-4). Set the variant via `tutao.locator.usageTestController.getTest("signup.emaildomains").variant=X` in the console
- Confirm that variant 1 shows the current implementation of the email address selection input and that a ping (stage 1) is sent each time an email is unavailable (but not if it is invalid). A ping should also be sent as soon as an entered email is available.
- Confirm that variant 2 shows the current implementation of the email address selection input (but a different error msg if the email address is unavailable, telling the user to use the dropdown) and that a ping (stage 1) is sent each time an email is unavailable (but not if it is invalid). A ping should also be sent as soon as an entered email is available.
- Confirm that variant 3 shows the new email address selection input with suggestions. Confirm that it works as intended and that 
  - it only shows suggestions if at least the username is available on at least one domain
  - it only shows suggestions if the input is focused
  - it only lets the user select available email addresses
  - the old domain dropdown still works
- Also confirm that a ping is sent if the username is available on 0 domains (stage 1) and that a ping for stage 2 is sent if the username is available on at least 1 domain
- Confirm that everything from variant 3 applies to variant 4, but the suggestions dropdown only shows domains where the username is available

**Comment by nowhub** [comment]
### Release notes
- [ ] Create the usage test `signup.emaildomains` using the dropdown in the admin client
- [ ] Set the rate limit for `/rest/system/multiplemailaddressavailabilityservice` to 3 per 10s
