### ISSUE TITLE
Password strength usage test

### ISSUE THREAD

**Issue by nowhub** [tutao/tutanota#4599]
As an operator, I want to find out whether users experience difficulties choosing a secure enough password during signup. 

### Acceptance Criteria
- Create a usage test that varies the password strength requirement
  - Variant 1: Leave as is (100%)
  - Variant 2: Password is ok at 80%
  - Variant 3: Password is ok at 60% 
- The following pings shall be sent:
  - Stage 1: When entering the password form page
  - Stage 2: Repeatable: When clicking next when the password is not secure enough
  - Stage 3: When clicking next and the password is secure enough

### Tasks
- [x] Implement 3 variants (+ not assigned) with different password strength requirements
- [x] Send ping at each stage

**Comment by nowhub** [comment]
### Test notes
- [ ] Create the `signup.passwordstrength` usage test, 3 variants, 100%, one participation
  - [ ] Stage 0: default
  - [ ] Stage 1: minPings:0, maxPings: 10
  - [ ] Stage 2: default
