### ISSUE TITLE
Paypal payment steps usage test

### ISSUE THREAD

**Issue by nowhub** [tutao/tutanota#4600]
As an operator, I want to find out whether users experience issues when paying for a subscription using Paypal. 

### Acceptance Criteria
- Create a usage test that measures the steps of Paypal payments
  - Starts at selection of Paypal as payment method
  - Paypal payment button click
  - Websocket notification received
  - Validated invoice data (click on next)

### Tasks
- [x] Adapt stages for invoice data validation
- [x] Check where websocket notification about connected Paypal account is received
- [x] Implement stages
- [x] Test with different orders, going back, (upgrades outside the signup), etc.
- [x] Check payment switch dialog
