### ISSUE TITLE
Remove recovery code dialog from signup

### ISSUE THREAD

**Issue by nowhub** [tutao/tutanota#4609]
As a user, I don't want to be bothered with the recovery code on signup.

### Acceptance criteria
* The dialog is removed from the final page of the signup wizard.
  * This should coincide with the release of #4604.
* A congratulation text is displayed ~~below~~ above the coffee drinking image instead.
  * For free subs only (discussed with arm) 
* Recovery code is still generated on sign up.

### Tasks

- [x] Consult hab about congratulation text
- [x] Remove recovery code from the last sign up page

**Comment by dipjul** [comment]
![Screenshot_20220927-225537_Chrome~3](https://user-images.githubusercontent.com/20329508/192595095-9e982ab5-af28-4af3-9daf-dad0631956a3.jpg)
Is the link to Lost account access need to be removed?

**Comment by nowhub** [comment]
Hi @dipjul, we don't plan to remove that link.

**Comment by dipjul** [comment]
Can you share the details on how to reproduce it or where it's appearing?

**Comment by nowhub** [comment]
The recovery code appears as the last step of the signup process.

**Comment by dipjul** [comment]
Locally unable to access the signup form, stuck in loading screen.
![image](https://user-images.githubusercontent.com/20329508/192827101-e454ef94-deae-4c1b-9fd5-549eb5a11d6e.png)

**Comment by nowhub** [comment]
### Test notes
- [ ] Register a free account, confirm that the recovery code is not shown and that the "congratulation" message is shown above the vis image
- [ ] Register a paid account, confirm that the recovery code is not shown in the "buy" (buy button) step
- [ ] Make sure that neither the recovery code nor the congrats message is shown on upgrade from the client
- [ ] Make sure that neither the recovery code nor the congrats message is shown on downgrade (to free) from the client
