### ISSUE TITLE
Improve button state display

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#4641]
As a user preferring to use keyboard I want to see what UI element I selected with my keyboard.

As a user preferring to use mouse/touch screen I don't want to be confused by seeing the focused state on the buttons I just pressed.

### AC:

* The currently focused UI element (the one getting activated when pressing enter) is highlighted in a visible focused state after * using tab / cursor keyboard navigation
* That focused state is not shown on any button after using the mouse or touch screen to press a button.
*  This behavior can be repeated indefinitely

### Notes:
While writing a new email:

click on the expander to enter cc/bcc recipients and press again to collapse it.
the button still has a grey background (i think it is the focused state). 
This might be confusing as we use the darker grey as "pressed" state.

![focused-state-mail-editor](https://user-images.githubusercontent.com/8296817/194262087-64ba0141-660a-492e-9f10-e76f6e2240f2.png)

Proposed solutions:
* We could maintain the accessibility advantages of showing the focused state and still get a cleaner look for this by only showing the focused state when necessary (ie after tabbing)

## Tasks
 - [x] Add detection for tab navigation in RootHandler
 - [x] Change CSS to only show the active state when we are using keyboard navigation
 - [x] Toggle keyboard navigation CSS based on mouse/keyboard events

## Test notes
 - [ ] Check that when using tab navigation focus ring, hover, focus and active (pressed) states are all displayed
 - [ ] Check that when using mouse focus ring is not displayed but hover and active work correctly
 - [ ] Check that when using touchscreen (ideally both iOS and Android) focus ring and hover are not displayed (hover would stuck after press) but active (pressed) state is still displayed
 - [ ] Check that switching between at least keyboard and mouse and back works correctly
