### ISSUE TITLE
Synchronize feature list with mail client

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#4670]
As  a user of the web application i want to see the same feature list as on the website so that i am not confused about different features.

### Acceptance Criteria

- Feature list from website is shown on signup/upgrade wizards
      - desktop
      - web app
      - android
- it's using the same collapsible design as the website feature list
- When changing feature list on website it should synchronize without client release
- show an empty feature list if website is unreachable/json can't be found

### Tasks
* [x] synchronize feature list translation keys on the client  and website
* [x] implement collapsible feature list for the clients
* [x] fetch the json data from the website

## Test Notes
* [ ] sync feature list (during signup __and__ change subscription while logged in)
  * [ ] use either desktop client or web client without loggin in
  * [ ] tooltips are only shown while hovering over a tooltip icon
  * [ ] clicking a tooltip icon will show a tooltip until some other part of the screen is clicked
  * [ ] also test (only) the previous note on mobile with touch
  * [ ] in multi-column layout (should be default in web and desktop client)
    * [ ] without pressing "Show all features"
      * [ ] in tab "Private"
        * [ ] make sure that the client shows the same feature lists for Free, Premium and Teams like https://tutanota.com/pricing/ does
        * [ ] make sure that the client shows the same tooltips for the features for Free, Premium and Teams like https://tutanota.com/pricing/ does
      * [ ] in tab "Business"
        * [ ] make sure that the client shows the same feature lists for Premium, Teams and Pro like https://tutanota.com/pricing/ does
        * [ ] make sure that the client shows the same tooltips for the features for Premium, Teams and Pro like https://tutanota.com/pricing/ does
    * [ ] after pressing "Show all features"
      * [ ] in tab "Private"
        * [ ] make sure that the client shows the same feature lists for Free, Premium and Teams like https://tutanota.com/pricing/ does
        * [ ] make sure that the client shows the same tooltips for the features for Free, Premium and Teams like https://tutanota.com/pricing/ does
      * [ ] in tab "Business"
        * [ ] make sure that the client shows the same feature lists for Premium, Teams and Pro like https://tutanota.com/pricing/ does
        * [ ] make sure that the client shows the same tooltips for the features for Premium, Teams and Pro like https://tutanota.com/pricing/ does 
  * [ ] in single-column layout (either resize window size or use mobile client)
    * [ ] Buy boxes are shown in Premium, Business, Free order (for "Private")
    * [ ] Buy boxes are shown in Premium, Teams, Pro (for "Business")
    * [ ] clicking "Show all features" on single buy box will only expand the specific feature list
  
### Regressions
* [ ] prices in the upgrade dialog shown in the client agree with what the website shows for the same plan
  * [ ] Free / Premium / Teams
  * [ ] Premium / Teams / Pro (Business) 
  * [ ] switching yearly/monthly updates prices accordingly
* [ ] prices are localized properly -> en-US Renders the currency symbol in front of the numbers
* [ ] the prices for already bought features shown on the subscription settings page are as expected
* [ ] buying and redeeming gift cards works as expected
