### ISSUE TITLE
Recovery code news item

### ISSUE THREAD

**Issue by nowhub** [tutao/tutanota#4671]
As an operator, I want to broadcast a news about the recovery code.

### Acceptance criteria
* Recovery code has the option to "show" the recovery code
* "Show" opens dialog to request the password to access recovery code
* Recovery code is shown inside news item after successful authentication the user has then the option to confirm the news by clicking "Confirm"
* The recovery code is only shown to global admins.
* Recovery code is not shown anymore if the news section is closed (requires password again)
* Recovery code "confirm" button is only shown while the code is shown in the item
* "Done" button dismisses the news item after showing a dialog that the user has to confirm
* Make sure recovery code is created if the customer does not have one

### Todos
- [x] Create UI for the news item
- [x] Make recovery code show up only after clicking "show" and entering one's password 
- [x] Create recovery code if customer does not have one

**Comment by nowhub** [comment]
### Test notes
- [ ] Make sure that `recoveryCodeDisplay_action` has been added to Phrase
