### ISSUE TITLE
Repeatable stages for usage tests

### ISSUE THREAD

**Issue by nowhub** [tutao/tutanota#4698]
As an operator, I want to be able to configure certain stages in usage tests to be configurable.

### Acceptance Criteria
- Usage test stages have two new settings `minPings`, `maxPings`, which allow setting the minimum and maximum number of pings a client may submit
- The default and current setting is `minPings = maxPings = 1`
- `0 <= minPings <= currentPings <= maxPings` always holds
- Pings for a stage may now also be submitted if all unsubmitted stages prior to it are optional (`minPings=0`)
- Repeatable stages' metrics are aggregated as usual

### Todos
- [x] Change UsageTestStage model to allow for new settings
- [x] Add minPings, maxPings options to stage creation/edit dialog
- [x] Adapt stage validation on ping submit 
  - [x] Client-side
  - [x] Server-side 
- [x] Adapt tests
  - [x] Client-side
  - [x] Server-side

**Comment by nowhub** [comment]
### Test notes


### Regression testing
- [ ] Make sure that signup.free and signup.paid still work as intended (p#28)
