### ISSUE TITLE
Tidy up mail instance (move attributes to MailDetails)

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#4719]
See server issue #1241

### Tasks
Adapt all usages of
- [x] body
- [x] header
- [x] recipients

### Test notes
Test with legacy mail instances:
- [ ] Mail indexing / search
- [ ] Inbox rules processing for a rule with a toRecipient
- [ ] Inbox rules processing for a rule with a ccRecipient
- [ ] Inbox rules processing for a rule with a bccRecipient
- [ ] Mail List: Mail with multiple recipients in each of the recipient fields (to/cc/bcc)
- [ ] Mail Viewer: Mail with multiple recipients in each of the recipient fields (to/cc/bcc).
- [ ] Mail Viewer: Reply to mail with multiple recipients in each of the recipient fields (to/cc/bcc).
- [ ] Export new and legacy mail including headers and diff.
- [ ] Offline

Test with new mail instances:
- [ ] Mail indexing / search
- [ ] Inbox rules processing for a rule with a toRecipient
- [ ] Inbox rules processing for a rule with a ccRecipient
- [ ] Inbox rules processing for a rule with a bccRecipient
- [ ] Mail List: Mail with multiple recipients in each of the recipient fields (to/cc/bcc)
- [ ] Mail Viewer: Mail with multiple recipients in each of the recipient fields (to/cc/bcc).
- [ ] Mail Viewer: Reply to mail with multiple recipients in each of the recipient fields (to/cc/bcc).
- [ ] Export new and legacy mail including headers and diff.
- [ ] Offline
