### ISSUE TITLE
Advanced repeat rule: Reschedule occurrence of a repeating event

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#4860]
As a user i want to be able to reschedule specific occurrences of a repeating calendar event so I can keep the original repeat rule while being able to react to scheduling conflicts.

### Acceptance criteria
* When an occurrence of a repeating event is rescheduled via dragging or edited in the editor, the user gets asked when saving or dropping the dragged event:
  * edit only the occurrence that was clicked → do that
  *   edit everything → add offset that was edited to the original event. don't do a separate rescheduled occurrence (basically what we're doing now)
* Rescheduled occurences are visible in the event edit dialog
* Received calendar invites with rescheduled occurrences are recognized
* Sending an invite with rescheduled occurrences correctly sends rescheduled occurrences so that it is recognized by other calendar software
* When an event with rescheduled occurrences is deleted completely, it deletes all occurrences - orginal, repeats and reschedules
  * this does not include the case where we delete a single occurrence - just add the exclusion then.
  * if a single rescheduled occurrence is deleted , we add an exception/exclusion for the orginal start time of the occurrence
* ~~Reminders on all platforms are fired in accordance with the rescheduled event~~ -> in next step #5358 
* When editing the occurence of a repeating event we display the datetime of that occurence in the edit dialog
* When changing the calendar of the events all of the linked events are moved to that calendar
  * Tentative: Guests are shared between all occurrences, also rescheduled ones
        Override this if implementation strongly suggests otherwise because we want to change it eventually anyway

### Notes
https://github.com/tutao/tutanota/issues/4872

### Release notes
 * schema upgrade must be run before any clients supporting writing the new index format are released.

### Tasks
* [x] model changes
    * [x] tutadb
    * [x] tutanota-next
    * [x] client
    * [x] backwards migration
    * [x] offline database must be consistent with the server after the update or be emptied
* [x] export/import
    * [x] Exports properly
    * [x] Imports another Tutanota Calendar
    * [x] imports calendars with rescheduled events from other calendar apps
* [x] documentation
* [x] translations
* [x] invites 
    * [x] sends notifications for adding altered instances
    * [x] sends notifications for updating altered instances
    * [x] sends notifications for removing altered instances
    * [x] sends notifications for changing the whole series
    * [x] canceling events works correctly for rescheduled events (for single and the whole series)
    * [x] Process incoming updates correctly and update rescheduled occurrences
* [x] calendar event editor
    * [x] change it so it always displays the selected instance when opened
    * [x] add the display section for rescheduled instances
    * [x] ask user about scope of the changes before opening the editor
        * [x] Editing a rescheduled event should still ask 
       * [x] if all events -> just edit as normal
      * [x] if only this occurrence -> add a new rescheduled occurrence after the edit operation
    * [x] guests should continue to apply to all instances
* [x] Rescheduled events are cleaned up properly
* [x] drag'n'drop for event should ask what to do on drop
* [x] test old clients in the presence of events with the same UID
* [ ] ~~Invalidate stored alarms on all platforms~~

## Test notes

**drag&drop**
 * [ ] When dragging and dropping one (non-rescheduled) occurrence of a repeating event there is a dropdown which suggest to change only one or all of them
   * [ ] it is not shown for single events that do not repeat
   * [ ] it is not shown for already rescheduled events (those just get rescheduled after drop)

**deleting**
* [ ] When clicking delete on any event of a series that has more than one visible (non-excluded) instance, the popup asks if only that instance should be deleted. the operation is applied according to the user's choice.
* [ ] if the series has only one visible instance, it asks for confirmation and deletes the whole series if approved

**editing**
 * [ ] when clicking edit on the popup, there is a dropdown to select single edit or multiple edit if the event is part of a series (even if it is the last remaining instance)
 * [ ] if editing a single instance in any shared or private calendar
   * it's not possible to change the calendar
   * it's not possible to change the attendees
* [ ] changing the repeat rule on the whole series deletes all exclusions & altered instances
* [ ] changing the start time on the whole series deletes all exclusions & altered instances
* [ ] changing the end time on the whole series adjusts the length of all altered instances as well
* [ ] other edits to the whole series are applied to all altered instances as well

**invitations, outgoing** 
for all of these, the appropriate notifications are sent:
  * [ ] cancellation for removed attendees and cancelled instances (deletion of a single non-altered instance should be an update notification for the whole series)
  * [ ] updates are sent to kept attendees after editing an event instance
  * [ ] invitations are sent to any attendees when creating new altered instances.

**invitations, incoming**
it's possible to accept/reject invites from outlook, proton and google.
* [ ] single, non-repeating event
* [ ] repeating event
* [ ] repeating event with exclusions
* [ ] repeating event where an altered instance exists and we get invited afterwards to all instances
* [ ] invitation to a single altered instance without being invited to the original event series.
* [ ] cancellations for accepted invites are correctly processed and the events are removed from the calendar.
* [ ] response mail is correctly sent to the organizer

**import/export**
* [ ] the tutanota import/export roundtrip works for events with altered instances
* [ ] we can import events with altered instances from other calendar apps
* [ ] we can export calendars with altered instances from tutanota and import them into other calendar apps

## Regression Test
* [ ] navigation between columns in mobile and desktop view works
* [ ] after editing an event's repeat rule, alarms are fired (or not fired) according to the new rule, like after adding an end condition or increasing the interval

**Comment by jctratt** [comment]
I would also like to have a "This and following events" option when modifying an event. Justification: A client's schedule may change and require moving recurring appointments to another day/time; however, keeping the past events scheduled is just as important.

**Comment by vitoreiji** [comment]
* Google. NOTE: Tutanota ignores any updates if the sender is not the organizer
  * [X] single, non-repeating event
  * [X] repeating event
  * [X] repeating event with exclusions: exclusion not considered
  * [X] repeating event where an altered instance exists and we get invited afterwards to all instances: main one does not exclude rescheduled until we accept altered one
  * [X] invitation to a single altered instance without being invited to the original event series
  * [ ] cancellations for accepted invites are correctly processed and the events are removed from the calendar.
  * [X] response mail is correctly sent to the organizer
* Outlook. NOTE: responses not processed by Outlook
  * [X] single, non-repeating event
  * [X] repeating event
  * [X] repeating event with exclusions
  * [X] repeating event where an altered instance exists and we get invited afterwards to all instances
  * [X] invitation to a single altered instance without being invited to the original event series.
  * [ ] cancellations for accepted invites are correctly processed and the events are removed from the calendar.
  * [X] response mail is correctly sent to the organizer
  * [ ] cancelling one occurrence of an event after accepting the whole series. Not processed by Tutanota
* Proton
  * [X] single, non-repeating event
  * [X] repeating event. NOTE: changing from YES to MAYBE is not reflected on Proton
  * [X] repeating event with exclusions. NOTE: Proton removes all alterations from event
  * [X] repeating event where an altered instance exists and we get invited afterwards to all instances. NOTE: same as above
  * [X] invitation to a single altered instance without being invited to the original event series. NOTE: same as above
  * [X] cancellations for accepted invites are correctly processed and the events are removed from the calendar.
  * [X] response mail is correctly sent to the organizer

**Comment by ganthern** [comment]
### outlooks "cancelling one occurrence of an event after accepting the whole series. Not processed by Tutanota"
this is the result of outlook not sending a new version of the event series with an added exclusion, but a CANCEL request
for a RECURRENCE-ID we never received (that never existed). we could handle this case easily by just adding the exclusion
and special-casing this.

### outlooks "cancellations for accepted invites are correctly processed and the events are removed from the calendar."
* cancelling non-repeating events
* cancelling whole series 
* cancelling an altered event
all work fine, more context needed

### googles "cancellations for accepted invites are correctly processed and the events are removed from the calendar."

adding an exclusion on google has the same problem as outlook: we get a CANCEL request for the RECURRENCE-ID. we can fix it in the same way. 

in combination with the fact that google does not like to send the EXDATE property, this also means that we will lose any exclusions added in this way when the google organizer sends an update to the whole event series, however.

other cancel operations seem to work fine, though

**Comment by ganthern** [comment]
I upgraded the CANCEL problem to a bug, I'm pretty sure it already doesn't work with the prod version.

https://github.com/tutao/tutanota/issues/5752

**Comment by vitoreiji** [comment]
Retested, cancelling from outlook, it is fine. Should we just accept the other two and finish this once and for all?
