### ISSUE TITLE
Create subfolders of system folders

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#4888]
As a user i want to be able to create folders in the pre-created system folders so I have maximum flexibility for the organization of my mailbox
## AC
* Parent folder including system folders can be selected from the create dialog
* If no parent folder is selected the mailbox name is selected and the folder will be created as a root folder
* Able to expand and collapse subfolders of system folders

## Tasks
- [ ] change folder creation so you can select name and parent in the dialog

## Test Notes
- [ ] Cannot delete system folders
- [ ] can delete custom subfolders of system folders
- [ ] moving folder to spam triggers spam dialog or popup
- [ ] moving folder to trash triggers trash dialog

**Comment by wrdhub** [comment]
Note: Don't merge this PR, these changes are rolled into the delete folder structure PR.
