### ISSUE TITLE
Long attachment file name not visible

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#4890]
In an email the full attachment name can not be made visible. Long attachment names are cut off and when clicking on the attachment we just offer to open/show the attachment, so there is no possibility to see the full name. On desktop however we have the tooltip text to show the full attachment name.

How to reproduce:
Open an email with a long attachment name on mobile.
-> It is not possible to see the full name.

## Notes
One way to solve this is to add the full filename as a text to the open/download dropdown and show it every time you click on the attachment.

We don't want to add this to the dropdown itself but rather create an own dialog to show file name and the open/download buttons

## AC
* in the normal bubble state, the file name extension is never truncated away (but the end of the actual name may)
* the bubble still is as short if the name is short (don't grow horizontally if it's not neccessary)
* in the normal bubble state, we don't show the size of the attachment anymore
* when the bubble is tapped, a modal is created instead of the dropdown
* the modal can be closed by tapping anywhere on the screen (or by hitting the esc key)
* the modal displays the full file name, the size and has buttons for the actions:

## Tasks

- [x] reduce font size in the bubble (or don't if it looks weird)
- [x] change the name display in the collapsed bubble to split file names if there is an extension and display the file name in a truncatable way
- [x] make the extension always visible
- [x] implement a modal that can be closed by tapping somewhere else on the screen similar to a dropdown
- [x] use it for the expanded bubble in the mail viewer according to the screenshot
- [x] use this in all clients

![223075572-36f1a1f6-bf5d-4909-91f8-7cd8171540d7](https://user-images.githubusercontent.com/29049728/229091933-aca7055e-7e49-49f4-8ca6-2635ccf51a83.png)

## Test Notes 
this needs to be tested on ios, android, desktop and in firefox and safari, for the mail editor and the mail viewer.
also test it for the contact form request editor.

* [ ] ensure that the bubble displays the file name with extension and size for reasonable file names so the size and extension are always visible and the name may be truncated. if the extension is too long, the size or name may not be visible.
* [ ] ensure that the popup opened by clicking the bubble always displays  the full name (even for unreasonable file name/extension combinations)
* [ ] when using any of the actions, the modal is closed and the action is executed.
* [ ] the popup contains only a "Download" button in the browser and on ios.  It's triggered by clicking and by shortcut "D"
* [ ] it also contains an "Open" button on android and desktop platforms. it's triggered by clicking and by shortcut "O"
* [ ] it contains a "Remove" button in the mail editor. it's triggered by clicking and by shortcut "Delete"
* [ ] the modal can be closed by back button, hardware back button, "Esc" and clicking anywhere but the action buttons contained within.
* [ ] even if the name is very long and the popup is opened very far down, all buttons are accessible and the popup can be closed

### Regressions
* [ ] sending mail with attachments still works.
* [ ] inline images still work.
* [ ] tooltips on the bubble still display the full file name

**Comment by ganthern** [comment]
current / modal / expanding bubble:

![Image](https://user-images.githubusercontent.com/29049728/223075572-36f1a1f6-bf5d-4909-91f8-7cd8171540d7.png)

**Comment by charlag** [comment]
We shouldn't stretch bubbles all the way, it looks odd. I think it would be cool if they would be limited in width still (like now) but would expand into the full thing like you've shown when interacted with.
