### ISSUE TITLE
AggregatedInstance._errors is populated but not handled properly

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#4968]
`InstanceMapper#decryptAndMapToInstance` will write `_errors` field for aggregates. However, we don't generate those fields on the types (e.g. see `MailDetails.ts`) and we don't handle them yet.

### Tasks
- [ ] Adapt code generation to generate `_errors` field for instances of type AggregatedType
- [ ] Remove redundant cast to any from MailViewerViewModel (line `bodyErrors = typeof downcast(mailWrapper.getDetails().body)._errors !== "undefined"`) 
- [ ] Verify if we need to handle _errors on other aggregates.
