### ISSUE TITLE
Conversation view in mail viewer

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#4979]
When selecting an email from a list i want to see emails that are belonging to the conversation so i can identify which emails other persons joined the conversation ordered by time.

## AC

-  MailViewer shows all emails belonging to a conversation as a list.
- Subject of mail list selection is shown at the top (sticky)
- Oldest Emails on top, newest one bottom
- Emails are ordered by time (a reply to an older email in the chain will still show chronologically, not after the email it was in reply to)
- mail list selection (primary email) is indicated in the conversation view (e.g. with different border color) and is the only mail that toolbar actions apply to 
- Primary email shows all actions, other emails have actions hidden behind the more menu
- By default the conversation view is scrolled to the primary email, other emails are shown above and below
- Primary email is shown in full by default
-  Other emails are collapsed (only showing sender, time and attachment icon (if applicable)) with a "show" button that expands that email
-  Quoted reply in mail body is collapsed by default and can be expanded
-  When a part of the conversation is missing (e.g. if the email is fully deleted) we show an indication that a part of the thread is missing. If we can't detect that something is missing with the current model, we don't show anything
-  Mail list view Is unchanged from current
-  Mobile: actions in bottom toolbar apply to the primary mail.
- Mails have their folder indicated by the folder icon
      

## Tasks
 - [x] Finish UI design
 - [x] Rebase on top of the 3.108.0-integration to get MailDetails model changes
 - [x] Implement new design
 - [x] Make sure that the viewer is scrolled to the right position when opening an email
 - [x] Make sure shortcuts work properly
 - [x] Make sure mobile actions work on the correct email
 - [x] Make sure deleted mails work
 - [x] Fix forwarded emails (throws an error because we can't load the conversation)
 - [x] Show mail location indication (icon)
 - [x] Indicate attachments in the conversation with an icon
 - [x] Collapse quotes
 - [x] Change other emails in the conversation to have actions hidden
 - [x] Check lifecycles for other emails in the conversation (e.g. subscription to entityEvents)
 - [x] Update conversation when conversation changes (email added/removed)
 - [x] Add progress for loading the conversation
 - [x] Make sure that primary mail body progress works and does not flash when switching between mails
 - [x] Make sure that rendering delay with mobile menu works
 - [x] Actions for other emails in conversation
 - [x] Collapse Expanded emails
 - [x] Block quote not collapsed for first email in conversation
 - [x] Do not display Unknown Emails

## Test Notes
 - [ ] Switching between mails works correctly
 - [ ] It scrolls to the selected mail when the rest of conversation is loaded
 - [ ] When the conversation fails to load there's a button below the conversation to retry and it works
 - [ ] Check that all shortcuts work correctly: scrolling, read/unread, move, delete
 - [ ] Check that when mails are updated the changes are reflected correctly in the conversation (move, delete, read/unread)
 - [ ] Check that deleting mails completely takes them out of conversation but the rest still works
 - [ ] Check that the mail body is not rendered until we finish scrolling ViewSlider/columns in single column layout
 - [ ] Check that actions on all emails work
 - [ ] Check that toolbar in single column layout works and changes primary/selected mail
 - [ ] Check that multiselect actions in the list still work
 - [ ] Check that the quotes are collapsed in all but the first email in the conversation
 - [ ] Check that quote collapse button works
 - [ ] Check that offline errors when loading attachments/mail body are still handled and it's possible to retry
 - [ ] Check that calendar event banner works
 - [ ] Check that phishing and auth banners work
 - [ ] Check that mail search still works
 - [ ] Check that external mailboxes work
 - [ ] Check that contact form mailboxes work
 - [ ] Check that forwarding emails works
 - [ ] Check that drafts are displayed correctly and have correct actions

**Comment by charlag** [comment]
New questions:
 - unread mail status? Shown or changed in conversation for other emails?

**Comment by charlag** [comment]
Here's how proton searches for blockquotes:

https://github.com/ProtonMail/WebClients/blob/1346a7d3e1a27c544f891ba5130655720a34d22a/applications/mail/src/app/helpers/message/messageBlockquote.ts

**Comment by AaronStiff** [comment]
Just wanted to thank everyone involved in this. The lack of a conversation view has really been the only big fault I could ever find in Tutanota. :)

Cheers
