### ISSUE TITLE
Improve credit card form

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#5055]
As a user I want to be able to enter my credit card data as easily as possible in order to prevent mistakes and to use less time.

**AC**
-  When one field is completely filled and valid, the cursor jumps to the next field.
- There is one field for the expiry date with autocompletion of the slash
- The date input infers what makes sense after every key stroke (ignores letters, will autocomplete "2" → "02 / ", "1/" → "01 / ", "1 " → "01 / " etc. )
- The credit card number field shows a space separator between 4 digit blocks.
- An indication is shown that there is an error in case a field is completely filled but invalid.
- If the credit card number is available there is an indicator if the CVV is 3 or 4 digits long.
- If the credit card number is available use the corresponding label for the CVV.
- If the card holder name is not necessary anymore with 3DS, remove the field.
- The old credit card form is still available for an A/B test, see #5056 

**Card type info**
- Cards starting with 3 = American Express
- Cards starting with 4 = Visa
- Cards starting with 5 = Mastercard
- Cards starting with 6 = Discover
- Card Verification Code – CVC (Mastercard)
- Card Verification Value – CVV (Visa)
- Card Verification Data – CVD (Discover)
- Card Identification Number – CID (Discover/Amex)
- Card Security Code – CSC (Amex)

## Tasks
* [x] make sure the form has a proper model-view separation
* [x] check if we need the credit card holder name for 3DS
* [x] make new files for the changed form
* [x] program and test the component that infers the date completion. use it in the form.
* [x] update the credit card input to insert spaces between the groups
* [x] detect from the credit card number how many digits the cvv has
* [x] change the CVV field so it is only considered filled if it has the appropriate number of digits filled in (3 or 4)
* [x] update error hints to show up as soon as a field is filled but invalid
* [x] add dynamic label for the cvv (see list above)
* [x] make sure the old component is easily dropped in for the A/B test.

### Usage Test
* [ ] in the admin client go to Usage and add a new Usage Test
* [ ] select payment.credit2 from the Pre-configured tests dropdown and keep the rest default
* [ ] click ok and start the test
* [ ] click on signup in the client and select some paid private subscription
* [ ] continue to the payment page
* [ ] paste this into the console: `tutao.locator.usageTestController.tests` and check that there is an entry with the test name "payment.credit2". Make sure to have during testing both variant 1 **AND** 2 (reload the page to get a new variant assigned)
* [ ] in case of variant 1 you should see the old credit card form: number, cardholder name, security code, expiration date
* [ ] in case of variant 2 you should see the new credit card form: credit card number, expiration date, security code
* [ ] (both display a country field)
* [ ] start a timer for the following steps
  * [ ] click any field or the next button should result in "Test 'payment.credit2': Completing stage 1, variant x" being printed out in the console
  * [ ] click on next and check for "Test 'payment.credit2': Completing stage 2, variant x" in the console
  * [ ] type in some wrong credit card number e.g. 4444444444444444
  * [ ] click on next and check for "Test 'payment.credit2': Completing stage 2, variant x" in the console
  * [ ] enter a right credit card number e.g. 4111111111111111
  * [ ] click on next and again check for "Test 'payment.credit2': Completing stage 2, variant x" in the console
  * [ ] **variant 1**: type in some cardholder name and click on next -> "Test 'payment.credit2': Completing stage 2, variant x" in the console
  * [ ] type in a security code with length 1 and click on next -> "Test 'payment.credit2': Completing stage 2, variant x" in the console
  * [ ] type in the security code e.g. 123 and click on next -> "Test 'payment.credit2': Completing stage 2, variant x" in the console
  * [ ] type in a wrong expiration date e.g. 12/6 and click on next -> "Test 'payment.credit2': Completing stage 2, variant x" in the console
  * [ ] type in a right expiration date e.g. 12/26 and click on next -> "Test 'payment.credit2': Completing stage 2, variant x" AND "Test 'payment.credit2': Completing stage 3, variant x"in the console **and stop the timer**
  * [ ] click on "ok" on the popup
  * [ ] on the newly opened tab enter the OTP
  * [ ] you should get redirected to the previous tab where a summary is displayed
  * [ ] go to the admin client, computer results of the test and click the test to see the results
    * [ ] look in the row of your variant
    * [ ] Start 3DS button_secondsPassedSinceStart_median and mean should show the time your timer shows
    * [ ] **variant 1**: tried client-side validation_validationFailure_ccHolderMissing is 1
    * [ ] tried client-side validation_validationFailure_ccNumberMissing is 1 or 2 (depends on whether you clicked the next button right away)
    * [ ] tried client-side validation_validationFailure_ccNumberFormat is 1
    * [ ] tried client-side validation_validationFailure_expirationDateFormat is 2
    * [ ] tried client-side validation_validationFailure_cvvFormat is 2
    * [ ] tried client-side validation_validationFailure_none is 1
    * [ ] Start 3DS button_# is 1
    * [ ] 3DS validation_# is 1
    * [ ] 3DS success_# is 1
* [ ] do the same with the respective other variant -> keep in mind that the results in the admin client will be incremented if you don't recreate the test
* [ ] try canceling the verification with the OTP in the last step and check that `3DS validation_# = 3DS success_# + 1`
* [ ] select any business subscription and leave the invoice field empty, click on next and make sure that "tried client-side validation_validationFailure_invoiceDataMissing" is 1 in the desktop client

### Form Field
* [ ] when assigned variant 2, the new credit card form should show up, displaying credit card number, expiration date, security code
* [ ] clicking in one of the 2 fields and then leaving ist results in a small error message being displayed right under the field
* [ ] credit card number field
  * [ ] type some numbers and check that the right behavior according to the following rules is shown:
  * [ ] Cards starting with 34/ 37 = American Express -> length 15, length CSC: 4 chars -> CSC field also updates its hint
  * [ ] Cards starting with 4 = Visa -> length CVV: 4 chars
  * [ ] Cards starting with 5 = Mastercard -> length 16, length CVC: 3 chars
  * [ ] Cards starting with 6 = Discover -> length 16, length CVD: 3 chars
  * [ ] all numbers are grouped into groups of 4 except for American Express (4, 6, 5)
  * [ ] it is not possible to type in more than 20 numbers or the maximum number of numbers for this type of card
* [ ] expiration date field
  * [ ] 2-9 -> 02-09 / 
  * [ ] 1 -> 1
    * [ ] 0-2 -> 10-12 / 
  * [ ] 0 -> 0
    * [ ] 1-9 -> 01-9 / 
  * [ ] try around with ... and check that everything makes sense
    * [ ] using backspace
    * [ ] 2 or 4 char years
    * [ ] 3 char years / 1 char years -> invalid
    * [ ] expired dates -> invalid
* [ ] CVV field
  * [ ] if length is defined by the credit card, it is not possible to type more numbers

**Comment by nokhub** [comment]
we'll proceed with the assumption that the card holder name is not needed (sandbox 3ds validation works) but we should talk to braintree and see what the requirements are because the docs are unclear.

**Comment by ganthern** [comment]
jumping to the next field after one is filled correctly has some wrinkles:
* we don't actually know that all credit card numbers are 16 digits 
* the date 12/20 may be complete or not, we don't know
