### ISSUE TITLE
Credit card form A/B test

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#5056]
As a system administrator I want to find out how the changes to the credit card form (#5055) reduce the signup dropouts in order to see how much the changes improve the signup flow.

**AC**
- An A/B usage test can be configured that measures the following steps:
  - Starts at selection of credit card as payment method (only when the user starts typing into any credit card form field)
  - Click on next (client side validation) with client side validation errors similar to existing credit card usage test
  - Start 3DSecure (button)
  - Server side validation error (with error type, max 10 count per test)
  - 3DSecure validation finished with error (max 1 count per test)
  - 3DSecure success
- The time between the user starts credit card data until the valid credit card data is sent to the server is recorded.

See #4601 as reference for the old usage test.

**Tasks**
- [x] Create a new test with a new name, so that the old and new tests do not get confused
- [x] Adjust the first ping to be sent only when the user starts entering data into any credit card field.
- [x] Add a stage for the server side validation and add the different error types as metrics. Only count 1 error per test run.
- [x] Adapt the time recording to only record the client side credit card data entry
- [x] Adapt the pre-configured test in the admin client

## Test Notes
- see: #5055

**Comment by armhub** [comment]
Found issues when testing:
* The ping for Start 3DSecure (button) is sent before the user clicks the button in the dialog

**Comment by armhub** [comment]
Found issue during testing:
Server side errors for the credit card validation (like CVV invalid) are already returned when calling PaymentDataService.put before the user confirms the 3DS dialog (stage Start 3DSecure (button)). Therefore we need to insert another stage that collects the same error types as the stage "3DSecure validation finished with error". This new stage needs to be between the client side validation and the confirmation dialog.
We still want to keep the error collection at the 3DSecure validation stage since we fixed a bug there and therefore want to notice if we now get errors there.
