### ISSUE TITLE
App gets slow while indexing

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#5112]
Users report that while indexing the app gets slow and unresponsive in all windows.

We suspect that it has something to do with sqlite database blocking the main thread.

If that's the case we could try to use node workers (not web workers!) to offload the load.

## Tasks:
* [x] rebase the thread-per-user prototype
* [x] properly type the interface  (?)
* [x] make sure errors are propagated correctly (reported and logged)
* [x] make sure we can log stuff from the worker
* [x] check that the solution works for the dist and the dev build
* [x] make sure that the threads disappear when the user logs out
* [x] see what happens when we stop the thread while it's doing something
* [x] make sure it can shut down cleanly

## Test Notes
 * [ ] log messages from the sql worker show up in the terminal and the "send logs" attachments
 * [ ] while any window is indexing, there is no lagginess in the UI of any other window (logged into any or no account)
 * [ ] multiple windows can index at the same time
 * [ ] the search works
 * [ ] offline login still works and can show mail content, even after
   * closing windows while indexing or loading mail
   * logging out while indexing or loading mail
   * closing the app while indexing or loading mail

**Comment by bedhub** [comment]
Analyse why it is happening and the decide if and how we want to fix it.

**Comment by ganthern** [comment]
* we seem to do a lot (~64?) of requests to the sqlite database per indexed mail, some of which contain significant data that needs to get cloned while the indexer is running
* we're spending quite some time in the offline DBs run function which executes the requests (on the native side). it's unclear if memoizing query preparation could help on the browser process or the node process
