### ISSUE TITLE
Show recovery code during signup process

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#5120]
## User story
As a user I want to be able to note down the recovery code during the signup process so that i can  log into my account even if I save my password incorrectly.

## AC

* Recover code shows up on congratulations page 
* Congratulations page is shown for paid signups too
* Congratulations page should not be displayed as another step but should mark the last step as completed
* Remove Vitor from the buy page
* Do not show recovery code news item right after login

## Tasks

* [x] move vitor to the congratulations page for premium signup
* [x] add the recovery code field there
* [x] use that page for both free and premium signup (last step)
* [x] change the wizard so it shows all steps as completed when on the congratulations page
* [ ] change the recovery code news item so it does not show up immediately, but has a 2-week repeat period until acknowledged completely, at which point it does not show up again
* [ ] adapt the text of the news item so it makes sense with these changes.
* [x] remove the usage test for the recovery code news item (client & admin client)

## Test Notes:
- [ ] Create the recovery code news item in the admin client
  - [ ] Name: `recoveryCode`, disable live date
- [ ] create a free account
  - [ ] the wizard shows 2 stages (numbers at the top) and the last page (which is not counted towards the numbers at the top) is the congratulations page
  - [ ] it is not possible to go back to earlier stages after the congratulations page is reached
    - [ ] the buttons with numbers at the top aren't clickable anymore
    - [ ] there is no "go back" button in the top left corner
    - [ ] using the browser back button or the android system back button will ask you, whether you really want to close the dialog
      - [ ] clicking cancel leaves everything unchanged
      - [ ] clicking confirm closes the account creation wizard -> check that you can still login to the just created account
      - [ ] check that the back buttons show the same behavior in all other stages
- [ ] create some paid account (try different types of paid accounts)
  - [ ] the wizard shows 4 stages (numbers at the top) and the last page (which is not counted towards the numbers at the top) is the congratulations page
  - [ ] make sure that the wizard shows the pages to select a payment method and the page to confirm the selected payment
  - [ ] it is not possible to go back to earlier stages after the congratulations page is reached
    - [ ] the buttons with numbers at the top aren't clickable anymore
    - [ ] there is no "go back" button in the top left corner
    - [ ] using the browser back button or the android system back button will ask you, whether you really want to close the dialog
      - [ ] clicking cancel leaves everything unchanged
      - [ ] clicking confirm closes the account creation wizard -> check that you can still login to the just created account
      - [ ] check that the back buttons show the same behavior in all other stages (especially after the page were the email address and password is selected)
- [ ] the numbers that are indicating the current step in the wizard are focusable via keyboard
- [ ] login in to the newly created account and make sure that the recovery code news item does not show up and that it is also not counted to the red indication next to the light bulb which shows how many news items are present
- [ ] login to some account that is definitely older than 2 weeks and is global admin and check that the news item is shown
  - [ ] create a new global admin user from this account and make sure that the news item is not shown for this new user
- [ ] login to some account that is definitely older than 2 weeks and is not global admin and check that the news item is not shown
- [ ] when logged in and switching from a free or from a paid subscription to another paid subscription the congratulations page does not show up
- [ ] open the wizard to add a custom domain
  - [ ] at the top left corner is a back button that also works
  - [ ] when hitting the browser back button you will be asked whether you want to close this dialog or not
  - [ ] when reloading the tab or trying to close it will ask you whether you really want to do this (native browser dialog)
    - [ ] clicking the respective button again forces it to reload /close without waiting for your input
- [ ] go to mail.tutanota.com/signup closing the tab or reloading the page will ask you whether you really want to leave when you at least clicked somewhere on the wizard
- [ ] redeem a giftcard by clicking the giftcards link -> closing the tab and reloading the page will ask you whether you really want to leave when you at least clicked somewhere on the wizard

### Regressions:
- [ ] directly go to a mail url or other view that requires a login and check that you're logged in
- [ ] open mail.tutanota.com/recover closing the tab/going back works fine
- [ ] log in to some account that is global admin and older than 2 weeks -> shows the recovery code news item
  - [ ] Click "done", confirm dialog, confirm that the news item is dismissed
  - [ ] Log in to another account, click "display recovery code", enter password, confirm that the action buttons work, click "confirm", confirm that the news item is dismissed

**Comment by nokhub** [comment]
handling browser back:

we can catch the popstate event as modal/viewslider do, but we're in the login view during signup and that one has `requireLogin: false`, so we're forcibly logged out and reloaded if we already have a session (after account creation).
