### ISSUE TITLE
Conversation View Phase I Part II

### ISSUE THREAD

**Issue by wrdhub** [tutao/tutanota#5134]
As a user I want the most awesome conversation view possible. 

Here are some changes we want based on feedback:

## Tasks
- [x] Drafts in conversation:
    - [x] Draft indicator on collapsed mails that are drafts (just icon or word bubble? -try and see what looks best)
    - [x] Drafts that are in the trash folder (or descendant folder) should not show up in the conversation
    - [x] Actions that are in the "more" selection should be appropriate to drafts (only delete, move, edit)
- [x] Unread mails in conversation should have an indication like the mail list view, a red circle and have text be bold
- [x] Button to expand block-quote in mail:
    - [x] Replace the current button with an indicator that something is collapsed
    - [x] Have a button that's clearly not a part of the email, should overlap the space between the email and blank space (see 10.02 refinement for example)
- [x] Selected email should always be at the very top of the view, possibly dynamically add more whitespace to make this possible
- [x] Option to disable conversation view:
    - [x] Option should be in Email settings and be on/off
    - [x] When off, instead of a conversation, the single mail is shown
    - [x] Option is on by default
 - [x] Changes to mail header/collapsed email UI:
    - [x] Do not bold the selected mail header
    - [x] If there is no Sender name, nothing is displayed on the collapsed mail. Display the sender email
    - [x] Have the Sender name header be consistent between collapsed and expanded mails
- [x] Floating Subject:
    - [x] Remove the pop-down animation 
    - [x] Make the font size the same as the subjects in the conversation list
- [ ] ~~Our own event replies don't get a normalized subject, causing it to be re-rendered with the "replied: " (en) prefix for every reply. Fix this.~~ -> Looking at this more, I think it is fine. Unless someone else complains, we will not change
- [x] Use conversation view in search view (do this last)

**Comment by ganthern** [comment]
is on master now :partying_face:
