### ISSUE TITLE
Introduce password confirmation 

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#5185]
## User story
When specifying a password for my account as a user I want to enter the  password a second time so that the input for the two  password fields are compared against each other and i can be sure that I typed the password correctly.

## AC
* a second password field is shown during signup
* a second password field is shown during password change
* when the password is reset via recovery code a second password field is shown during recovering login
* when the passwords don't match the error is shown below the second password field
* when the user tries to proceed with unmatched passwords the error message is shown in a dialog
* password reveal button must be present on both fields
* for changing user password as an admin no confirmation is shown
* password strength is only shown for the first password field

## Tasks:
* [x] create a component that contains two password fields (both with reveal buttons)
  * error below the second password field if the password don't match -> hint below the field
  * get method that returns password if both match or error (Translation key) if not (updates while typing - not when second field is empty)
  * error is shown in a dialog if the next (signup...) button is clicked
  * password strength only for the first password field
* [x] use this component for:
  * signup
  * password change
  * password reset: replace the two existing password fields with the new component
* [x] check that only one password field is present in the settings when changing a user's password

## Test Notes:
* [ ] check that a second password field for confirmation is shown for:
  * [ ] signup
  * [ ] change password in the settings
    * [ ] login settings
    * [ ] own user in user settings
  * [ ] when sending a request via contact form -> bedpremium has a contact form
  * [ ] resetting the password with the recovery code
* [ ] check that there is only one password field for:
  * [ ] change password of some user in the settings
* [ ] check that the password form with the confirmation field behaves right
  * [ ] both password fields have a reveal button that can be independently toggled
  * [ ] the dialog doesn't let you proceed if the confirm password field has no input -> dialog with `Please confirm your password.`
  * [ ] the hint below the confirm field is `Please confirm your password` if no password is typed in
  * [ ] the dialog doesn't let you proceed if the confirm password field has input which does not match the other typed in password -> dialog with `Confirmed password is different.`
  * [ ] the hint below the confirm field is `Confirm password is different`
  * [ ] when the right password is in the confirm field, the hint is `Password ok.`
  * [ ] it is possible to proceed if the confirmation field contains the right password
  * [ ] if both password fields contain no input it is not possible to proceed -> dialog `Please enter a new password`
  * [ ] if only the confirm field contains input it is not possible to proceed -> dialog `Please enter a new password`
* [ ] when changing the password of a user check that:
  * [ ] all three password fields have a reveal button that can be independently toggled
