### ISSUE TITLE
Simpler folder editing in desktop layout

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#5298]
## User story
As a user, I want to be able to edit my folder list and/or single folders without having to change my scroll position in the list or go to edit mode.

## AC
* three dots button is shown when  hovering/focusing a folder row by either using a mouse or keyboard navigation.
* when the button is shown the folder counter is not visible
* the button opens a drop down which provides access to add folder, edit folder and delete folder action.
* An "Add folder" (secondary) button is shown as the very last row of the custom folder list.
Simpler Folder Editing

## Tasks
 - [x] Switch unread mail counter to always show the full number
 - [x] Switch to "more" button on hover/focus for the folder row
 - [x] Add "add button" folder below the folders

## Test notes
- [ ] Hovering over a folder shows the "More/Three dots" button
    - [ ] Does not appear for trash or spam folders 
- [ ] Using the keyboard to tab over a folder has the more button appear and you can tab to it and use it 
- [ ] clicking on that button allows for editing options
    - [ ] Appropriate actions are shown: only add folder for system folders, and Edit, Add folder, Delete for custom folders
- [ ] Executing these actions works as expected 
- [ ] Add Folder button appears at the end of the custom folder list
    - [ ] You can click on this button and add a folder
