### ISSUE TITLE
Multi-select indicator & select all

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#5301]
## User story
As a user, i want to have a visual indication that i can select/deselect all and individual items from the loaded list, so that i can run actions for the selected items.

## AC
* A checkbox is shown in the toolbar which allows selecting all loaded emails, contacts or search results
* A checkbox is shown for each individual list item
* The number of selected items are shown in the viewer section.
* If the list is not loaded completely we show another button in the viewer to load and select all.
  * While we try to load all items we show the progress in some way
  * If the selection if switched while loading, the loading is stopped

## Tasks
 - [ ] Adapt the design of the first column action ("new email"/"new contact" to fit the toolbar in some way) 
 - [x] Implement new design for the list and mail row
 - [x] Implement "select all" button that selects all loaded items
 - [x] Implement true "load all", progress and cancellation
 - [x] Do not run into rate limits right away
 - [x] Fix contact list
 - [x] Fix template list
 - [x] Fix user list
 - [x] Fix group list
 - [x] Fix contact form list
 - [x] Fix knowledge base list
 - [x] Fix quick search

![Image](https://user-images.githubusercontent.com/3099142/227905823-14237357-e3f3-4d3b-bb81-015ab523dd0c.png)

note: the filter function is not part of this issue

## Test notes
 - [ ] Test select all
   - [ ] it shows correct version of multiselection in the viewer with an ability to load all or deselect
 - [ ] Test load all
   - [ ] It progressively loads and selects
   - [ ] Cancellation should stop it
   - [ ] Continuing should pick up from where it left last time
   - [ ] Changing to another folder stops the loading
   - [ ] Changing to another view stops the loading
   - [ ] Test that scrolling does not affect loading progress
 - [ ] Test actions applied to a lot of emails at once
   - [ ] Marking a lot of emails read/unread does not start too many requests at once 
 - [ ] Test that above things also work in search
   - [ ] Changing search criteria stops the loading
   - [ ] Viewer works correctly in search too
 - [ ] Check that list rows look correct:
   - [ ] Mail
   - [ ] Contact
   - [ ] Template
   - [ ] User
   - [ ] Group
   - [ ] Contact form
   - [ ] Knowledge base
 - [ ] Check that there are no checkboxes in mail/contact rows when in single-column layout
