### ISSUE TITLE
Toolbar in mail viewer

### ISSUE THREAD

**Issue by wrdhub** [tutao/tutanota#5306]
## Tasks
- [x] Update the UI to have a toolbar above the mail view (not the mail list side).
- [x] Add action buttons like in the below screenshot (not the mail list side).
- [x] Ensure that correct action buttons appear for the selected mail/user authority.
- [x] Actions on mails in the viewer will be in the "more" (three dots) button.
- [x] When multiple mail are selected, the mail viewer displays how many mail are selected and the actions are in the toolbar.
- [x] The toolbar will be included in mail search view.
- [x] The toolbar will show on the two and three column layout.
- [ ] Always display subject above the selected card, and should be visible when the email is first opened (but does not stick when scrolled).

![Image](https://user-images.githubusercontent.com/119855382/227898994-18c1e0cb-4558-419a-850c-a79f029337fd.png)

## Test Notes
- [ ] General
    - [ ] Toolbar is displayed for mail view in three-column and two-column mode
    - [ ] Toolbar is not displayed single column mode
- [ ] Mail view
    - [ ] toolbar has expected actions for a mail
    - [ ] the action buttons all work
    - [ ] action buttons are navigable with keyboard
    - [ ] keyboard shortcuts still work
    - [ ] all available actions for a mail are available on its card under the three dots button
    - [ ] When opening a mail, it is scrolled to the correct spot (to the subject or displaying some of the previous entry)
- [ ] Multiple mails selected 
    - [ ] toolbar shows actions related to multiple selected mails
    - [ ] The action buttons work
    - [ ] the "cancel" button works and deselects selected mails
- [ ] Search View
    - [ ] The toolbar also works for mails in the search view (including multi-select)
    - [ ] search for contacts works as expected
    - [ ] multi-select for contacts works as expected
