### ISSUE TITLE
Toolbar in contact viewer

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#5307]
## Tasks
 - [x] Design contact viewer to be closer aligned to mail viewer: toolbar above the viewer and contact as a card
 - [x] Adapt contact viewer to new design
 - [x] Make sure it is consistent with search results viewer

## Test notes
 - [ ] Contact viewer shows all information correctly
 - [ ] Switching between contacts works without issues
 - [ ] Editing contacts leads to them being updated in the viewer
 - [ ] Mobile toolbar for contact viewer works
