### ISSUE TITLE
Uncaught BadRequestError: Invalid Mail address in mailaddressaliasservice

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#5356]
```
I clicked on the add + icon that is next to the new domain name


Client: Browser
Type: PREMIUM
Tutanota version: 3.112.6
Timestamp (UTC): Sun, 09 Apr 2023 10:10:39 GMT
User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/111.0
BadRequestError
Error message: 400: NS_Ul9L----9 | POST /rest/sys/mailaddressaliasservice
Stacktrace:
BadRequestError. 400: NS_Ul9L----9 | POST /rest/sys/mailaddressaliasservice
```

Server log:
`
I 12:10:39.382 sys RootHandler.java:537 M08Hc5h----2 NS_Ul9L----9 de.tutao.tutadb.rest.exceptions.BadRequestException:invalid mail address - POST /rest/sys/mailaddressaliasservice/ `

we may want to log the address, we're doing it for mailaddress availability already and it's easier to catch what's wrong that way.

## Tasks

- [x] Log invalid email address in mailaddressaliasservice similar to mailaddress availability service
- [x] Prevent adding empty aliases in custom domain setup

**Comment by bedhub** [comment]
The error appears when users are clicking the add button with an empty email field in the custom domain setup flow.
We should show a proper error message in that case.

**Comment by armhub** [comment]
Server part is implemented on branch "print-invalid-alias-in-alias-service"

**Comment by armhub** [comment]
Test notes

- [ ] Add an email domain. On the alias page during this setup click on the + button without entering any username.
- [ ] When entering an invalid username and pressing + an error message should be shown and the username should be deleted. This is currently the expected behavior.
- [ ] Regression test that adding Tutanota and custom domain aliases works in custom domain setup, Mail settings and user management
