### ISSUE TITLE
Toolbar changes

### ISSUE THREAD

**Issue by wrdhub** [tutao/tutanota#5383]
## Tasks

- [ ] checkbox: make hit box area larger, and have more space between it and the sender name
- [ ] Add subject to mail card, do not have it in conversation list
- [ ] select all shortcut (already done: https://github.com/tutao/tutanota/pull/5363)
- [ ] Change time formatting (should this be a separate issue?):
    - [ ] Just time for today
    - [ ] Just "Yesterday" for the previous day
    - [ ] Just day of the week for last seven days
    - [ ] Just date for older (Month, day, year; no day of week or time)

Bugs
- [ ] tutanota team badge is not next to sender name
- [ ] opening an email from search view doesn't push the sender's address to the admin client.
- [ ] draft edit button missing in toolbar when draft mail is selected
- [ ] open an email > hold Ctrl and select a different email > the original one is not selected, have both be selected
- [ ] Fix border between header and list on mobile
- [ ] fix scrollbar on mobile

UI changes
- [ ] Font size in mail list: Have larger font size. 16 for sender, 14 for subject 
- [ ] Make selected mail in mail list be darker, maybe make text red too
- [ ] checkboxes: use lighter color in list (maybe not in the toolbar)
- [ ] Increase padding, reduce margin for mail list items
- [ ] Dot for unread emails: no checkbox, so should be on first line
