### ISSUE TITLE
Search in Settings for Templates and Knowledgebase

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#5406]
## User story
As a user I want to be able to search in templates and knowledgebase entries to find things more easily.

## AC
* Search input field is available on top of the list when Templates and Knowledgebase are visible in the settings
* This search function is the same as the filters in the mail editor (the template shortcut/the knowledgebase button)
* Non-matching items are filtered out of the list, only leaving matching items that the user can navigate through.
* If no items matches there should be a "no matches" text similar to the empty list message.

## Tasks
 - [x] Replace template list with the new list
 - [x] Add a filter bar to the template list
 - [x] Replace knowledge base list with the new list
 - [x] Add a filter bar to the knowledge base list

## Test notes
 - [ ] Filtering templates works
 - [ ] Filtering knowledge base works
