### ISSUE TITLE
Manage contact lists

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#5407]
## User story
As a user I want to be able to create recipient lists so that i can assign multiple email address to a single identifier.

## AC

* There is a new section in the folder of the contact view named "Recipient lists"
* Next to heading there is an "Add" button.
* A dialog appears where the user can specify a name for the recipient list.
* The dialog also contains an address input field to add recipients that behaves similar to adding guests to an event.
* An added recipient is shown below the address input  field.
* second column shows a list of all recipients in the selected list and supports multiselect
* if only one recipient is selected, the third column shows a view with
* card that shows the recipient address and a "remove from list" button and a "create contact" button that brings up a contact * editor with that address prepopulated
* one card per contact in the current users contact list that has the recipient address assigned as a full contact viewer. each has delete and edit in the more menu
* in multiselect, a multiselection viewer is shown similar to the mail multiselect:
   * cancel seelction
   * mass actions (remove from list)
   * delete recipient lists is possible similar to calendars
* edit recipient list: renaming, adding items is possible
* Recipient lists are only available for new paid plans 

## Notes
- Service similar to calendar or templates (keep in mind sharing in the future)

## Tasks
- [x] Make a model for recipient list that has entries of email
- [x] Make a service that can create, delete, and edit recipient lists
- [x] Add section for recipient list in contact view
- [x] Create list view (2nd column)
- [x] Be able to add new recipient lists (create dialog)
- [x] Be able to remove recipient lists
- [x] Create recipient list viewer (3rd column view)
- [x] Be able to add new entries to the list (create dialog)
- [x] Remove entries from list
- [x] Have create contact button on emails that do not have a contact
- [x] Add support for multiselection
- [x] Edit recipient list
- [x] Make recipient list are only available for paid plans (check in to see which plan)

## Test notes
TBD

 - [ ] Test migration from previous model for customer with and without custom plan (to get custom plan upgrade an account from old plan and then roll it back in the admin client)
 - [ ] Creating contact lists is possible with new paid plans
 - [ ] Creating contact lists is not possible with free plan
 - [ ] Creating contact lists is not possible with old plans
 - [ ] Downgrading is not possible if there are any contact lists
 - [ ] Opening contact view loads contact lists
 - [ ] Deleting contact list is possible
 - [ ] Creating contact list entries is possible
 - [ ] Renaming contact list is possible
 - [ ] Showing contact lists is possible
   - [ ] Desktop
   - [ ] Mobile
 - [ ] Related contacts are shown in contact list entry viewer
     - [ ] you can edit contact in in this view
     - [ ] you can delete contact in this view
 - [ ] If there is no related contact, "No contacts with this email found. Create Contact" message shows
     - [ ] clicking "create contact" brings up the contact editor with the email address already filled in
     - [ ] you can save and contact appears 
 - [ ] Creating/deleting entry updates the list
 - [ ] Loading entry by URL will load and select the entry
 - [ ] Switching between lists/contacts works correctly and updates the URL
 - [ ] Multiselect actions (delete) work
 - [ ] clicking the plus button in the list toolbar brings up dialog where more recipients can be added
     - [ ] a recipient already in the list (in the dialog) will not be added again
     - [ ] a recipient already in the greater contact list will be added in the dialog, but after saving there will only be one entry
 - [ ] Actions in Mobile view are appropriate to Contact or Contact List
     - [ ] Clicking the Plus button in the header will add Contact or Contact List Entries 
     - [ ] The sort option in the header shows and works for contacts, but does not display when looking at a contact list   

Regression
- [ ] Interacting with contacts through "All Contacts" still works
    - [ ] Multiselect actions work
- [ ] You can use "New Contact" button to create a new contact
- [ ] loading contact by URL will load and select contact
- [ ] Contact actions (delete, edit, export) still work as expected

**Comment by kibhub** [comment]
"Loading entry by URL will load and select the entry" does not work

**Comment by kibhub** [comment]
Some notes:

- Adding invalid email address does not throw an error. Editor vanishes and invalid address is not added.
- Adding a duplicate address does not throw an error/warning.

**Comment by GenericGuy** [comment]
Is this feature intended to be unavailable with the old subscription model?

**Comment by wrdhub** [comment]
> Is this feature intended to be unavailable with the old subscription model?

Yes. The new paid plans are more expensive, and so we feel that it is fair that some features are only available with those plans. This is in part to incentivize switching, but also because that extra support really does help us to be able to work on these new features.

We appreciate everyone's support so that we can continue to work on Tutanota!
