### ISSUE TITLE
Change mobile layouts & improve the design

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#5408]
Adapt mobile layout (1 and 2 column layout)

## Tasks
 - [x] (fix and) merge #5119
 - [x] Adapt mobile header layout to the new design
 - [x] Adapt top-level layout to have header in the list column and toolbar in the viewer column
 - [x] Implement "enter multiselect" action for the list without selecting any items
 - [x] Adapt mail/contact rows to show/hide checkboxes
 - [x] Implement animation for entering/leaving multiselect mode
 - [x] Adapt 2-column layout to have the main action (e.g. new mail) in the toolbar
 - [x] Adapt multiselect mobile layout to have actions in the bottom
 - [x] Remove shadow from bottom nav bar, use separator instead
 - [x] Remove borders below the nav bar, above the header bar
 - [x] New mail view design
 - [x] New contact view design
 - [x] Updated calendar design
 - [x] Updated settings design
 - [x] Updated login screen design
 - [x] Updated external login screen design
 - [x] Updated termination screen design
 - [x] Updated search screen design
 - [x] Updated search bar design
 - [x] New translations
 - [x] Change bottom multi action bar for mail to have proper order of buttons
 - [x] Cleanup some duplication for bottom action bars
 - [x] Adapt native Android part
 - [x] Adapt native iOS part
 - [x] Adapt native Desktop part
 - [x] Fix mail sender line
 - [x] Move calendar buttons back to the left
 - [x] Fix invisible single selection in single column layout (either truly deselect or make sure it doesn't affect anything) 

![Image](https://user-images.githubusercontent.com/8296817/233955246-8105e1cd-670d-4f77-abc5-3711a427a15a.png)

## Test notes
 - Upgrade from previous version, see that the app  doesn't crash and uses the correct theme
   - [ ] desktop
   - [ ] android
   - [ ] ios
 - New installation, see that the app  doesn't crash and uses the correct theme
   - [ ] desktop
   - [ ] android
   - [ ] ios
 - Check select/multiselect for Mail (including single & multiselect actions). On mobile check new "enter multiselect", long press, select all
   - [ ] mobile single column
   - [ ] mobile 2-column
   - [ ] desktop 3-column layout
 - Check select/multiselect for Contacts (including single & multiselect actions)
   - [ ] mobile single column
   - [ ] mobile 2-column
   - [ ] desktop 3-column layout
 - Check select/multiselect for Search (mail & contacts) (including single & multiselect actions)
   - [ ] mobile single column
   - [ ] mobile 2-column
   - [ ] desktop 3-column layout
 - [ ] Check search bar & quick search
 - Check calendar layout
   - [ ] Mobile
   - [ ] Desktop
 - Check settings layout
   - [ ] Mobile
   - [ ] Desktop
   - [ ] Check that different window sizes work correctly
 - [ ] Check login screen UI
 - [ ] Check external login UI
 - [ ] Check that whitelabel still works and custom logo is still applied
 - [ ] Check termination screen UI
