### ISSUE TITLE
Filter for unread emails

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#5431]
## User story
As a user i want to have the option to filter my email list so that only the unread or read emails of that list/folder are shown.

## AC
* there is a button inside the mail list toolbar that allows to set a filter on the mail list to only show read email, only show unread emails or to deactivate the filter
* if you click select all while a filter is active, clicking "select all" will only select mails that match the current filter
* if more mails are loaded while the filter is active, the filter also applies to the newly loaded mails
* same with updates coming from outside: if new mail arrives in the list, it's only displayed if it matches current filter
* filter should be available in the search view  (it should possible to use it in the mobile view)
* as soon as a set of emails is loaded the filter is applied and the matching results are shown even if there are not enough emails to finish loading.
* if there are not enough results, loading continues
* while emails are loading a progress item appears as last list item.
* there is a cancel button on the progress item in the list to stop the loading.
* when loading is cancelled the "show more" item appears.

## Tasks
 * [x] List refactoring
   * [x] Introduce ListModel
   * [x] Virtual row handling
   * [x] Updates for list items
   * [x] Selection handling
   * [x] Automatic load on scroll
   * [x] Loading indicator & manual load more
   * [x] "load, scroll to and select" based on the url
   * [x] Mobile multiselect
   * [x] Sorting in contact view
   * [x] Swipe items
   * [x] Load all
   * [x] Move shortcut
   * [x] Empty list state
   * [x] Update URL
   * [x] Keep track of selection per folder
   * [x] Focus viewercolumn when we select a mail
   * [x] dragging mails
   * [x] socket for admin client
   * [x] self-healing unread mail counters
   * [x] mutliselect not allowed in some lists
 * [x] Filter
   * [x] Model for the filtered list
   * [x] UI for filtering in the toolbar mail view
   * [x] UI for filtering search view
   * [x] cancelling of loading

## Test ntoes
 - [ ] Switching between mails
 - [ ] Multiselect mails (different methods, including keyboard and checkbox and mobile multiselect)
 - [ ] URL is updated correctly
 - [ ] Loading the app with mail URL will try to load and display that email
 - [ ] Loading more works
 - [ ] Cancelling of loading works
 - [ ] Network errors are handled correctly
 - [ ] Inbox rules are applied
 - [ ] Selected folder/mail is remembered when switching between views
 - [ ] Filtering mails works
 - [ ] Mails don't disappear if they stop matching the filter
 - [ ] Loading can be cancelled and resumed
 - [ ] Load all still works
 - [ ] Load all still works in search
 - [ ] Load all works with filters
 - [ ] Contact list works
 - [ ] Search view works
 - [ ] Filters work in search
 - [ ] Filters work in mobile mail view
 - [ ] Filters work in mobile search view
 - [ ] Secure external mails
 - [ ] Mailto & MAPI
 - [ ] Contact forms

**Comment by dergigi** [comment]
It's ridiculous that this doesn't work and that it has been like this for [three years](https://archive.is/ui4Qa).

**Comment by vitoreiji** [comment]
> URL is updated correctly
 What does "correctly" mean?

**Comment by vitoreiji** [comment]
> Network errors are handled correctly

Again, what does "correctly" mean? Also, which network errors, other than being offline, and how to I trigger them?

**Comment by charlag** [comment]
> > URL is updated correctly
> 
> What does "correctly" mean?

- [ ] URL is updated every time you switch between folders or mails and only once per switch
- [ ] it remembers the mail per folder
- [ ] it remember the folder that was open before leaving mail view
- [ ] in multiselect the element id part is removed from the URL

**Comment by charlag** [comment]
> > Network errors are handled correctly
> 
> Again, what does "correctly" mean? Also, which network errors, other than being offline, and how to I trigger them?

You can trigger network errors by breaking the connection, either by actually disconnecting or by using devtools (only works in browser). So yeah it means offline.

It should stop loading and show "load more" button and it should be able to continue when you press on it.
