### ISSUE TITLE
Improved calendar event viewer and editor

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#5437]
the calendar event editor and view model are monolithic and hard to test / extend.

as user I don't want to be confused by being offered to edit an event when I can't actually edit it. I still need to be able to set my attendance and alarms without having the full event editor available.

## AC

* it's not possible to edit anything about the attendees in an event that was created in a calendar that was shared with you
  * if it has guests, the editor cannot be opened for it (because you're not the organizer and cant send updates)
  * if it has no guests, the editor can be opened, but the guest list is replaced with a message stating "you cannot invite people to an event that was not created in one of your personal calendars"
* in your own calendars, the calendar details popup shows a selector for your own attendance if you're invited to it (similar to the invite banner or as a dropdown like in the editor. keep it short)
* it's not possible to set the same alarm multiple times in the editor

## Tasks

* [x] finish splitting the CalendarEventViewModel into components that 
  * uphold invariants while the editing operation is in progress
  * contains the logic necessary to do higher-level operations like rescheduling, excluding
  * sending updates/cancellations/invites
* [x] re-write the calendar event editor to always be writable (don't open it for read-only events)
  * in cases where the event is partially writable, add a message that states that this is the case and why
* [x] adapt calendar popup to enable
  * [x] setting and viewed your own attendance (if you're invited)
* [x] update the calendar documentation in the doc project with the most important high-level concepts and the invariants (or where to find them - tests)
* [x] add the new translations to phrase

## Test Notes
personal calendar = calendar that's shown under "your calendars"
(rw/ro)-shared calendar = calendar that's not shown under "your calendars" (read-write/read-only)

**event popup**
* [x] the event popup shows only the close button for ro-shared events or on invites in external mailboxes
* [x] it shows edit, delete and close for events in personal calendar and rw-shared calendars
* [x] it shows edit, delete, close, send update for events with attendees in personal calendar, but not in rw-shared calendars.
* [x] it shows the yes/no/maybe buttons with the selected one highlighted if you're an attendee, but only in personal calendars.
* [x] these butttons also work as expected - status is set, the event is updated, response mail is sent
* [x] the buttons are not shown in events where you're not invited.

**event banner (mailview)**
* [x] for tutanota users, the event banner still can be used to set the attendance and adds the event to the first personal calendar.
* [ ] for external users, the event banner can be used to send a response, but does not add the event to any calendars.
* [x] the banner can be used to open the popup

**event editor - personal calendar**
* [x] editor for a calendar event with no attendees is fully editable and does not show the note about partially editing.
* [x] it's impossible to change the organizer address unless the event is completely new or had no attendees
* [x] in cases where the organizer address can change, the selector shows the active aliases of the user
* [x] the selected organizer address is used for sending the invites.
* [x] saving a new event sets it up correctly on the server, sets the alarms and sends invites/updates/cancellations as required.

**event editor - rw-shared calendar**
* [x] the editor for a rw-shared event without attendees is fully editable except for the attendees and shows the note about partial editing.
* [ ] it's not possible to open the editor for an event that has attendees

**event editor - ro-shared calendar**
* [x] it's not possible to open the editor for events in a ro-shared calendar.

**event editing - general**
* [ ] editing the calendar an event is in works as it should:
  * [ ] for new and existing events, all writable (shared and personal) calendars are selectable while there are no guests added
  * [x] if there are guests in a new event, the calendar dropdown only shows personal calendars
  * [x] if there are guests in an existing event in a shared calendar, the calendar cannot be changed
  * [x] if there are guests in an existing event in a personal calendar, the calendar can only be changed to other personal calendars
* [x] editing an event without changing the start time works
* [x] editing an event with changing the start time works
* [x] events show at the right time in the calendar, even when switching time zones:
  * all-day events
  * normal events

**event editor - alarms**
* [x] existing alarms from the event are shown correctly
* [x] in shared calendars, only the alarms set by the current user are shown and editable.
* [x] it's possible to add new alarms, but only if an alarm of that time does not exist yet
* [x] it's possible to remove alarms
* [x] the selected alarms are set up correctly after saving and fire at the right time (test switching timezones)

**invites**
* [ ] only paying customers can send or respond invites
* [x] responding to invites from external mail services works and is applied
* [ ] responding to invites from secured external tutanota mail boxes works

**exclusions**
* [x] can be deleted from the editor (if editing the event is possible for the current user)
* [x] can be added from the popup by selecting the correct option from the delete-dropdown
* [x] can not be added for non-repeating events or repeating events that have only one occurrence left that's not excluded
* [x] will be displayed correctly in different time zones
* [x] will not be deleted when merely changing the event from all-day to not all-day or back
* [x] will be deleted if anything else about the event scheduling changes
* [x] will not be deleted if any other fields change

**regressions**
* [x] import of events still works
  * in tutanota, exported from tutanota and form other mailboxes
  * in other mailboxes, exported from tutanota
