### ISSUE TITLE
Replace lists in settings

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#5541]
With filter for unread emails we now have a filter implementation for the list and also new list components and we should use them in the rest of the codebase.

Additionally we don't need to use search & search index infrastructure for simple search implementations in settings.

## Tasks
 - [x] Replace user list with the new list
 - [x] Add a filter bar to the user list 
 - [x] Replace group list with the new list
 - [x] Add a filter bar to the group list
 - [x] Update search bar/search index to not include groups
 - [x] Remove whitelabel children
 - [x] Replace contact form list with the new list

## Test notes
 - For each list check that search, filtering and selection works
 - Selection should focus the right column
 - Entity updates should be applied
