### ISSUE TITLE
Add Tutanota as share option

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#556]
As an iOS tutanota user, i want to have tutanota show up in the system share menu so I can easily send attachments and text from any app.

### Acceptance Criteria:
- it's possible to select tutanota from the share menu (insert screenshot here)
- files are attached to a new mail viewer
- text is inserted into the body

### Tasks
- [x] Write documentation
- [x] Check how we can test this automatically.
- [x] Code cleanup

### Notes:
- this requires an action extension or share extension
- write the data to a location that can be accessed by the extension and the main app
- we'll need a custom protocol to call the app with openURL from the extension (trick the OS into allowing us to open the main app)

### Test Notes

Each share request results in a new mail editor being opened.

test sharing different things on iPad and iPhone 13 mini, try hot boot (app is already in background) and cold boot (app is completely closed):

* [ ] sharing the website from safari should result in a mail body containing the shared URLs
* [ ] sharing an image from safari should result in a mail body containing a link to the image
* [ ] sharing text from safari results in a mail body containing that text
* [ ] sharing a contact from the contacts app results in a mail with a vcf (vcard) attachment

Files:
* [ ] use the file app to share a single file -> it gets attached
* [ ] multiple files (below 25MB) -> they get attached
* [ ] files over 25MB -> the mail editor does not get created
* [ ] files with spaces in the name -> get attached

Photos:
(from the Photos App)
* [ ] single photo gets attached
* [ ] multiple photos get attached

Signal - you can connect your account temporarily and log out after:
* [ ] sharing a voice message becomes a audio file attachment
* [ ] sharing an attached file from a message results in that file being attached
* [ ] sharing an image from a message results in that image being attached

**Comment by Pryla** [comment]
Almost 4 years later. How far are we with this feature? It's really missing tbh. Cannot share a single file from nowhere. Always need to add it via "add attachment". [In November 2019 the Tutanota Reddit account stated:](https://www.reddit.com/r/tutanota/comments/bwn3us/comment/f74vrtx/?utm_source=share&utm_medium=web2x&context=3) "It's on the roadmap so it shouldn't be that much longer, but at least a couple of months still."
