### ISSUE TITLE
Unlimited custom domain mail addresses

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#5584]
As a user who owns a custom domain, I want to be able to define as many email addresses as I want with that domain, so that I can take full advantage of my domain name.

## AC
* Custom domain mail addresses are not counted as used email alias for plans with unlimited custom domain alias support.
* Behavior for Tutanota domain aliases does not change
* Unlimited custom domain alias feature is available for all new paid plans
* Numbers of used / available aliases are shown in the settings including a hint that custom domain aliases do not count towards the email address limit.

## Additional info
* Showing this feature in the plan feature list (website and client) will be handled in a separate issue.
* Server branch is unlimited-custom-addresses-5584

## Tasks
- [x] Adapt settings to show the number of used Tutanota email addresses and info about what affects limit
- [x] Add new translations to Phrase
- [x] Adapt server side to allow this
- [x] Make sure downgrading checks for all kinds of aliases

## Test Notes
* [ ] it's not possible to downgrade to free if there are any extra addresses enabled
* [ ] the number of used / enabled addresses does not change for new plans when adding or deleting custom domain addresses
* [ ] the number does change as expected when adding / disabling / enabling tutanota addresses for new and legacy plans
* [ ] it's possible to add more custom domain addresses if the limit is reached for tutanota addresses on new plans
* [ ] it's still possible to reassign any addresses to a different user when the limit is reached on the sending user
* [ ] it's still possible to reassign any addresses to a different user when the limit is reached for the customer on legacy plans
* [ ] it's only possible to reassign an address to a different user when the user's "used" limit is not reached (new plans)
* [ ] for legacy plan customers, the custom domain addresses still count towards the limit
* [ ] it is not possible to switch to a plan with less aliases if the "used" aliases count is higher (new plans and legacy)

**Comment by vitoreiji** [comment]
Should also consider implementing #4566.

**Comment by D0T1X** [comment]
When this is being implemented. I feel like it would also be a huge opportunity to integrate it with services like bitwarden. To have the alias be auto-created if at all technically possible.
https://bitwarden.com/blog/use-bitwarden-to-generate-email-aliases-with-fastmail/

**Comment by githupper** [comment]
It is stated as Done but as of right now, still not able to create more than 15 aliases with my custom domain.

Am I missing out something?

**Comment by vitoreiji** [comment]
@githupper "Done" means we are done developing it, not necessarily that it is already released. We finished this recently, so it will be on the next release.

**Comment by C8opmBM** [comment]
Finally! 
You were really lagging behind and I was just about to jump ship to skiff. Glad I searched and found this.

I hope this will apply not only to the highest tier plans, but all plans which have custom domain option.

**Comment by C8opmBM** [comment]
The update has just been released, the hint is present (_custom domain addresses do not count towards the limit_), however they DO count towards the limit.
I tried deleting and re-adding one, same behaviour.

I have the old premium plan with 5 aliases and 1 custom domain.
Can you please clarify? Thanks!

**Comment by ganthern** [comment]
This feature only applies to the new paid plans (Revolutionary, Legend, Essential, Advanced, Unlimited)

**Comment by C8opmBM** [comment]
Not good tutanota. I've been waiting for this for a long time to drop anondaddy or refrain from going to skiff which offer this for free. You will, slowly, be left behind.

Have a good day.

**Comment by quamok** [comment]
> > I have the old premium plan with 5 aliases and 1 custom domain.
> 
> This feature only applies to the new paid plans (Revolutionary, Legend, Essential, Advanced, Unlimited)

So I guess we will slowly see users using the old paid plan being left behind on new features to try force their hand to migrate to one of the newer more expensive plans?

**Comment by ganthern** [comment]
I'd like to hear compelling arguments against existing customers getting what they paid for (a supported and regularly maintained product) and us financing the development of new features in a way that enables us to expand development capacity.
