### ISSUE TITLE
Migrate local storage data

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#5637]
As a user of [mail.tutanota.com](http://mail.tutanota.com/) I want to keep my stored credentials and config when the domain changes to the new domain so I do not have to set up everything from scratch.

## AC

*  When navigating to [app.tuta.com](http://app.tuta.com/) from the website, any existing credentials and local config from [mail.tutanota.com](http://mail.tutanota.com/) are transferred to the new domain (deleted from the old)
* The previous step is done without any cleartext information being transferred in the browser history or to any server.
* When using any mobile or desktop app after the domain change, any saved credentials and config values will still work.
* On the login page on mail.tutanota.com mention that Tutanota is called Tuta now and login will move to app.tuta.com. There should be a link in the banner to go directly to the login on app.tuta.com.
* When (trying to) move the credentials away from mail.tutanota.com we store the information in local storage that this has been done.
* When (trying to) move the credentials to app.tuta.com we store the information that this has been done on app.tuta.com.
* Storing credentials on the old domain is disabled (no checkbox)

## Notes
* We accept that the search index is not transferred.

## Tasks 
* [x] web app must be enabled to run on app.tuta.com (independent of stored credentials)
* [x] check places where we hardcode tutanota.com and change them if necessary in the tutadb
* [x] check that also in the client
* [x] also in admin client
* [x] ~~update csp rules to allow app.tuta.com to load mail.tutanota.com in an iframe and make sure that app.tuta.com is the only domain allowed to do that.~~ this is now done with a new tab, but we updated the csp to disallow iframes
* [x] ~~for the test system, update the csp rules to allow test.tuta.com to load test.tutanota.com~~ see above
* [x]  on boot of the login page, check the local storage if the migration has already been attempted. if yes, continue boot as normal.
* [x] otherwise check for stored credentials on mail.tutanota.com. 
  * the new domain opens the old in a new tab and waits for credentials being transmitted
  * the old domain opens the new one in a new tab and sends all credentials over
 * [x] on app.tuta.com, store the received information and the fact that the migration was attempted.
 * [x] if the app runs on mail.tutanota.com, it should show the info banner about the new domain.
 * [x] if the app runs on mail.tutanota.com, remove the "store credentials" checkbox.
 * [x] make desktop updates and dictionaries available under app.tuta.com
 * [x] make sure that the localhost / http variant of the dev build still works
 * [x] check that whitelabel still works
   * mail
   * login 
   * blobs
 * [x] put the translations on phrase

## Release Notes
 * [x] add the DNS entries for test.tuta.com (post test release)
 * [ ] add the DNS entries for tuta.com  (post release)

## Test notes
these need to be tested in firefox, chrome and safari. it should be possible to copy localStorage from the new domain and paste it into the localstorage of the old domain to get saved credentials on the legacy domain even without the checkbox.
also, try to do this migration with different machines that have not accessed the respective other domain for a while. at least firefox is using some heuristics like "has the user interacted with this domain recently" before granting local storage access to programmatically created tabs/iframes/windows.
 
* [ ] The credentials migration banner is only shown if we are after the migration start date of the 7th of November (set window.tutao.locator.Const.CURRENT_DATE or adapt system time to test this)
* [ ] if the banner is shown on tutanota.com, no dismiss button is on it.
* [ ] if the banner is shown on tuta.com, the dismiss button is on it. it also removes the banner and prevents it from showing up again (until local storage for tuta.com is cleared)
* [ ] on tutanota.com, there is no "save credentials" box anymore after the migration start date (set window.tutao.locator.Const.CURRENT_DATE or adapt system time to test this)
* [ ] the "save credentials" box is visible on tuta.com
* [ ] with no stored credentials on tutanota.com -> banner is shown, but replaces current tab with tuta.com when clicked.
* [ ] with stored credentials  on tutanota.com -> banner is shown and opens tuta.com in a new tab, where the credentials are available and working. they are no longer on tutanota.com.
* [ ] tutanota.com does no longer auto-login even if there is only one saved account after the 7th of November (set window.tutao.locator.Const.CURRENT_DATE or adapt system time to test this)
* [ ] tuta.com does not show the banner if the tab was opened by calling window.open() (like after clicking the banner on tutanota.com). check with window.opener != null
* [ ] the signup link on tutanota.com opens tuta.com/signup
* [ ] directly opening /signup on tutanota.com redirects to tuta.com/signup and all query parameters are applied (campaigns, probably gift cards)
* [ ] the banner is never shown on whitelabel domains
* [ ] using whitelabel with a CNAME entry pointing to login.tutanota.com and to login.tuta.com works

## Regression Tests
* [ ] credit card payment works on tuta.com and on tutanota.com for all clients and on whitelabel
* [ ] paypal payment works in browser and on mobile
* [ ] signup on tuta.com works
* [ ] you can still build & debug the android development app
* [ ] you can still build & debug the ios development app
* [ ] you can still upload and download attachments

### iframes
Experiments with iframes in firefox show that we sadly can't access localstorage inside a child context (iframe on origin A inside origin B with A != B) that was created on the same origin A while being a top-level context, even if all permissions and csp headers are set.

* especially firefox has a problem with this for good reasons (to prevent cross-domain tracking).
* safari probably also won't allow this
* firefox partitions origin state by the top-level origin and the current context's origin. if they differ too much, access will be partitioned and the child gets an empty storage.
* origin consists of scheme, hostname, port
* firefox will allow the access if the origin is similar enough (ex. mail.tutanota.com to app.tutanota.com), but because we move from tutanota.com to tuta.com, we're partitioned.
* the previous restriction is relaxed in chromium-based browsers, they would allow that cross-origin access.
* https://developer.mozilla.org/en-US/docs/Web/Privacy/State_Partitioning

### ServiceWorker
due to the service worker, we expect some people to have mismatched application versions on app.tuta.com and mail.tutanota.com - this is problematic if the old version on mail.tutanota.com does not know about mail.tutanota.com/migrate.

this is only a problem for people that
* use the web app by directly going to mail.tutanota.com
* have credentials stored there
* then, after this is released, directly visit app.tuta.com
* then click the banner.

we will keep the login button pointing to mail.tutanota.com/login for a while so people get the new version on the old domain and don't want to show the banner right away, 
rather wait for a few days.

**Comment by wrdhub** [comment]
The only two items I ran into issues with were the "no banner shown when opening when calling window.open()" (was not true on any platform) and "signup on tutanota.com redirects to tuta.com/signup and all query parameters are applied" (parameters are not applied). But I may have been doing something wrong
