### ISSUE TITLE
Second factor login on new login domain

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#5638]
As a user with a second factor for [mail.tutanota.com](http://mail.tutanota.com/), I want to know how I can use it for [tuta.com](http://tuta.com/) in the future so I can migrate fully to the new domain and not worry about the old one disappearing.

## AC
* When I log in on app.tuta.com and there are no second factors for tuta.com, a message is shown (with a link) that the login must be done on the mail.tutanota.com or confirmed on another device
*  if the user has a totp, we just show the code input and a message that the hardware key is not registered for this domain
*  After I log in on app.tuta.com and there are no hardware second factors for tuta.com but hardware second factors for mail.tutanota.com, a message is shown (how?) that the key must be added to this domain.
* for this message, totp is ignored

## Tasks
 - [x] Check if the existing message about second factor domains fits and adjust if it doesn't
 - [x] Implement post-login check for U2F keys for the new domain
 - [x] Make sure that apps also pick the right domain or show the message
   - [x] desktop
   - [x] android
   - [x] ios

## Test Notes
- [ ] Have a key on old domain, try to log in on new domain
    - [ ] Login works on mobile apps and desktop
    - [ ] Web will show dialog with instructions
- [ ] Have a key on new domain, try to log in on old domain. It does not work. 
- [ ] If you have keys for both old and new domain, they new domain is preferred. (Log in on app and check the url that is brought up during the 2fa dialog.)
- [ ] Whitelabel logins still work for web and mobile apps.
- [ ] When sharing giftcard, url has correct domain. Check web and at least one mobile app.
- [ ] Refer a friend link has correct domain. Check web and at least one mobile app.

**Comment by ganthern** [comment]
when you have stored credentials on whitelabel and try to log in on the old domain, it will use the existing credentials once you click the link to your whitelabel domain. should be fine I guess?

**Comment by ganthern** [comment]
when you have (different) keys for the new and old domain, the app does not prefer the new key, we had to use the old one to log in.

**Comment by charlag** [comment]
> when you have stored credentials on whitelabel and try to log in on the old domain, it will use the existing credentials once you click the link to your whitelabel domain. should be fine I guess? It's using the autoLogin though, so you might end up in another account than you tried to log in for a bit.

it was always like that, we could add `noAutoLogin`  there if we want?



> when you have (different) keys for the new and old domain, the app does not prefer the new key, we had to use the old one to log in.

it should be a quick fix but we could also fix it later?
