### ISSUE TITLE
Handle arbitrary alarm durations

### ISSUE THREAD

**Issue by vitoreiji** [tutao/tutanota#5711]
As a calendar user, I would like to be able to see my alarms with the correct time, regardless of what duration it is, so I'm not confused by some arbitrary default value.

## AC
- Events that contain alarm triggers that do not correspond to an enum value will fire alarm at the configured time
- In the event editor, it is not possible to set these alarms, but they're displayed and can be cancelled/removed
- The list of alarms on the event is displayed in a human-readable and localized way (5 Stunden instead of 5H)
- only allow single-unit triggers and extend our custom syntax
- incoming triggers with multiple units are converted to the smallest unit they contain (round seconds up to the next full minute)

support weeks, days, hours, minutes.

## Tasks
- [x] Accept arbitrary value when displaying set alarms (probably just the syntax as defined by iCal)
- [x] Format alarm time in a readable and localized way
- [x] Ensure that alarm is still triggered at the right time
   - [x] android
   - [x] ios
   - [x] desktop client
   - [x] web client

## Notes
Example how to convert incoming trigers

-P1DT5M would be 24 * 60 Minutes + 5 Minutes = 1445M

## Test Notes
Test on desktop, web, android, ios:
- [ ] Adding an alarm to a calendar event works (is displayed correctly, bell is on event, is still there when event editor is reopened)
- [ ] Alarm triggers at the correct time

Does not need to be tested on all platforms:
- [ ] Importing an event with an alarm works as expected (alarm is on the event, triggers at the correct time)
- [ ] Importing an event with multiple time units on the trigger resolves to the smallest unit given (1DT30M = 1470 minutes, 2W1D = 15 days, etc...) and that value is displayed in the reminder time
- [ ] The minutes/days/weeks label matches the user's chosen language (Minuten/Tage/Wochen in German, for example)

**Comment by ganthern** [comment]
wip branch: arbitrary-alarm-triggers-5711
