### ISSUE TITLE
Flexible reminder times

### ISSUE THREAD

**Issue by vitoreiji** [tutao/tutanota#5712]
As a calendar user, I would like to be able to set my alarms flexibly exactly as I need them before the event starts so I'm not restricted to a few options that may not be useful to me.

## AC
- the old alarm options are still available as a quick way to set alarms
- there is an option to add a reminder when the event occurs
- there's also an option to add a custom alarm in the event editor
  - this option opens a new dialog with a field for amount of time units and a dropdown to select the time unit (minutes, hours, days, weeks)
  - the amount text field is restricted to non-negative integers (zero is valid)
- alarms are still deduplicated
- the alarms still fire according to the configured trigger

## Release notes
Must be released **after** #5711 to prevent confusion.

## Tasks
 - [x] Add a preconfigured option to show reminder at the time of the event (0 seconds)
   - [x] Have human-readable text for it
   - [x] Test it on all platforms
 - [x] Implement a new dialog for selecting specific amount and unit for reminder trigger
 - [x] Add an option to select custom time
 - [x] Implement deduplication of reminders

## Test Notes
- [ ] Mail Notifications still working 
- [ ] Alarms for events still working
- [ ] The pre defined intervals still there
- [ ] The pre defined intervals work and de-duplicate correctly with the custom ones
- [ ] There is an option for custom interval
- [ ] The custom interval works 
- [ ] Multiples alarms defined while creating the event works
