### ISSUE TITLE
Feature list extension

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#5846]
As a private customer i want to be aware which features are available

### AC
* The family feature is listed for legend and revolutionary plans on the website and within the mobile apps, translation key: pricing.family_label
* An info button is shown next to the feature which provides tooltip information, for legend:  pricing.familyLegend_tooltip, for revolutionary: pricing.familyRevolutionary_tooltip
* Old clients do not throw an error if they fetch a feature which they don't have a translation for.
* Feature list also includes entries for contact list, shared mailboxes, unlimited custom domain addresses

## Tasks
 - [ ] Add new translation keys
 - [ ] Add new features to the list
 - [ ] Check old clients
 - [ ] Check the website

### Notes

The translation keys have already been added to phrase, see  wiki: SW development Home / product team / meeting minutes

### Test notes

- [ ] The new feature list entries are available including tooltips according to the wiki page at
  - [ ] website
  - [ ] signup
  - [ ] upgrade
- [ ] Opening the signup and upgrade in old clients does not show the new new entries

### Release notes

- The website needs to be published before (same branch name)
- The server needs to be updated for translations (same branch name)
