### ISSUE TITLE
Offline usage

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#590]
As a user i want to be able to access my mailbox when there is no internet connection available (e.g. travelling) so that I have access to my emails, contacts and calendar entries that have been accessed before.

After log in to my mailbox i currently have to wait each time in every view until the progress spinner is completed to see the content. I expect that the content that i have accessed before is visible right after login without any larger delays. 

**Acceptance criteria:**
- [x] There is a non blocking indicator that shows the current offline/online/synchronizing state. #3815
- [x] Offline login is possible when credentials are stored locally. #3888 
- [x] Offline access is available on desktop app #3816 
- [x] Offline access is available for Android app #4030 
- [ ] Offline access is available for iOS app https://github.com/tutao/tutanota/issues/4135
- [x] Mail, Mail Body instances that have been accessed by the users or by the search indexer are available. #3813
- [x] All contacts that were available from last online state can be read. #4134 
- [x] All calendar events that were available from last online state can be read. #3699
- [x] Restricted access to settings 
- [x] Offline data is stored encrypted
- [x] Deletion of offline data #3812

**Technical tasks**
- [x] #4501
- [x] Create proposal for offline database to store data encrypted #3816
- [x] #3823

**Implementation hints**
For detailed description and discussion see the wiki page for offline storage (/pages/viewpage.action?pageId=38898504 )

**Comment by huzzam** [comment]
yes please, this is the number one roadblock for me using Tutanota primarily. I write and respond to emails while offline & away from internet, and need the ability to queue outoging messages & download my inbox.

**Comment by CodingEagle02** [comment]
> 
> 
> yes please, this is the number one roadblock for me using Tutanota primarily. I write and respond to emails while offline & away from internet, and need the ability to queue outoging messages & download my inbox.

Yup. I really, really want to switch to Tutanota, but I can't until I can use it offline.

**Comment by TheCrowned** [comment]
Is there an ETA to this? Similar situation for me: the impossibility of using the Android client offline is kinda of blocking my adoption :(

**Comment by CodingEagle02** [comment]
> 
> 
> Is there an ETA to this? Similar situation for me: the impossibility of using the Android client offline is kinda of blocking my adoption :(

They've [mentioned on Reddit](https://www.reddit.com/r/tutanota/comments/dyiqqr/offline_usage/f81re0n) it's coming within a couple of months.

**Comment by anbecreative** [comment]
Any news on when we can use this offline? It's the only stopping point from switching.
Thanks.

**Comment by fosres** [comment]
Hello Tutanota

Like many, I am also interested in downloading my inbox messages so I can read them offline and compose email messages offline before sending them later. 

What directories in Tutanota's source code do you recommend we research as we try to add the feature.

**Comment by charlag** [comment]
If you would like to make a prototype, please refer to how we build and use search index and `EntityRestCache`. One could try to save instances to the IndexedDB, apply entity updates to it and retrieve them, just like `EntityRestCache` but on disk

**Comment by mark-franz** [comment]
> 
> 
> > Is there an ETA to this? Similar situation for me: the impossibility of using the Android client offline is kinda of blocking my adoption :(
> 
> They've [mentioned on Reddit](https://www.reddit.com/r/tutanota/comments/dyiqqr/offline_usage/f81re0n) it's coming within a couple of months.

They refer us to the [roadmap](https://tutanota.com/roadmap/), but I cannot see 
- a priorisation of the issues
- any kind of time estimate

So what is "a couple of months" ... ?

**Comment by vitoreiji** [comment]
@mark-franz The roadmap is prioritized, items at the top are top priority. We don't give out time estimates. Please keep the github issues clean by sticking to bug reports and, if you're contributing code, implementation details. Feature requests belong on reddit.

**Comment by mark-franz** [comment]
Thanks @vitoreiji . I can't reply to the [related thread on Reddit ](https://www.reddit.com/r/tutanota/comments/dyiqqr/offline_usage/)since it's been closed.

**Comment by europound** [comment]
entire mailbox with all emails should be downloaded locally and synced
and indexed
every time i have to index when searching

**Comment by runkelstein** [comment]
Yes I also would like to have an offline option. Lets say you internet connection is down but you want to recall and read an e-mail you have received. Or you are on the road and you do not have an internet connection and you want to download your e-mails.

Also it would be nice to have an option to archive read e-mails locally which can then be removed from the servers. For instance that could be resolved with an auto delete option for the server-side storage (e.g. after 1 month), then there would have been enough time to use it with several devices. Having the option to delete remotely but save locally is also something I'd consider a security feature.

**Comment by NotepadPlusUser** [comment]
Offline storage for calendar and mail is a very welcome addition.  Because Tutanota has only been online, I have been very nervous in relying on it.

REQUEST TO STORE EMAIL ATTACHMENTS OFFLINE:  Could I ask that the app provide an option to store email attachments offline as well.  Such attachments may be mission critical when doing business.
 * The default setting must be 'do not store offline'.  Otherwise, if people with small storage on their phones miss the setting, things will eventually go badly wrong.  Some notebooks also have small storage.
