### ISSUE TITLE
Website on new domain

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#5929]
As a user I want to be led to the website tuta.com so that I am aware of that Tutanota will be renamed to Tuta

## AC
 
* The Tutanota domains ([tutanota.com](http://tutanota.com/), [tuta.io](http://tuta.io/), [tutamail.com](http://tutamail.com/), keemail.me, [tutanota.de](http://tutanota.de/), [tutao.de](http://tutao.de/) ) should redirect to [tuta.com](http://tuta.com/) with a permanent redirect
*  [https://tuta.com](http://tuta.com/) shows the website that's currently available at [tutanota.com](http://tutanota.com/)
* there's a note on the page that introduces the change from tutanota to tuta and links to the relevant blog post
* Every site/path from tutanota.com/<path> should be accessible under the new domain tuta.com/<path>
* logging in at mail.tutanota.com with second factors that use https://tutanota.com/u2f-appid.json still works
* all clients can still fetch the support entries
* feature lists still work
* privacy policy can still be fetched by the clients that do

## Notes:

* legacy U2F json should still work
    https://tutanota.com/u2f-appid.json
   * does it work with redirect or do we need to prevent redirect?
* does fetching support entries from client work with redirect?
* absolute links on the website or elsewhere to tutanota.com can be changed later
* TutaDb mr 518
* Website mr 105

## Pre-release task
* [x] put the translation key "nav.domainChange_markdown" on the **website** project on phrase and make sure it works. the markdown will contain a link to a blog post that needs to be added to the link whitelists for the sanitizer.
* [x] confirm with ops that the certificate can be/has been ordered for tuta.com
* [ ] make sure the blog post exists
* [ ] branch `website-on-new-domain-5929` on the backend and  website needs to be merged and released with this

## Tasks
 * [x] Make local setup for redirect and test U2F, feature list, support entries, privacy policy (also check connect-src csp on server & client)
 * [x] Add redirect
 * [x] Add note that tutanota will be renamed to tuta
 * [x] update translation sanitizer to allow tuta.com links (links.ts)
 * [x] update the link whitelist in the whitelist project to allow for tuta.com
 * [x] make sure that the old clients can handle the redirects!
 * [x] change the login/signup links in the header

## Test notes
since we have no test system website, this needs to be tested locally.

* [ ] The U2F, feature list, support entries and privacy policy are pointed to the new domain and works with new and old clients
* [ ] The connect-src csp header is correct
* [ ] any page on the old domain redirects to its counterpart on the new one, maintaining any additional info like params and hash
* [ ] A note above the Header about the domain change is displayed correctly on Desktop and Mobile
* [ ] The link in the note links to a blog post about the domain change
* [ ] Login and signup buttons redirects to the new domain (app.tuta.com)

**Comment by charlag** [comment]
Even with modifying both client and server and overriding DNS I could not test all things locally, especially old clients which connect to tutanota.com no matter what, we would need to put a proxy in front of everything to be able to test it.
