### ISSUE TITLE
Allow creating additional email addresses with new domain

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#5961]
As a user, I want to use the new tuta.com domain for email addresses so i can have a short and easy to remember email address.

## AC:

* during signup, if the selected plan is not Free,  the list of available domains includes "@tuta.com"
* for free accounts, it's shown in the list, but greyed out and with a "Premium" label next to it
* for additional email addresses, it's only available for new plan customers
* legacy customers get an upgrade dialog if they try to select it
* when signup with tuta.com domain is not completed the account should not be able to send and receive emails until the account is paid.
* free accounts with a tuta.com signup address get a "complete your signup" popup after login instead of the "sending & receiving disabled" one.
* tuta.com is handled as tutanota email domain.
* important email addresses of tuta.com (e.g. postmaster,@ hostmaster@) are assigned to our tutao.de admin user

## Tasks
* [x] add the domain @tuta.com to the server side
  * mta-sts list
  * DNS
  * draft facade
  * (there may be more)
* [x] create the marked list item for @tuta.com on free signup. use a star icon.
* [x] make a dialog pop up if @tuta.com is selected during free signup that explains that this domain is not available for free.
  * if accepted, go back to plan selector
  * if declined, select select previous domain value
* [x] add @tuta.com to the available extra mail address domains for paid new plans
* [x] in the extra mail address selector for legacy paid accounts, mark the tuta.com domain similarly to the free signup. show upgrade wizard if selected.
* [x] change the default to @tuta.com for all signups that have it available
* [x] create @tuta.com accounts with the "paid subscription needed" approval status. change to "approved" once payment is set up.
* [x] during login, check approval status: if it's paid subscription needed, show dialog with the "finish your signup" text, otherwise act as if account is not approved yet for sending & receiving. (current dialog for this case may already be enough for this)
* [ ] sysops: register important addresses of the new domain for our tutao.de admin user as aliases

## Test Notes
Signup
- [ ] Free signup is not allowed to create account with tuta.com domain
- [ ] Free signup can create account with any other domain
- [ ] When doing a free signup, tutanota.com is the default selected domain
- [ ] When trying free signup with tuta.com, a pop up informs of needing paid account and asks user if they want to switch
- [ ] When doing a premium signup, tuta.com is the default selected domain
- [ ] Premium signup can create an account with tuta.com domain
- [ ] Premium signup can create an account with any other domain
- [ ] When creating a premium account with tuta.com address, if there is an issue with payment:
    - [ ] The account is created
    - [ ] The account is locked with "Paid subscription needed" status, a popup will show informing the user
    - [ ] Once the user has updated with working payment, the account can send and receive emails
- [ ] A user can signup for a tuta.com address with a paid account, then downgrade to free and the account will still work
Additional Email Addresses
- [ ] When trying to add an email with a free account, a popup asking to upgrade is shown
- [ ] When trying to add an email with tuta.com domain on a legacy paid account, a popup informing the user that a new paid subscription is needed is shown and when the user confirms, an upgrade dialog is shown
- [ ] When trying to add a non-tuta.com email on a legacy paid account, it works with no pop-ups
- [ ] When trying to add an email with tuta.com domain on a paid account, it works with no pop-ups
- [ ] When trying to add a non-tuta.com email on a paid account, it works with no pop-ups
Additional Users
- [ ] When trying to add a user with tuta.com domain on a legacy paid account, a popup informing the user that a new paid subscription is needed is shown and when the user confirms, an upgrade dialog is shown
- [ ] When trying to add a user with non-tuta.com domain on a legacy paid account, it works with no pop-ups
- [ ] When trying to add a user with tuta.com domain on a paid account, it works with no pop-ups
- [ ] When trying to add a user non-tuta.com domain on a paid account, it works with no pop-ups
More
- [ ] Accounts with tuta.com domain can receive emails from external providers
- [ ] Can send to external mailboxes with tuta.com address

## Pre-release tasks
- [ ] Test that accounts with tuta.com domain can receive emails from external providers
- [ ] Can send to external mailboxes with tuta.com address
- [ ] Check that mta-sts records are correct for tuta.com
- [ ] Check that mta-sts records are still correct for the old domains (at least one)
