### ISSUE TITLE
Free account with tuta.com

### ISSUE THREAD

**Issue by murilopereirame** [tutao/tutanota#6073]
**Describe the bug**
I can create a free account with @tuta.com if I first select a paid plan then go back when I reach the payment step.

**To Reproduce**
1. Go to Sign Up
2. Select any paid plan
3. Enter your email address with the tuta.com selected as default
4. Proceed to the next step
5. When on the payment step, hit back until the select plan step
6. Select the free plan
7. Finish creating the account

**Expected behavior**
The user isn't able to change to a free plan after creating an account with tuta.com while in signup page

## Task
- [ ] Show error dialog  on the second page saying that tuta.com domains are not allowed for free accounts. Navigate back to plan selection afterwards.

## Test notes
- [ ] Create a paid account with tuta.com domain, after account creation go back to plan selection. See that "free" plan is no longer an option.
- [ ] Create a paid account with tutanota.com domain, after account creation go back to plan selection. See that "free" plan is an option.
- [ ] On an existing account, try to change the plan. All options should be visible and plan change is possible.
