### ISSUE TITLE
Add day selector for day and agenda view

### ISSUE THREAD

**Issue by murilopereirame** [tutao/tutanota#6099]
## AC

A day selector appears for day and agenda view

- First row shows weekday name. 
- Week starts on monday or sunday depending on the setting.
- Day of the month number appears below the week day name.
- A dot should appear below the day of the month number to indicate that there is at least one event on that day
- Left/right swipe gesture changes the week
- When the week changes the selected day changes to the same week day of that week.

## Tasks

- [x] Show weekday name on first row
- [x] Week starts on correct day (this is a user setting)
- [x] swiping left or right changes the week (look into possibly adding buttons, so the week can be changed with a click)
- [x] When the week changes, the selected day changes to the same day of the week
- [x] Single dot indicator below days with at least one event 
- [x] Day selector can be extended to month selector
- [x] Smaller circle for the selected day
- [x] Try to adapt colors closer to the mockup
- [ ] Adapt the weekdays background in month and week view and use just one char

## Test Notes:
these are on the calendar navigation improvement issue
