### ISSUE TITLE
Change name from Tutanota to Tuta Mail in the translations

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#6113]
As a user I want to see the new name in every text in the application and on the website.

### AC
* The name "Tutanota" is not used in texts any more on website and application. Instead it is "Tuta Mail".

### Tasks
* [x] Download all translations from Phrase for clients.
* [x] Search and replace the name for clients.
* [x] Upload all translation to Phrase again for clients.
* [x] Update translations for clients.
* [x] Update translations for the server.
* [ ] Download all translations from Phrase for website.
* [ ] Search and replace the name for website.
* [ ] Upload all translation to Phrase again for website.
* [ ] Update translations for website.

**Comment by armhub** [comment]
Server branch: update-translations-41
