### ISSUE TITLE
New credentials system for apps

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#6153]
As a user of the desktop or mobile app i want that data is stored locally by default so i have full advantage of the desktop client (search index, offline storage, notifications) when i add my account credentials.

## AC
* The "login in" button should change to "Add account"
* There is a hint below the "Add account" button: "Data will be stored on your device"
* There is no option to "save credentials" on the login screen anymore for mobile and desktop apps.
* When adding an account these features should be enabled:
   * Search index
   * Offline storage
   * Push notifications
* "Delete credentials" should be renamed to "Remove account"
* When removing the account credentials the data should be removed
   * Search index
   * Offline db
   * Push identifier
   * Scheduled alarms
   * External image rules.
* When removing the account the client should stop receiving push notifications for this account.
* "Log out" action should be renamed to "Switch account"
* Web application maintains the existing "Store credentials" mechanism.
* local password changes should not invalidate any of the local data (we should get a new session immediately)
* remote password changes still work as they do now (offline login, then password prompt if session expired)

##  Tasks
 - [x] Change login screen for apps+desktop (labels, checkbox,  remove account)
 - [x] Enable mail search index automatically
 - [x] Credentials deletion cleanup:
   - [x] Search index
   - [x] Alarms
   - [x] Push identifier
   - [x] Image rules
   - [x] Remove push identifier on the server as well
 - [x] Change log out button for apps+desktop
 - [x] Make sure local password changes do not invalidate data
 - [x] Make sure remote password changes are still handled correctly

## Test notes
 - [ ] Translations are correct for both browser and apps
 - [ ] Verify that when an account is added the search index is enabled automatically
 - [ ] Verify that it is not enabled automatically in browser
 - [ ] Verify that when deleting account in apps:
   - [ ] Push notifications are not received anymore
   - [ ] Search index db and config db are removed from local storage (check with devtools on desktop)
   - [ ] Check in push identifier list in Mail settings that the push identifier for that device was automatically removed
   - [ ] Check that no alarms are fired for that user
 - [ ] Check that after adding an account push notifications are still received
 - [ ] Try disabling and enabling search index manually
 - [ ] Try local password change, verify that credentials still work
 - [ ] Try remote password change and then login in app with premium account. You should see a prompt and the app should work after the new password was given, even after relogin. All the data should persist.
 - [ ] Try remote password change and then login in the app with free account. The login should fail on the login screen, all the data will be gone.

**Comment by ganthern** [comment]
> Try disabling and enabling search index manually

what's the desired behaviour here? the dropdown is enabled, but choosing "disabled" for the search index doesn't change the setting.

**Comment by charlag** [comment]
I think it should change to disabled?

**Comment by pesaro66** [comment]
I am a normal user, not a developer: sorry if I make a mistake when writing here.
What I wanted to ask is to remove this change and return to the old option of letting the user save credentials locally. We have explained the reasons for this in the forum [((https://www.reddit.com/r/tutanota/comments/1ahgyj4/comment/kp8obt3]) and [).](https://www.reddit.com/r/tutanota/comments/1aleaqu/about_the_automatic_saving_of_credentials) As you can read, we do not like this new function, we do not find it useful, in fact we find it harmful.
Of course, ours is an opinion, but of users who have praised this new function, I have frankly seen very few. So what I ask of the developers and staff of Tutanota is to seriously evaluate this request of mine. As far as I am concerned, if you put the automatic saving of credentials also in the access from the web portal, I will be forced, against my will, to stop using Tutanota, which I had chosen for the maniacal care of privacy protection.
Thank you very much.
