### ISSUE TITLE
Adapt calendar navigation improvements for larger screens

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#6253]
As a user i want that the calendar navigation improvements for the single column layout also apply to two and three column layout so i can benefit from the improved navigation and have a unified look and feel.

## AC
* The day selector appears in the left column to select day/week/month of my current view (mini calendar in left column)
* The toolbar appears for the calendar view similar to what we have in Mail and Contact views to separate actions and content.
* Content of the calendar should look like a card.
* The calendar view selector is available in the toolbar (either as dropdown or as  segment control)
* "Today" action appears in the toolbar
* The agenda view only shows events for the selected day and uses two column layout in the content area. First column shows the agenda list, second column displays the event details.

## Tasks  
- [x] prepare mockups

- [x] Implement changes
  - [x] Add the mini calendar to the left column
  - [x] Changing the months in mini calendar doesn't change the current view date
  - [x] Add the toolbar similar to what we have implemented already
  - [x] Use the card style to calendar views
  - [x] Move the today button and the view selector to the toolbar
  - [x] Implement event details in agenda view
     - [x] Use two columns layout
     - [x] Left column should include events for that day
     - [x] Right column shows the details of the selected event
     - [x] If there is no selected event, shows just a message to select an event

### Three columns layout
* [ ] The first column contains a day selector in all calendar views
* [ ] The day selector doesn't appear in the sidebar on single/two columns layouts
* [ ] You can swipe the day selector
* [ ] When you change the months in day selector, nothing happens with the current selected date
* [ ] When you select a date it changes the current selected date in the current view
* [ ] A toolbar is visible above the calendar view
* [ ] The toolbar contains the today button and a segment control to select the view type
* [ ] The calendar content uses the card style
* [ ] Agenda only show events to the selected date
* [ ] There's a place to show the events details while in agenda view
* [ ] If no event is selected, there is an icon with a message informing the user
* [ ] When you click on an event while in the agenda view, you can view the event details in the right

### Regressive (One/Two columns layout)
* [ ] The day selector is expandable while in one column layout
* [ ] The day selector appears as a popup while in two columns layout
* [ ] You can swipe weeks/months in the day selector
* [ ] Updates/deletes realized in another or the same window reflects at the current selected event

**Comment by ganthern** [comment]
Week and day view don't seem to be using the card style in the desktop layout:
![image](https://github.com/tutao/tutanota/assets/29049728/534e3f0f-1194-4bef-b803-71725fdfe195)
![image](https://github.com/tutao/tutanota/assets/29049728/c8485469-9be8-4499-8701-ce8b28179caa)
