### ISSUE TITLE
Allow swipe gesture in agenda view

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#6282]
When i am in the agenda view on mobile device i want to be able to switch the day using a swipe gesture so i can navigate back and forth.

### AC

* Swipe on the content area changes the day the same way as in the day view.

### Tasks
- [x] Implement the swipe gesture on the agenda view same as the month view etc.

### Test Notes
- [ ] The Agenda View show events for today
- [ ] The user can swipe left/right and see a preview of next/previous day respectively
- [ ] If the user concludes the swipe left/right action, the next/previous day should be displayed
- [ ] The date must change on day selector if the swipe action is concluded
- [ ] Changes on day selector must be reflected at the event list
- [ ] There's no changes to the desktop version
