### ISSUE TITLE
Add time indicator to agenda view

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#6284]
When i am viewing the agenda view of the current day i like to have a current time indicator so that i can identify which of the events are still relevant for that day.

### AC
* Time indicator appears for the current day as a red line (similar to day and week view)
* Finished and started events are shown above the time indicator
* Upcoming events are shown below the time indicator
* All day events are always shown above time indicator

### Tasks
- [x] Add a red line to the events list in the Agenda View
- [x] Position the red line on top of the next occurring event, below the last occurring event
- [x] Ensure all day events remain on top of the red line
- [x] Update the position of the red line as time progresses

### Test notes
**Note: Begin this test on a user that currently has no events for today.**
- [ ] Create a few calendar events that are on the current date:
    - [ ] Make one an all-day event
    - [ ] Make one in the past
    - [ ] Make one two (2) minutes into the future
    - [ ] Make one four (4) minutes into the future
- [ ] Verify the time indicator appears above the event that is five minutes into the future
- [ ] Wait two (2) minutes on this screen, and verify that, once the event time has been reached, the time indicator has moved to the one that was four minutes into the future (now two minutes)
- [ ] Wait two (2) minutes on this screen, and verify that, once the event time has been reached, the time indicator is no longer present
- [ ] Create a calendar event that isn't all-day for tomorrow (if one is not present), and verify no time indicator shows up for that day in the agenda view
- [ ] Go back to today and create an event that is one hour into the future.
    - [ ] View it in the light theme and verify the time indicator is red
    - [ ] View it in the dark theme and verify the time indicator is cyan
    - [ ] View it in the blue theme and verify the time indicator is blue
- [ ] Check that column sized didn't change
- [ ] Check that aria labels (via dev toolsl) and titles of the columns (visible on mobile) didn't change
