### ISSUE TITLE
Tuta contacts in calls and messages

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#6374]
As a user of the tuta app I want my tuta contacts to be available in other apps like calls, messages, so i can use tuta as my main contact management tool.

### AC:
* If a call from a number stored on a tuta contact is incoming, that contacts data is available on the call screen
* If you make a call and type a number, matching tuta contacts should be suggested
* tuta contacts show up in other apps that use system contacts on android and ios
* enabling this feature is a reversible user decision (for each user)
* the contacts sync at least after opening the app and logging in
* If you remove an account from tuta app it should remove all associated contacts from contact book
* The following attributes should be supported and mapped to the native attributes as closely as possible:
  * Display name
  * Nickname
  * ~Title~
  * Company
  * ~Role~
  * ~Comment~ 
  * Birthday
  * Email (with type)
  * Phone number (with type)
  * Address (with type) 

### Tasks

- [x] https://github.com/tutao/tutanota/issues/6382
- [x] https://github.com/tutao/tutanota/issues/6383
- [x] https://github.com/tutao/tutanota/issues/6384
- [x] cleanup code and merge

### Notes:
* We do not want to manage all contacts on the system from tuta.
* We also don't want to see other system contacts in our contact list
* if possible, only use our own contact editor for editing tuta contacts

### Test Notes
- [ ] There's a new settings section to contacts
- [ ] The user can enable/disable the contact synchronization there
- [ ] When deleting an account, the contacts are removed from the phone's book
- [ ] When enabling synchronization:
  - [ ] If the user doesn't give contacts permission, no error is thrown
  - [ ] If the user give contacts permission, Tuta contacts are synchronized right away
- [ ] With synchronization enabled:
   - [ ] Tuta contacts are synchronized to the phone's contact book at the moment that the sync is enabled and after login
   - [ ] Tuta contacts are synchronized after creating/editing/deleting a contact
   - [ ] Tuta contacts are synchronized after receiving an contact update from other client
   - [ ] Tuta contacts overwrite any changes made on the phone's contact book
   - [ ] The following fields receives updates from Tuta:
      - Display name
      - Nickname
      - Company
      - Birthday
      - Email (with type)
      - Phone number (with type)
      - Address (with type) 
    - [ ] If Contacts permission is removed, no error is thrown and the preference is disabled
- [ ] With synchronization disabled:
   - [ ]  No Tuta contact is synchronized with the phone's contact book
   - [ ] Previous synchronized contacts are deleted

**Comment by B3K-me** [comment]
Great to see this on the roadmap.  This is the one issue keeping me from subscribing to Tuta.
