### ISSUE TITLE
Onboarding flow to configure tuta app

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#6462]
As a user i want to have a guided setup of the app so i benefit from all the features that the app provides

### AC
* A wizard dialog shows up after the first login to configure the app behavior.
* Page 1 should show a congrats/welcome message
* Page 2 should allow configuring notification behavior, including
   * Enabling push notification
   * Battery optimizations (only Android)
* Page 3 allows configuring the theme behavior (light/dark/system/custom)
* Page 4 allows enabling contact synchronization/ initial import
* Page 5 allows configuring App lock behavior.
* The user should be able to skip the dialog at any time.
* The option that are provided in the tour are configurable in the settings in its own section.
* When asking for system permission it should be initiated by a user interaction (button press)

### Notes:

We should look at other onboarding flows and decide if multiple pages is the best way to guide the user.
We like to first have design proposal that shows all the pages of the flow.

## Tasks
  - [x] Implement design proposal
  - [x] Create new wizard
  - [x] Implement notifications page
    - [x] Android
    - [x] iOS
  - [x] Contacts page
  - [x] Themes page
  - [x] App lock page
  - [x] Review design proposal and apply changes
  - [x] Adjust permission dialogs on startup

## Test Notes
- [ ] On Android
  - [ ] The app does not display the OS permission dialog after first sign in
  - [ ] The onboarding wizard appears after first sign in
  - [ ] The onboarding wizard does not appear after subsequent sign ins
  - [ ] Pressing the 'cancel' button skips the wizard
  - [ ] The 'Notifications' page appears if the notification permission is not granted
  - [ ] The 'Notifications' page does not appear if the notification permission is already granted
  - [ ] The 'Grant Permission' buttons on the 'Notifications' page:
    - [ ] have the label 'Granted' if the permission is already given
    - [ ] do not have the label 'Granted' if the permission is not given
    - [ ] have the label 'Granted' if the permission is given when switching apps to the settings app, enabling the permission then switching back to the Tuta mail app
    - [ ] display a dialog message if clicked on when the permission is manually disabled in the OS's settings
  - [ ] The radio buttons on the 'Appearance' page changes the apps theme when pressed
  - [ ] The 'Import' button on the 'Contacts' page of the wizard opens the import contacts dialog
  - [ ] The Activate button on the 'Contacts' page:
    - [ ] has the label 'Activate' if contact synchronization is disabled
    - [ ] has the label 'Activated' if contact synchronization is enabled
  - [ ] The radio buttons on the 'Unlock method' page changes the app lock method after pressing finish
  - [ ] Pressing on a breadcrumb with a tick takes the wizard back to that page
  - [ ] Each page has a good layout in portrait view
  - [ ] Each page has a good layout in landscape view
- [ ] On iOS
   - [ ] The app does not display the OS permission dialog after first sign in
    - [ ] The onboarding wizard appears after first sign in
    - [ ] The onboarding wizard does not appear after subsequent sign ins
    - [ ] Pressing the 'cancel' button skips the wizard
    - [ ] The 'Notifications' page appears if either the notification or the battery optimization permission is not granted
    - [ ] The 'Notifications' page does not appear if both the notification or the battery optimization permission is already granted
    - [ ] The 'Grant Permission' buttons on the 'Notifications' page:
      - [ ] have the label 'Granted' if the permission is already given
      - [ ] do not have the label 'Granted' if the permission is not given
      - [ ] have the label 'Granted' if the permission is given when switching apps to the settings app, enabling the permission then switching back to the Tuta mail app
      - [ ] display a dialog message if clicked on when the permission is manually disabled in the OS's settings
    - [ ] The radio buttons on the 'Appearance' page changes the apps theme when pressed
    - [ ] The 'Import' button on the 'Contacts' page of the wizard opens the import contacts dialog
    - [ ] The Activate button on the 'Contacts' page:
      - [ ] has the label 'Activate' if contact synchronization is disabled
      - [ ] has the label 'Activated' if contact synchronization is enabled
    - [ ] The radio buttons on the 'Unlock method' page changes the app lock method after pressing finish
    - [ ] Pressing on a breadcrumb with a tick takes the wizard back to that page
    - [ ] Each page has a good layout in portrait view
    - [ ] Each page has a good layout in landscape view
- [ ] On desktop
  - [ ] The onboarding wizard does not appear
  - [ ] The account sign up page looks good
- [ ] On Web
  - [ ] The onboarding wizard does not appear
  - [ ] The web app asks for permission to send notifications after first sign in
  - [ ] The redeem giftcard wizard looks good
  - [ ] The add domain wizard looks good

**Comment by murilopereirame** [comment]
1. [Android] The battery permission is disabled as granted even with the battery restriction turned on
2. On landscape mode, the next button may need a bit of spacing from the bottom
![Screenshot_20240314-131325](https://github.com/tutao/tutanota/assets/34790144/f7f86b05-fcba-4f86-a4d0-0f873fce757e)

**Comment by charlag** [comment]
I already noted https://github.com/tutao/tutanota/issues/6712

**Comment by rezbyte** [comment]
>     2. On landscape mode, the next button may need a bit of spacing from the bottom

Thanks for testing the onboarding flow. I will fix this today.
