### ISSUE TITLE
Update tuta contact when contact is changed on the device

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#6468]
When editing a tuta contact on my phone using a different app (e.g. phone app) i want  changes to be applied to the contact stored in tuta so i don't need to open the tuta app to modify the contact.

## AC
* After the contact is edited on my device the changes are applied to tuta contact when I log into the app
* If the native contact was changed all fields that are synchronized to the native phone book will be overwritten with the native changes
* When there are server and native changes we always take the native state.

## Tasks
- [ ] Implement SyncAdapter to sync existing data
- [ ] Apply user's local changes to Tuta

## Notes
 - We probably can make use of existing sync data for Android, see https://developer.android.com/guide/topics/providers/contacts-provider#ContactsProviderMetadata see https://developer.android.com/guide/topics/providers/contacts-provider#SyncAdapters
 - It doesn't seem like we have the last update time for the contact on the server, we might need to keep track of that locally with entity updates or add some metadata to the contact entity on the server

## Test Notes
- [ ] Initial Sync:
    - Create a new contact on the device through native Contacts app;
    - Open the Tuta app;
    - Verify that the contact appears in the app's contact list;
    - Edit the contact on the app;
    - [ ] The changes are applied to the native contact.

- [ ] Sync native changes:
    - Modify an existing contact on the device through native Contacts app;
    - Restart the Tuta app;
    - [ ] The changes were synchronized across all clients.

- [ ] Sync server changes:
    - Update a contact on another client;
    - Wait for the entity update;
    - [ ] The Android app contains the latest contact data;
    - [ ] The native contact contains the latest contact data. 

- [ ] Delete Contact:
    - Close the app and delete a contact from through the native Contacts app;
    - Open the app again;
    - [ ] The changes were synchronized;
    - On Tuta App delete a contact;
    - [ ] The native contact were deleted.

- [ ] Conflict Resolution:
    - Edit the native contact;
    - Edit the same contact in another Tuta client;
    - Start the Android app;
    - [ ] The native changes were applied and the server ones are discarded.

- [ ] Batch Operations:
   - Close the Android app; 
   - Change more than one contact and property on native contacts;
   - Change more than one contact and property on another client;
   - Create a contact on the native side;
   - Create a contact on another client;
   - [ ] Check that all changes were applied according with the previous definitions (Native changes overwrite server ones)
   
- [ ] Network Interruption:
    - With a premium user, login and sync contacts;
    - Close the app and turn off the internet;
    - Edit one contact on the native side;
    - Edit the same contact on another client;
    - Edit a different contact on the native side;
    - Edit a different contact from the previous two on another client;
    - [ ] Open the app, no changes were applied;
    - [ ] Turn on the internet, see the changes being applied according to the previous definitions.

### Documentation
MR #585
