### ISSUE TITLE
Easy contact import via attached/opened vcard file

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#6469]
As a user I want to be able to import contacts sent from other apps and services with a single click.

## AC
 - [x] If contact file is shared from another app I want to be able to choose to import it as a contact rather than using it as an attachment. There should be a preview of contact data.
 - [x] If email has a contact file attached there is indication that it is a contact file and there is a way to trigger preview and import of the contact

## Tasks
 - [x] Add dialog for handling  shared vcf files
 - [x] Add an option to import vcf file attached to an email
 - [x] Add a handler to opening vcf file on Android
 - [x] Add a preview for importing contacts 
 - [x] Check if adding custom action on iOS is a good option
 - [x] Change icon for the contact attachment bubble
 - [x] Polish import dialog flow (preview, import, progress, success)  

## Test Notes
- [ ] Downloading attachments still working
- [ ] Opening attachments still working
- [ ] There's an option to import when the attachment has one of vCard mime types
  - text/x-vcard
  - text/vcard
- [ ] When the attachment has one of vCard mime types, the icon is related to contacts
- [ ] **[1]** When trying to import from attachment:
   - [ ] A preview with the contacts inside the vCard is displayed;
   - [ ] The user can import or cancel from the dialog;
   - [ ] If importing, a loading is displayed and after importing a success message is displayed with the number of contacts imported with success;
   - [ ] If there's any error related to entities, a message with the amount of failed & imported contacts is displayed;
   - [ ] If there's any other type of error, an unexpected error message is displayed.
- On Android:
  - [ ] The user can open a .vcf file from any app, e.g. File Explorer, with Tuta;
  - [ ] When opening a .vcf file, the user see the preview if the contacts;
  - [ ] Continue from [1].
- On Android/iOS
  * [ ] When sharing one or more .vcf files with Tuta, a message is displayed asking if the user wants to import or attach the file;
  * [ ] The user can share more than one file at time and they will be imported together;
  * [ ] If the user include a non-vCard file, the files will be attached and no dialog about import is displayed.

**Comment by paw-hub** [comment]
"If there's any error related to entities, a message with the amount of failed & imported contacts is displayed;" cannot be tested. This can probably be ignored.

"When sharing one or more .vcf files with Tuta, a message is displayed asking if the user wants to import or attach the file;" This works, but attaching the file and saving a draft leads to a BadRequestError.
