### ISSUE TITLE
Tuta uses CTRL instead of Meta/Command on macOS and iOS

### ISSUE THREAD

**Issue by paw-hub** [tutao/tutanota#6503]
On macOS and iOS/iPadOS, we need to swap the ctrl/meta keys so that pressing CMD+S saves drafts.

## AC
- CTRL shortcuts on macOS and iOS/iPadOS work with the command key instead of CTRL.
- Shortcuts are properly displayed with the CMD key instead of CTRL in the help/F1 window.

## Test notes
- [ ] On macOS and iOS (hint: for iOS, use Bluetooth, USB, or iOS Simulator), do the following:
    - [ ] Create a draft and press F1. Verify that saving is displayed as CMD+S, not CTRL+S.
    - [ ] Press CMD+S and verify that it saves the draft.
    - [ ] Close the draft. Press Shift+CMD+L and verify it takes you to the login screen.
- [ ] On something that is not macOS or iOS, make sure CTRL still works as expected.
