### ISSUE TITLE
Selection behavior after processing an email.

### ISSUE THREAD

**Issue by wrdhub** [tutao/tutanota#6583]
As a user I want to configure the what is selected/shown after moving the current selection to a different location

AC

- When a single email is viewed and removed from the list as a result of some action (e.g. move operation), the list changes 
  - if the "show older" is used, select the next older email or the last email in the list if there are none
  - if "show newer", select the next newer email or the first email in the list if there are none
  - if "show none" clears the selection, and in single-column mode goes back to the list view
  - if the email was the only email in the list, the focus must shift to the list and no email should be selected
- When multiple emails are selected and removed from the list as a result of an action, the list changes the selection.
  - if the "show older" is used, select the next older email after the oldest in selection or the last email in the list if there are none
  - if "show newer", select the next newer email before the newest in selection or the first email in the list if there are none
  - if "show none" the list clears the selection, and in single-column mode goes back to the list view
  - if no emails are left in the list, the focus must shift to the list and no email should be selected
- The option is configurable per device and the default options are: for mobile apps: "show none", and desktop/web: "show older"

## Tasks
- [x] Add a new config in email section with three options:
  - [x] Show Older
  - [x] Show Newer
  - [x] Show None
- [x] Apply the config to the Mail View list
- [x] Apply the config to the Search View list

## Test Notes
Check this in Mail View and on Mail Search:

- [ ] There's an option in Settings -> Email to select the desired behavior
- With "Show Older" selected:
   - [ ] When the selected email disappears from the list, the first email ABOVE it is selected
   - [ ] When on multi select, the next email ABOVE the first email into the selection list is selected
- With "Show Newer" selected:
   - [ ] When the selected email disappears from the list, the first email BELOW it is selected
   - [ ] When on multi select, the next email BELOW the last email into the selection list is selected
- With "Show None" selected:
    - [ ] No email is selected
