### ISSUE TITLE
Support common contact fields

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#6590]
As a user which maintains contacts on a android or iOS device i want that all native contact fields are available in tuta contacts.

### AC
* Fields that are mentioned below are editable in the app.
* New fields are synchronized with mobile phone books
* New fields are part of the vcard export/import

### Notes

We want to add support for
* [x] Middle names
* [x]  Name prefix/suffix
* [x] Phonetic names (First, Middle, Last)
* [x] More job fields (they have job title, department, and company; we have only company and role)
* [x] Custom dates (more than just birthday)
* [x] Website URLs
* [x] Relationships (i.e. family members)
* [x] IM handles (for us, especially end-to-end encrypted handles, such as Signal and Telegram, which may be nice to have in a Tuta contact, but other providers or even custom ones may be worth implementing as well)
  *  check if we can reuse our social network field.
* [x] Notes (Comments) - already in the model, we need to sync them
* [x] Pronouns (at least iOS)
   *  https://www.iana.org/assignments/vcard-elements/vcard-elements.xhtml

## Tasks
 - [x] Add fields to the model
 - [x] Add fields to the contact editor
 - [x] Add fields to the contact viewer
 - [x] Add fields to vcard export/import
 - [x] Add fields to sync (Android)
 - [x] Add fields to sync (iOS)
 - [x] Add fields to contact import from device

MR 586

## Test Notes
- [ ] The fields described above are added to Contact Editor
- [ ] The fields described above are added to Contact View
- [ ] The fields described above are added to two-way sync on Android and iOS, except:
  - [ ] Pronouns are not synchronized on both platforms
  - [ ] Notes are not synchronized on iOS
- [ ] The user can import a vCard including the following new fields:
  - [ ] Middle Name
  - [ ] Department
  - [ ] Websites
  - [ ] Prefix
  - [ ] Suffix
  - [ ] IMPP (Instant Messenger Handle)
  - [ ] Pronouns
  - [ ] Related (Relationships)
- [ ] The user can export a vCard and it includes the following new fields:
  - [ ] Middle Name
  - [ ] Department
  - [ ] Websites
  - [ ] Prefix
  - [ ] Suffix
- [ ] The user cam import from native contacts and the new fields are imported except:
  - [ ] Pronouns on both platforms
  - [ ] Notes on iOS

**Comment by rezbyte** [comment]
It might be a good idea to use the date picker for the birthday field.

**Comment by rezbyte** [comment]
I am not sure whether this is correct behavior but on iOS when I import a contact, then enable contact synchronization and edit a contact, a new contact is created in the native contacts app instead of the existing one being updated.

**Comment by rezbyte** [comment]
When exporting a vcard containing a 'parent' relation from Android's contacts, the 'parent' is not imported when the vcard is.

**Comment by rezbyte** [comment]
I cannot test whether pronouns in vcards are imported correctly because I cannot find any app that exports them. They are not included in the vcard standard.
