### ISSUE TITLE
Tuta SDK

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#6609]
## Tasks
 - [x] #6610
- [x] address concerns about WASM (alternative compile target via WASM → JS translation)
- [x] ship JS fallback for current WASM crypto primitives #6768 
- [x] **checkpoint**: does JS fallback work?
- [ ] replace all JS crypto primitives currently in use
- [ ] **checkpoint**: does JS fallback work for all primitives?
- [ ] refine the design with crypto team #6687
  - what are the responsibilities of CryptoFacade
  - what code is part of the SDK
  - is SDK stateless?
 - [ ] implement part of SDK without encryption and use it in mobile apps for (limited) notification preview
 - [ ] **checkpoint**: does it work in native (mobile apps)?
 - [ ] implement encryption part of the SDK
 - [ ] use it for full notification preview
 - [ ] **checkpoint**: does encryption as part of SDK work for native?
 - [ ] implement more parts of sdk to completely replace current implementation in the app

**Comment by wrdhub** [comment]
This issue is outdated and doesn't make sense anymore
