### ISSUE TITLE
Add JS fallback for WASM components

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#6768]
Some of our current crypto algorithms are compiled to WASM (argon2, liboqs). This causes issues in environments where WASM is disabled (browsers on iOS with Lockdown Mode, Tor-browser and derivatives in some security settings).

In the future we would like to compile Rust-based SDK to WASM so we will rely on WASM even more.

We would like to allow those special browser cases to still use Tuta.

## Tasks
- Argon2
   - [x] Try wasm-to-JS transpiler manually for one of our WASM libraries
   - [x] Integrate with build system to produce the fallback
   - [x] Implement WASM detection at runtime
   - [x] Load fallback when needed
 - Liboqs
   - [x] Try wasm-to-JS transpiler manually for one of our WASM libraries
   - [x] Integrate with build system to produce the fallback
   - [x] Implement WASM detection at runtime
   - [x] Load fallback when needed

## Test Notes
See #6835
