### ISSUE TITLE
Move setup/onboarding wizard out of "main" chunk

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#6844]
Currently src/gui is meant for general-purpose UI elements.

Onboarding wizard is a component that's specific to non-browser targets. It is also not required for app start.

We should move it to one of the chunks that are loaded later. Normally I would suggest "settings" as a kitchen sink for rarely-used components but this one is specific to native and is probably big enough where it warrants its own chunk e.g. `src/native/main/setupwizard`.

## Tasks
 - [x] Move setup wizard files to their own directory
 - [x] Define a new chunk in `allowedImports()` (no one should be depending on it statically)
 - [x] Define a rule in `getChunkName()` to sort that directory into that chunk

## Test Notes
- [ ] The wizard still being displayed on Android and iOS
- [ ] The wizard still looking good on Android and iOS
- [ ] The wizard chunk isn't loaded on the Browser or Desktop app (setup-wizard-<HASH>.js)
- [ ] The wizard completely works on both Android and iOS

**Comment by mpfau** [comment]
The wizard chunk is loaded on the Browser. Extracted to https://github.com/tutao/tutanota/issues/6894
