### ISSUE TITLE
Avoid duplicated contacts after importing and enabling contact synchronization

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#6875]
As an user I want to have just one instance of each contact inside my native address book after importing them and enabling contact synchronization inside Tuta app.

## AC
* After importing and enabling synchronization there's just one local instance of the imported contacts
* There is only one contact container that we use for synchronisation, the sync container
* The sync container is the local container if present,  otherwise it is the default container.
* Warn users to disable iCloud sync if there's no local address book to prevent contacts from being synchronized between devices
* If user turns on contact synchronization we try to match the contacts in the sync container to prevent the unnecessary creation of contacts (iOS)

## Tasks
 - [x] Add a warning about iCloud when enabling contact sync
 - [x] Add a check and warning about iCloud + contact sync after login
 - [x] Add a function to match existing contact with tuta contacts
 - [x] Take new match function into account to decide whether to create or update the contact

## Notes
 - Check what Gmail is doing. They are moving contacts to their own list.

## Test notes
 - [ ] When iCloud sync for contacts **is not** enabled enabling contact sync just works without a warning
 - [ ] When iCloud sync for contacts **is** enabled there is a dialog warning about the conflicting sync.
   - [ ] The option to go to settings opens the iCloud setting
   - [ ] The option to enable the sync anyway works
   - [ ] The cancel option does not enable sync
- [ ] After importing contacts and enabling contact sync there is a prompt suggesting to remove (old) duplicate contacts
  - [ ] It removes the duplicates and only the duplicates when confirmed
  - [ ] It does nothing when user declines
- [ ] On Android the sync is enabled without a warning and work like before

**Comment by charlag** [comment]
I did a bit of investigation and so far it seems like there's no collision of iCloud container with local contain (that we use now). In the list of containers we don't even see the iCloud one, even thought the iCloud sync is on for contacts. I hope I'm not missing anything.

So I'm not sure if the warning for iCloud is needed or is even possible.

**Comment by charlag** [comment]
This answer implies that local container is CardDAV:
https://stackoverflow.com/a/33510091/1923879

This comment mentions that "local" container is gone but it's possible to have both:
https://stackoverflow.com/questions/34587214/how-to-force-a-new-cncontact-into-a-local-cncontainer#comment121239594_36003934

**Comment by charlag** [comment]
I did check some more and indeed, normally you shouldn't have both containers so I suppose it is possible to check for that.

**Comment by charlag** [comment]
While enabling contact sync we don't have any indication of progress and you can enable the sync twice if it takes a while. We should address it later though.
