### ISSUE TITLE
Notifications don't open the app

### ISSUE THREAD

**Issue by danielhill1982** [tutao/tutanota#6946]
Notifications do not open the app. I have windows 11 pro installed.

**Comment by lalomartins** [comment]
I came here to report this (or at least I believe it's the same issue), so let me add some context.

If I click on the notification pop-up, it **does** open the app (and the message in question).

However, if I miss that short time window and the notification goes to the Windows notification panel (formerly Action Center), it no longer works properly. Clicking a notification there does nothing but dismiss the notification.

This includes non-mail notifications, such as app updates.

I have verified that it is possible for those notifications to do something; some apps do work, in particular Microsoft ones (an easy one to test is Phone Link). But Tuta is not the only app that fails to work, which makes me suspect MS changed the APIs for Windows 11.

**Comment by paw-hub** [comment]
Reproduces on Windows 10, at least as of recently.

**Comment by paw-hub** [comment]
Signal, for example, seems to dodge this by not using Electron's own notifications, instead opting to send a Windows toast notification using https://www.npmjs.com/package/@indutny/simple-windows-notifications?activeTab=readme

**Comment by charlag** [comment]
For context, this is where the issue is described:
https://github.com/electron/electron/issues/24524

It seems like electron itself is aware of it and recommends using libraries for that:
https://github.com/electron/electron/issues/41164

**Comment by charlag** [comment]
## Tasks
 - [x] Review the new library (simple-windows-notifications)
 - [ ] Get the library (simple-windows-notifications) to work with the build system
 - [x] Get the library (simple-windows-notifications) to actually spawn notifications

**Estimated: 24h**

**Comment by paw-hub** [comment]
We reviewed it, and while there isn't anything malicious, there are bugs.

For example, this seems to be wrong:
```c++
static bool are_notifications_supported =
  Windows::Foundation::Metadata::ApiInformation::IsApiContractPresent(
    L"Windows.Foundation.UniversalApiContract", static_cast<uint16_t>(65536));
```

`static_cast<uint16_t>(65536)` will yield 0, since the range of a 16-bit unsigned value is 0 to 65535.

From what it looks like, they probably saw some confusing line like this in the documentation:

```c#
[Windows.Foundation.Metadata.ContractVersion(typeof(Windows.Foundation.FoundationContract), 65536)]
```

However, this 65536 is actually a 32-bit value (0x00010000). It also appears to represent both the major (upper 16 bits) and minor (lower 16 bits), so it's actually 0x0001 (1) and 0x0000 (0) rather than some major version 65536.

As such, it should *actually* be doing this:
```c++
static bool are_notifications_supported =
  Windows::Foundation::Metadata::ApiInformation::IsApiContractPresent(
    L"Windows.Foundation.UniversalApiContract", 1, 0);
```

**Comment by Backspaze** [comment]
I reported this back in 2022 (#4472) and have avoided the notifications since then. Today, I clicked on a notification just to test if it might have been fixed, and to my surprise, it worked! After some digging in the release notes, I found this issue. Nice to see that this has finally been resolved!
