### ISSUE TITLE
Task: Minimal EntityClient in Rust

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#6952]
## AC 

- It is possible to load any Element Types and List Element Types
- It is possible to load entities without encryption
- All required headers and authentication using provided access token are included
- It is possible to handle error responses from the server
- Returned entities are dynamically typed dictionaries
- The unencrypted fields are mapped to logical values (booleans, dates etc.)
- Encrypted fields are preserved with matching type (null/bytes)

## Tasks
- [x] Serialize and deserialise json to dictionaries. (basic instance mapper)
- [x] Allow GET requests for LET and ET types  (without range requests)
- [x] Add required headers (model version, access token, client version )access token are included
- [x] handle error responses
- [x] map values to to types (booleans, dates etc.)
