### ISSUE TITLE
Task: Key resolution in Rust

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#6956]
<p>In order to access encrypted fields of entities we need to be able to decrypt session keys of entities.</p>
  <p><strong>AC</strong></p>

* SDK has internal ability to resolve (decrypt) session keys of entities
* SDK caches group keys in memory

**Tasks**
 - [x] Add `CryptoFacade` which can resolve session keys given entity type and entity data
 - [x] Stub `KeyLoaderFacade` to be able to get group keys
 - [x] Implement `_ownerEncSessionKey` case (symmetric encryption using group keys)
 - [x] Implement resolving session key with bucket key (w/o authentication for now)
     - [x] (this includes Tuta Crypt protocol)
 - [ ] Depends on #7071  

<details>
<summary>outdated</summary>
* SDK has a method to initialize encryption layer
 * it is initialized using access token + session encrypted password

**Notes**

* Look as existing CryptoFacade. We might need to design something similar.
* Try to avoid global state/invalid state. You should only get access to encryption layer after completing initialization.
 ```rust
  impl Sdk {
 
  // ..
 
  // not an actual signature but the idea is that you get a handle to it only after you init session
    async fn init_encryption(
        &self,
        base_sdk_layer: BaseSdk,
        access_token: &str,
        encrypted_password: Vec<u8>
    ) -> Result<EncryptionSdk, SessionError>
}
```
* depends on #6953 
* depends on #6954 
* depends on #6952 
* How do we handle encryption errors in notifications?
  * we fall back to basic notification
</details>
