### ISSUE TITLE
User story: Create base projects

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#6963]
When developing the sdk I want a library project to work on so I can implement the required features

## AC
* There's a minimal cargo project for the Rust part of the SDK
* There's a minimal library project for the Swift part of the SDK
* There's a minimal library project for the Kotlin part of the SDK
* All code resides in our main repository
* The SDK code is separated from the app code
* The final directory structure is agreed upon

## Questions

Should we create a new GitHub project for the SDK, at least for the core part?
-> Put it in the main repo as a first step.

How to structure libraries?:
-> Option 1

Option 1

    sdk
        android-sdk
        ios-sdk
        rust
    app-android
    app-ios

Option 2

    app-android
        app
        sdk
    app-ios
        app
        sdk

## Tasks

- [x] Create minimal cargo project for the Rust part of the SDK
- [x]  Create minimal library project for the Swift part of the SDK
- [x]  Create minimal library project for the Kotlin part of the SDK
- [x] Decide  final directory structure is agreed upon
