### ISSUE TITLE
Configure Binding + FFI

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#6964]
When developing the sdk I want to use the rust code in Swift/Kotlin so I don't have a lot of duplicated code

## AC

- The Rust project can  to generate Swift and Kotlin code
- Bindings are build together with application build
- The generate-bindings command produces the libraries (.so files) and the bindings in Kotlin, Swift and WASM.
- libs are generated for the supported architectures (armv7, x86_64)

## Notes

Q: Should we build the Rust libraries every node make call?

-> Yes

## Tasks

- [x] Generate Swift code to access SDK 
- [x] Generate Kotlin code to access SDK
- [x] Add binding generation to the build process
- [x] Build libs for supported architectures.
