### ISSUE TITLE
Task: decrypting fields

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#7070]
**AC**

 - There is a function inside API to convert between untyped map of encrypted values and typed map of decrypted values given the session key
  - All aggregates are processed
  -  It correctly handles empty/default values

**Tasks**
-   [ ] Create an InstanceCryptoFacade
-   [ ] Create a function to call the CryptoFacade to decrypt fields and InstanceMapper to map them
-   [ ] Deal with empty/default values

 Depends on #6953
