### ISSUE TITLE
Standalone Calendar App

### ISSUE THREAD

**Issue by murilopereirame** [tutao/tutanota#7146]
As a user I want a calendar app without any mail related stuff so I can easily check my calendar

**AC**
- The app shouldn't have
  - Contacts page and native integrations
  - No Mail page, but invites still working
   - No Contacts or Mail search
 - The app should include
   - Calendar search
   - Calendar integrations w/ other modules (contacts and mail)
       - Contact Suggestions for guests
       - Emails for calendar invitation
- Complete login and signup flow

**Tasks**
- [ ] Remove mails page
  - [x] View
  - [ ] Business logic
- [x] Remove contacts page
  - [x] View
  - [x] Business logic
- [x] Update nav bar
- [x] Redirect user to calendar view after login/signup
- [x] Handle contact suggestions when creating a new event
- [x] split files into three folders (mail-app, common, calendar-app)
- [x] Have calendar Android project build with common and calendar-app folders
- [x] #7155

** Test Notes **
This should involve testing of all functionality in both apps (sending mails, making contacts, settings fields, creating calendar events, receiving notifications for mails and events).

Notable things to test are:

- [ ] show welcome dialog works from settings
- [ ] inbox rules still work as expected
- [ ] showing event from event banner in invite works
- [ ] import contacts in mail app still works
    - [ ] trying to import a vcf file into the cal app does nothing
