### ISSUE TITLE
Update Settings for Standalone Calendar App

### ISSUE THREAD

**Issue by murilopereirame** [tutao/tutanota#7147]
Only relevant things to the calendar should be in the settings.

**AC**
The settings should still include:
- Login
- Notification
- Appearance
- Global settings*
- Plans (since one can still sign up with this app)
- Payment
- Referral
- Whitelabel

**Tasks**
- [x] Remove other pages and logic
- [x] In notifications, remove setting about display of mail info
- [x] in global settings, remove mail-related settings

**Test Notes**
- [ ] Global Settings still fully working on both Mail and Calendar App;
  - [ ] There's no Mail related stuff under Global Setting on Calendar App
- [ ] All others settings works as expected;
- [ ] On Calendar:
  - [ ] There's no Contact settings
  - [ ] There's no Mail settings
 - [ ] On Mail:
   - [ ] All settings still available
