### ISSUE TITLE
New App Icon for Android Calendar app

### ISSUE THREAD

**Issue by murilopereirame** [tutao/tutanota#7148]
**AC**
- New icon 
- light and dark theme
- should support monochrome theme

**Tasks**
- [x] Get new icon from design team
- [x] Implement new icon
- [x] Confirm final design

**Test Notes**
- [ ] The icon from Mail app still the same
- [ ] There's a new icon for the calendar app (blue one)
- [ ] On dark mode, the splash screen displays the white icon
- [ ] On light mode, the splash screen displays the blue icon
