### ISSUE TITLE
Calendar-only notifications

### ISSUE THREAD

**Issue by murilopereirame** [tutao/tutanota#7149]
**AC**
- Calendar app should only receive calendar related notifications
- There is a new push identifier for the calendar app

**Tasks**
- [x] Set up a new push identifier
- [x] Make sure tutadb handles the new push identifier

**Test Notes**
- [ ] Calendar app produces a new push identifier different from Mail
- [ ] Preexisting push identifiers still working in the mail app (Just for mail notifications)
- [ ] Calendar app doesn't receive mail notifications
- [ ] Calendar app receives alarm notifications
- [ ] Mail app doesn't receive alarm notifications
- [ ] Mail app receives mail notifications
- [ ] Desktop and web apps still receive all notifications

**Pre-release tasks**
- Merge MR 641
