### ISSUE TITLE
Update onboarding wizard

### ISSUE THREAD

**Issue by murilopereirame** [tutao/tutanota#7150]
**AC**
- All relevant items should still be there
- No mail related stuff
- No contact related stuff
- Notifications still work as expected after completing the wizard

**Task**
- [x] Remove mail related stuff
- [x] Remove sync and import (~~but keep permissions~~)

**Test Notes**
- [ ] The Onboarding wizard still working as before on Mail App
- [ ] The Onboarding wizard doesn't have a Contact import/sync page on Calendar App
- [ ] User should be prompted for Contact Permission when trying to invite someone to an event for the first time.
