### ISSUE TITLE
Actions in notification

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#7157]
When receiving a notification on my device i want to be able to perform actions on the received mail so that i don't have to open tuta app to do that.

## AC
* Delete and mark as read action are available on iOS and Android app
* Delete moves the mail to the trash folder
* Mark as read sets the read status to read
* The notification is dismissed after the action.
* On iOS a long press makes the actions available.
* On Android a chevron makes the actions available.

## Tasks
Once the Depends on tasks are done:
- [x] Android
    - [x] Hook up the functionality so the buttons do the thing 
- [x] iOS
    - [x] Hook up the functionality so the buttons do the thing 

## Depends on
- #6960
- #7653 
- #7654 

## Test notes
- [ ] On desktop, open two email clients: one logged into the account you will send messages with (we'll call this one the sender), and one logged into the account that will receive those messages (we'll call this one the receiver).

On iOS and Android, do the following:
- [ ] Enable notifications permissions if it is not already enabled. (Android should also have battery optimization bypassed.)
- [ ] Sign into the receiver's address.
- [ ] Leave the app.
- [ ] Receive an email from the sender on the receiver. From the notification, delete the email.
- [ ] On the desktop which is logged into the receiver, verify the email was moved to trash.
- [ ] Receive another email from the sender on the receiver. From the notification, mark it as read.
- [ ] On the desktop which is logged into the receiver, verify the email is marked as read.
- [ ] Go back into the app and verify the state on the app matches the state on the desktop.

HINT: To interact with a notification on iOS, you can hold down the notification with your finger for a few seconds for the menu to appear.

**Comment by wrdhub** [comment]
Android works great, iOS has some issues.
