### ISSUE TITLE
Simplified event editor

### ISSUE THREAD

**Issue by andrehgdias** [tutao/tutanota#7205]
**Event editor redesign:** Simplify the event editor so event creation is easier on mobile devices.

**Tasks**
- [x] #7384
- [x] implement the design with new components
    - [x] Title
    - [x] #7912 
      - The mobile apps should use the Button and the desktop/web application should use the input
    - [x] Calendar selection
      - [x] Reduce calendar color to same size as icons (Clock icon specifically)
    - [x] Repeating rules #7905 
    - [x] Reminders #7913 
    - [x] Guests #7904 
    - [x] Location
      - [x] Don't handle location url when editing
    - [x] Description
      - [x]  Handle focus highlight

**Fixes**
- [x] Adjust colors and themes
- [x] Adjust spacing
  - [x] Fix the spacing between title and header (Should be the same as right/left)

**Second Iteration**
- [x] Add line separator to time section
- [x] Increase components interactive area (44px or check w3c accessibility guidelines)
- [x] Change select icon #7907 
- [x] Add click feedback
- [x] Match dropdown width w/ parent
- [x] Change arrow icon to match settings
- [x] Repeat rules
  - [x] Input should select option (Ends section)
 - [x] Guests Page
   - [x] Attending always visible
   - [x] Separate guests with line
   - [x] Remove "Password for ..." label

- [x] #7991
