### ISSUE TITLE
Import ics files on mobile

### ISSUE THREAD

**Issue by murilopereirame** [tutao/tutanota#7214]
As a user, I want to be able to import ICS files on mobile

**AC**
- It's possible to import ICS files when using the Calendar App
- The Calendar app knows how to handle ICS files (Similar with what we do for VCF files)
- The user should be able to select to which calendar they want to import the ICS content
- We show a list similar to contact import with the name and time of events

**Tasks**
- [ ] Enable ics importing on mobile devices
- [ ] Add ics as a supported file type for calendar and mail app
  - [ ] Add calendar selection during import when handling ics files

## Test Notes
- [ ] Downloading attachments still working
- [ ] Opening attachments still working
- [ ] There's an option to import when the attachment has text/calendar as its mime-type
- [ ] When the attachment has text/calendar as mime-type, the icon is related to calendar
- [ ] **[1]** When trying to import from attachment:
   - [ ] A calendar selector is displayed to pick a calendar to insert the events;
   - [ ] A preview with the events inside the file is displayed;
   - [ ] The user can import or cancel from the dialog;
   - [ ] If importing, a loading is displayed;
   - [ ] If there's any error related to entities, a message with the amount of failed events is displayed;
   - [ ] If there's any other type of error, an unexpected error message is displayed.
- On Android:
  - [ ] The user can open a .ics file from any app, e.g. File Explorer, with Tuta Mail/Calendar;
  - [ ] When opening a .ics file, the user see the preview of the events;
  - [ ] Continue from [1].
- On Android/iOS
  * [ ] When sharing one or more .ics files with Tuta, a message is displayed asking if the user wants to import or attach the file;
  * [ ] The user can share more than one file at time and they will be imported together;
  * [ ] If the user include a non-ics file, the files will be attached and no dialog about import is displayed.
