### ISSUE TITLE
Error when clicking on notification on iOS

### ISSUE THREAD

**Issue by paw-hub** [tutao/tutanota#7581]
When clicking on a notification, it should open the mail in question. Instead, an error is received. 

It seems some combination of these factors results in an error when the client does a PUT request - specifically, the receivedDate is wrong.

Steps to reproduce:
1. Enable biometrics and full notifications
2. Receive external insecure email
3. Tap the notification to open
4. Error occurs

Presently, this appears to just affect iOS users, but this will be updated if this is reproducible on Android.

## Tasks
- [x] Create a server-side hotfix and log the timestamps that tried to be written
- [x] Find out the cause of the issue
- [x] Fix the issue
- [ ] After releasing the fix, remove the server-side patch once everyone on iOS has the fix and there are no "Mail::receivedDate tried to be changed" logs

## Test notes
- [ ] Receive a notification with sender/recipient enabled on iOS; verify no error when viewing the mail from tapping the notification
- [ ] Receive a notification with sender/recipient enabled on Android; verify no error when viewing the mail from tapping the notification
- [ ] Verify no "Mail::receivedDate tried to be changed" log appears on the server as a result of testing this.
