### ISSUE TITLE
Improve birthday calendar events

### ISSUE THREAD

**Issue by murilopereirame** [tutao/tutanota#7670]
**AC**
- Birthday event bubbles have gift icon in its title
- The event bubble shows the contact's age.

**Tasks**
- [x] Adapt event bubbles to calculate contact's age
- [x] Modify the event title to contain the gift icon

**Test Notes**
- [x] Contacts with a full date should have their age on the event title
- [x] There's a gift icon on birthday events bubble
