### ISSUE TITLE
Search for birthday events

### ISSUE THREAD

**Issue by murilopereirame** [tutao/tutanota#7671]
**AC**
- Birthday events can be found by using event search
- The birthday calendar is not available as a filter option for free users.
- The result view should present a contact preview.

**Tasks**
- [x] Show the Birthday event in Search Bar overlay
- [x] Make search list Birthday events
- [x] Hide the birthday calendar while on search if the user is Free/Legacy
- [x] When previewing the event, show contact's overview
- [x] When trying to edit the contact, redirects to Tuta Mail
