### ISSUE TITLE
Show contact preview for birthday events

### ISSUE THREAD

**Issue by murilopereirame** [tutao/tutanota#7672]
When clicking on a birthday event i want that the contact details are shown so that i can decide how to contact the person to which him all the best to his birthday

**AC**
- When clicking on birthday event there is a contact preview appears
- The preview  shows the main attributes of a contact, including
  - Name (using same logic as contact viewer)
  - Age
  - Email addresses including a link to write an email
  - Phone numbers including a link to make a call.
- There preview uses the same style as the calendar event preview using different icons.
- There is an option to edit the contact, which redirects to the mail app

**Tasks**
- [ ] Show contact preview when previewing the birthday event
- [ ] Use the same preview popup w/ different icons
- [ ] Redirect the user to Mail App when editing

**Comment by hrb-hub** [comment]
The links seem to have an underline decoration when the user has only one email and one number
![image](https://github.com/user-attachments/assets/fed9231e-42d3-45b6-9dfa-3408569809e2)
