### ISSUE TITLE
Allow creating labels

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#7753]
part of #318 
**estimated: 12h**

**spent: 9h**

**AC**
 - It should be possible to create a label and attach name & color to it

## Tasks
 - [x] Backend service
 - [x] UI in folder column

## Test notes
- [ ] Create a label with the "Add label" button at the bottom of the labels list
- [ ] Give a name and color
- [ ] New label should be displayed with that name and color
- [ ] Label is still there after reload
