### ISSUE TITLE
Allow deleting / editing labels

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#7755]
part of #318
**estimated: 6h**
**spent: 5h (~3hr core, ~2 polishing/responding to review)**

## Tasks
 - [x] Backend service
 - [x] UI

## Test Notes
- [ ] Can edit the name of an already created label
- [ ] Can change the color for an already created label
- [ ] Can delete a label
- [ ] changes are immediately displayed in the labels list in the sidebar
- [ ] changes are immediately displayed for any relevant labels displayed on mails in the mail list or in the mail viewer
