### ISSUE TITLE
Assign labels

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#7756]
part of #318
**estimated: 16h**
**spent: 7h + 4h + 2h + 0.5h + 1h = 14.5h**

## Tasks:
 - [x] Backend service
 - [x] Converstaion viewer
 - [x] List view (multi select)
 - [x] Add an icon when label applied to some emails

## Test notes
 - [ ] There is a button to assign labels in mail view
   - [ ] In desktop layout in the toolbar for a single mail
   - [ ] In desktop layout in the toolbar for multiselect
   - [ ] In more menu for individual mails
   - [ ] In mobile layout in the toolbar for a single mail
   - [ ] In mobile layout in the toolbar for multiselect
 - [ ] There is a button to assign labels in search view
   - [ ] In desktop layout in the toolbar for a single mail
   - [ ] In desktop layout in the toolbar for multiselect
   - [ ] In more menu for individual mails
   - [ ] In mobile layout in the toolbar for a single mail
   - [ ] In mobile layout in the toolbar for multiselect
- [ ] Dropdown shows all the labels and their status
- [ ] In case of multiselect if some mails don't have the label assigned and some do there is a label icon with a dash in the middle
- [ ] Only labels that are completely selected or deselected in the dropdown will change, partially applied ones don't change
- [ ] Folders don't change when changing labels
- [ ] When mails are from different mailboxes (e.g. in search) then ----> ??
- [ ] Dropdown to apply labels does not overflow
- [ ] Dropdown to apply labels can be navigated with keyboard and screen reader, it traps focus correctly
- [ ] If dropdown is dismissed no labels are applied
