### ISSUE TITLE
Display labels in mail viewer

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#7758]
part of #318 
**estimated: 6h**

**AC**
 - Conversation viewer displays all labels assigned to email
 - Label list wraps when it doesn't fit

## Tasks
 - [x] Add label list to mail viewer when mail is expanded
 - [x] Adjust label color saturation for dark theme

## Test notes
 - [ ] Labels are displayed with their names when email is expanded
 - [ ] It works on both desktop and mobile layouts
 - [ ] Each label is only displayed on a single line or is cut off if it doesn't fit
 - [ ] Labels wrap to multiple lines
 - [ ] Labels update when applied labels change
 - [ ] Labels update when the label itself is changed
 - [ ] Saturation for label color is capped in the dark theme
 - [ ] Labels with low saturation in color are displayed unchanged in dark theme
 - [ ] Labels are displayed correctly in dark theme on iOS
