### ISSUE TITLE
Display label in mail list

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#7759]
part of #318
**estimated: 16h**
**actual time: 11h**

**AC**
 - Limit amount of labels
 - Limit the size of a single label
 - Part of the subject should show even when there are a lot of labels

## Tasks
 - [x] Add container in `MailRow` that can display labels
 - [x] Update MailRow with the label information
 - [x] Pass on the label information to `MailRow` in `MailListView`
 - [x] Pass on the label information to `MailRow` in `SearchListView`
 - [x] Limit the size of individual labels, limit the number of labels
 - [x] Fix view size adjustment when there are labels

## Test notes
 - [ ] Assigned labels are displayed on the mail in mail list view
 - [ ] Label updates like changing its name or color are reflected in mail list view
 - [ ] Mail list preview in Whitelabel's `CustomColorEditorPreview` works as expected
