### ISSUE TITLE
Show mails with currently selected label

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#7760]
part of #318
**estimated: 4h**
**actual: 7h**

**AC**
 - it is possible to select a label from the list below the folder list
 - only emails with the selected label are displayed, across all folders

## Tasks
 - [x] Check that URL schema can support labels
 - [x] Adjust `MailView` to show when the label is being selected
 - [x] Adjust `MailViewModel` to be able to load emails by labels and not only folders

## Test notes
 - [ ] Selecting a label
   - [ ] Selected label is highlighted in side menu
   - [ ] Selected label's id is shown in URL
   - [ ] Mails having currently selected label are shown in mail list
   - [ ] Folder icons are shown on mails in the mail list
   - [ ] Selecting an unused label shows no mail in mail list
   - [ ] On label selection mail list is focused
 - [ ] In edit mode label selection is disabled
   - [ ] Selected label is not highlighted
   - [ ] Selecting a different label does nothing
- [ ] When moving multiple mails and mails are in different folders, all move target are shown
  - [ ] In label view
  - [ ] In search view
