### ISSUE TITLE
Toggle button

### ISSUE THREAD

**Issue by rih-tutao** [tutao/tutanota#7773]
Toggle/switch  with full accessibility support.
The component should have a on/off, and a disabled state.
Adding classes should also be allowed.

**Tasks**
- [x] Write base component
- [x] Introduce disabled state with aria properties

### Test notes
- [ ] Toggle works as a standalone component by:
    - [ ] Receiving a boolean value as an attribute that controls its state on/off
    - [ ] Receiving a callback function that will be called after the user click on the toggle pill or its label, the callback receives the new state as a parameter
- [ ] Toggle can be disable, preventing any kind of interaction besides highlighting and copy/paste its label 
- [ ] It's focus-able if enabled
    - [ ]  Can be interacted with using the `Spacebar` and `Return` keys
- [ ] No style overwrites are allowed through the style attribute
- [ ] Classes can be added to extend it's styling
- [ ] The component has all relevant Aria and a11y properties set and reflecting its state
- [ ] Toggle has two variants
    - [ ] Normal render label and toggle pill side-by-side
    - [ ] Extended renders label and toggle pill on opposite side, expanding the width and leaving a gap between them
- [ ] Toggle pill can be rendered left or right its label
