### ISSUE TITLE
Select Component

### ISSUE THREAD

**Issue by domesticated-raptor** [tutao/tutanota#7778]
Implement a Dropdown component.

**AC**
- Reuse the existing dropdown
- The Select component should be able to receive a placeholder
- The placeholder should be displayed when no option is selected
- If an option is selected, the Select component should display the selected option as it is
- Have a OptionList component to hold the dropdown options

**Tasks**
- [x] Write base component
- [x] Extract a basic OptionList from Dropdown
- [x] Handle option selection
- [x] Handle placeholder
- [x] Handle keyboard navigation
- [x] Handle disabled state
- [x] Handle accessibility
