### ISSUE TITLE
Remove new domain notice

### ISSUE THREAD

**Issue by wrdhub** [tutao/tutanota#7895]
Remove the "Tutanota is now Tuta" banner on the web login page. It's been long enough!

## Tasks
- [x] Remove migrate credentials ("Tutanota is now Tuta") banner
- [x] Remove unused keys on Phrase

## Test notes
- [ ] Banner is no longer present on login page
- [ ] Credentials are still saved properly when the "Store password" option is checked

**Estimated: 1h**
**Time spent: 2h**
