### ISSUE TITLE
Guests Page

### ISSUE THREAD

**Issue by murilopereirame** [tutao/tutanota#7904]
Implement a new page to select guests when creating a new event

**AC**
- There's a new page to select the guests
- The user can change the organizer alias
- The organizer attendance status is on a new line
- There's a button to encrypt the invite for external users
- Guest password: 
  - If the guest is a contact with a predefined password, the password should be auto filled
  - The guest password input's content can be visible or hidden
  - There's a button to control password input visibility
  
![Image](https://github.com/user-attachments/assets/db7d763a-1cb1-4026-a9c7-1a5af09da4f9)
![Image](https://github.com/user-attachments/assets/b795a7fa-9618-4ef9-a837-70a8a0acd88f)

**Tasks**
- [x] Implement a dropdown for selecting organizer
- [x] Implement a dropdown for  organizer attendance status bellow organizer
- [x] Use the previous created components to implement the layout
- [x] Handle password per guest
- [ ] Implement navigation from event editor to guest list
- [x] Update input component to accept type
- [x] Handle guests suggestion logic
- [x] Handle guests password autofill if available and needed
- [ ] Handle accessibility
