### ISSUE TITLE
Repeat Rules Page

### ISSUE THREAD

**Issue by murilopereirame** [tutao/tutanota#7905]
Implement a new page to select repeat rules when creating a new event. 

**AC**
- When selecting the custom option, a new section should appear to customize the interval
- There's a new page to select the repeat rule
- The inputs still using dropdowns
- Show the dropdowns on End section only when their respective option is selected
- Use the existing radio button from onboarding wizard

![Image](https://github.com/user-attachments/assets/a2bed320-5a59-4ed8-a0eb-d3e934091281)
![Image](https://github.com/user-attachments/assets/c7d1bcba-55c7-4066-9c3c-54bd8e1f8bae)

**Tasks**
- [ ] Implement the navigation to the new page
- [ ] Implement the design using the previous created components
- [ ] Handle the rules logic
