### ISSUE TITLE
Input Button

### ISSUE THREAD

**Issue by murilopereirame** [tutao/tutanota#7906]
Create and implement an Input Button

**AC**
- There's a button with a label and an input
- When the button is clicked or focused, the input should be focused and the label hidden
- When the input loses the focus, the button displays the provided label and the input hidden
- The button should have an Outline variant

**Tasks**
- [x] Implement the button
- [x] Implement focus logic
- [x] Handle accessibility
- [x] Handle disabled status
