### ISSUE TITLE
Time section

### ISSUE THREAD

**Issue by murilopereirame** [tutao/tutanota#7912]
Implement time selection section on Event Editor

**AC**
- On mobile:
  - There's a button to pick a date and time
- On desktop:
  - The picker is an InputButton that when clicked should focus the internal input field and displays a date picker dropdown (Depends on #7906 )
- User is able to mark the event as All day
- Existing validations still working
- The layout is implemented according to design

**Tasks**
- [ ] Implement the card section
- [ ] Add the buttons to pick dates
- [ ] Add All Day event switch
- [ ] Migrate date validations
- [ ] Add input for desktop
