### ISSUE TITLE
Reminders Section

### ISSUE THREAD

**Issue by murilopereirame** [tutao/tutanota#7913]
Implement reminders section on the new Event Editor

**AC**
- There's a reminders section inside the new Event Editor
- The reminder section is aligned on left
- There's no title on this section, only an icon
- If there's already a reminder, the action to add a new one should include a plus icon
- The add reminder w/ the icon should be indented
 
![Inverted filled text pop-up](https://github.com/user-attachments/assets/fcf3615f-26f1-4280-a477-fb8933a215cb)

**Tasks**
- [x] Adjust alignment
- [x] Use action "Add Reminder" instead of none
- [x] Change the dropdown to accept don't having an icon
- [x] Fix the reminder items styling inside dropdown
- [x] Handle accessibility
