### ISSUE TITLE
Restrict labels based on subscription

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#7943]
Free accounts and old paid plans can add up to 3 labels.

## Tasks
 - [x] Client-side check when adding a label
 - [x] Server-side check when adding a label
 - [x] ~~Migrate existing plans~~ Not needed because this would only apply to old plans which wouldn't have this feature anyway.
 - [x] Server-side check when downgrading
 - [x] Handle new precondition when downgrading

**Estimated: 10h**
**Spent: 1h + 1h + 1h + 2h**
