### ISSUE TITLE
Downloading and storing exported emails

### ISSUE THREAD

**Issue by hrb-hub** [tutao/tutanota#7954]
**Estimated: 20h**
**Taken: 21h**

## Tasks
- [x] Load mails by iterating mail bags
- [x] Load mail details in bulk
- [x] Load attachment entities in bulk
- [x] Load attachment data
- [x] Write emails to the disk
- [x] Persist the export state periodically to resume it
- [x] Update the export state for UI
- [x] Resume on login
- [x] There's a function to stop the export
- [x] Error handling
