### ISSUE TITLE
Add AppStore subscription to Calendar App

### ISSUE THREAD

**Issue by murilopereirame** [tutao/tutanota#7987]
As a Tuta Calendar user, I want to subscribe to a plan using in-app subscription as my Payment method

**AC**
- Users are able to subscribe on calendar app using AppStore in app subscription
- Subscriptions made on Tuta Mail are valid on Tuta Calendar
- User can't manage a subscription made on Tuta Mail inside Tuta Calendar
- When trying to manage a subscription made within other Tuta App, a message appear informing user to manage on AppStore or inside the other app.

**Tasks**
- [x] Add the respective subscriptions on AppStore connect to Calendar App
- [x] Update backend to handle calendar subscriptions
- [x] Detect subscriptions made within Mail App (and the opposite)
  - [x] Check which app was used to subscribe
  - [x] Update model to hold this info
- [x] Create an enum on server to identify Mail and Calendar subscriptions

### Calendar App
- [ ] Verify that App Store payment is the only option on iOS (you should automatically select it).
- [ ] Verify that App Store payment is unavailable on Android, web, and desktop.
- [ ] Sign up for a paid account using App Store in Euros. Verify this works and that the prices are displayed correctly.
- [ ] Sign up for a paid account using App Store in some other currency (USD, BRL, GBP, etc.). Verify this works and that the prices are displayed correctly.
- [ ] Sign up for a free account, then switch to App Store payment. Verify this works.
- [ ] Sign up for a paid account using PayPal, then try to switch to App Store without canceling. Verify this does not work.
    - [ ] Cancel the subscription, and then try to switch to App Store. Verify this works.
- [ ] Change an App Store subscription from Revolutionary to Legend. Verify this works and that this is near-instant (should switch within a minute).
- [ ] Change an App Store subscription from Legend to Revolutionary. Verify this works, but the switch does not occur until the subscription renews.
- [ ] Verify that App Store subscriptions cannot be altered directly on any non-iOS app. You are redirected to the iTunes store.
- [ ] Try to delete your account with an App Store subscription. Verify you cannot do that.
    - [ ] Deleting from Settings -> Global settings -> Delete account
    - [ ] Deleting using Terminate Account
- [ ] Create some calendars and subscribe to external calendars
- [ ] Cancel a subscription. Once the subscription has expired, manually run the App Store Subscriptions batch job. Verify the account has no custom calendars.
- [ ] You can't manage your subscription created on the Mail App
  - [ ] You're prompted to open Mail App
- [ ] Create a subscription on Mail App
  - [ ] Let it expires
  - [ ] Run the batch job with a future date (Next day)
  - [ ] Change it on calendar app, you can pick another plan or resubscribe through Calendar App using App Store payments

### Mail App
- [ ] Subscription with App Store payment still working
- [ ] You can manage subscriptions created on Mail App
- [ ] You can't manage your subscription created on the Calendar App
  - [ ] You're prompted to open Calendar App
- [ ] Create a subscription on Calendar App
  - [ ] Let it expires
  - [ ] Run the batch job with a future date (Next day)
  - [ ] Change it on mail app, you can pick another plan or resubscribe through Mail App using App Store payments

**Comment by murilopereirame** [comment]
- The batch job isn't deleting the calendars
- App Store subscription dialog is being shown for users while subscribed with another payment method
