### ISSUE TITLE
Create/Edit events with Advanced Repeat Rules

### ISSUE THREAD

**Issue by murilopereirame** [tutao/tutanota#8047]
As a user, I want to be able to create or edit events with advanced repeat rules like weekly on some days or every first 

**AC**
- Weekly:
  - select days of the week.
- Monthly:
   - Same day in month. Do not allow changing the day in repeat rule configuration.
   - Same weekday in a week. First, second, third, fourth or last week.

**Tasks**
- [ ] Update UI to include new rules
- [ ] Adapt event saving to deal with rules
- [ ] Adapt reminders to deal with rules

**Comment by andrehgdias** [comment]
Feature mentioned on #4579
