### ISSUE TITLE
Handle Advanced Repeat Rules during Alarm Schedule

### ISSUE THREAD

**Issue by murilopereirame** [tutao/tutanota#8096]
**AC**
As a User I want to have my alarms scheduled according to the Advanced Repeat Rules and receive notifications for them according to the rules.

**Tasks**
- [x] Implement the event expansion in Rust
- [ ] Write the wrapper for iOS
- [x] Write the wrapper for Android
- [ ] Schedule the alarms
