### ISSUE TITLE
Shared mailboxes

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#903]
As a admin of tutanota account, i want to configure mailboxes that can be accessed by multiple users, so that they can send and receive messages from that mailbox without the need to login into another account.

## AC
* Tutanota admin user can order shared mailboxes in "Settings → Shared mailboxes"  and assign users as members
* The shared mailbox section is available for accounts with multi user support (new business plans, new private plans with multi-user support, legacy plans)
* Ordering of shared mailboxes is only possible for new plans.
* Members of such a mailbox see another mailbox with the same folder structure in their folder list.
* A member can send and receive  SMTP messages
* A member can send and receive end-to-end encrypted messages to other Tutanota users
* Sending end-to-end encrypted messages to external user is not supported and shows an appropriate info message.
* Local admin groups are kept in the new "Shared mailboxes" section

## Tasks
* [x] Rename the "Groups" section to "Shared mailboxes"
* [x] Only show the shared mailboxes section for plans with multi user support
* [x] Restrict creating shared mailboxes for admins of new paid plans. For others show an upgrade dialog.
* [x] Verify that all members of the shared mailbox see it below their private mailbox
* [x] Verify that members can send and receive SMTP messages
* [x] Verify that members can send and receive end-to-end encrypted messages to other Tutanota users
* [x] Show a dialog informing that it is not possible to send confidential emails to externals when a user tries to send one
* [x] Verify that local admin groups are still visible and accessible in the new "Shared mailboxes" section
* [x] Add an info link in the create dialog that points to an FAQ entry explaining details of the shared mailboxes

Bug collection for refinement:
* When clicking on a notification for a new email in a shared mailbox the user inbox is opened instead (tested on desktop).

## Test notes shared mailboxes
- [ ] Order shared mailboxes in Settings -> Shared mailboxes in a new paid plan
- [ ] Ordering a shared mailbox is not possible for legacy paid plans
- [ ] Check that the shared mailboxes section is available for new paid plans, new private plans with multi-user support and legacy paid plans
- [ ] Check that the shared mailboxes section is not available for the free plan and private plans without multi-user support
- [ ] Assign the admin user itself to the shared mailbox and remove it again
- [ ] Assign a non-admin user to the shared mailbox and remove it again
- [ ] Shared mailboxes are visible below the personal mailbox in the mail view
- [ ] When a folder of a shared mailbox is selected the sender in the email editor is the shared mailbox address
- [ ] When a folder of a personal mailbox is selected the sender in the email editor is the personal mailbox address
- [ ] Sending and receiving SMTP emails from a shared mailbox is possible
- [ ] Sending and receiving internal emails from a shared mailbox is possible
- [ ] When trying to send a confidential email to externals (click send button) a dialog is shown informing that this is not possible yet.
- [ ] Existing local admin groups are visible in the shared mailbox section as well.
- [ ] The info link at the bottom of the add shared mailbox dialog points to an FAQ entry informing about shared mailboxes
- [ ] Deactivating and activating shared mailboxes is possible. The price changes in this case.
- [ ] Change the sender name of the shared mailbox and check that it is used when sending an email.
- [ ] Regression test adding/removing users, including the own user, from a calendar group
- [ ] Regression test adding/removing users, including the own user, from contact list groups
- [ ] Regression test adding/removing users, including the own user, from template groups

**Comment by JimmyCushnie** [comment]
This is a very important feature for business use. I hope it will be coming soon.

**Comment by prcmt** [comment]
A little confused by the linked closed issues. By shared email accounts, does this mean mailboxes to which multiple users (with their own login credentials) have access?

**Comment by armhub** [comment]
Yes, this is about shared mailboxes that can be used by multiple users at the same time without having to login as a different user. I have renamed the issue to make it better understandable.

**Comment by QEDeD** [comment]
This feature would also be great for families and couples, who want a shared email address, like us@[familiy_name].TLD. Currently, you need either need a separate account with the shared address or, if you make it an alias to one of the family member's account, other family members have to log into the other person's account. Instead, it would be nice to simply have one or more folders that could be accessed from each person's own account.

**Comment by prcmt** [comment]
Shared mailboxes are a surprisingly rare feature of mail services, considering how useful they are!

**Comment by AFulgens** [comment]
Am I mistaked here or this could be trivially solved by implementing #516? (One mailbox + aliases = shared mailbox)

**Comment by laius** [comment]
Any news regarding a release date? After all, it's been added to the project roadmap over 19 months ago. And it's (from my PoV) essential for families requiring a common inbox.

**Comment by laius** [comment]
> Am I mistaked here or this could be trivially solved by implementing #516? (One mailbox + aliases = shared mailbox)

No. We don't want one mailbox with two addresses. Instead we want two addresses of which one is shared.

**Comment by jflattery** [comment]
> Any news regarding a release date? After all, it's been added to the project roadmap over 19 months ago. And it's (from my PoV) essential for families requiring a common inbox.

"Soon"™

**Comment by QEDeD** [comment]
Looking forward to it 🙂

**Comment by laius** [comment]
> > Any news regarding a release date? After all, it's been added to the project roadmap over 19 months ago. And it's (from my PoV) essential for families requiring a common inbox.
> 
> "Soon"™

Could you specify this a little? Like, are we talking closer to 4 weeks or 4 months?

**Comment by jflattery** [comment]
> > > Any news regarding a release date? After all, it's been added to the project roadmap over 19 months ago. And it's (from my PoV) essential for families requiring a common inbox.
> 
> > 
> 
> > "Soon"™
> 
> 
> 
> Could you specify this a little? Like, are we talking closer to 4 weeks or 4 months?

I would say 4 years, give or take 3 years should be about accurate. But I know nothing.

**Comment by JimmyCushnie** [comment]
Bump -- @armhub is there any ETA for this? It is a pain forwarding emails to the other person who needs to see them.

**Comment by tegutistgut** [comment]
Come on. Please do this.
The only privacy friendly clients are K-9 and FairEmail.

The only alternatives would be Tutunota or ProtonMail (if they do it) or CanaryMail (they think about making it open source)

**Comment by BriT999** [comment]
i vote for this. It will be a **game changer!** _C'mon Tutanota team_

**Comment by Creylia** [comment]
Please, as a family, this is absolutely necessary.

**Comment by EVLRBT-01** [comment]
Will this support multiple accounts as suggested in #521 ? 

I ask as I am considering Tutanota for both a separate Private and Business account (with custom domains), which I'd want to access using the same mobile device. An Android Work Profile might be a workaround in the short term...

**Comment by vitoreiji** [comment]
@EVLRBT-01 your use case is already supported; you can log into multiple accounts with your device and switch between them at will. All of them will be able to get notifications.

**Comment by EVLRBT-01** [comment]
Not on mobile? You need to log out and back in as the other user as far as I am aware?

The FAQ on the Tutanota site also says "In the mobile app, you can currently only login with one user.".
________________________________

**Comment by cyb3n3tic** [comment]
Just going to add my voice to the rest to say that a shared mailbox that is accessible from two different accounts without additional log in steps will be a huge win - I will pay money and shift domains to whichever secure email provider comes up with this first but none seem to see it as any kind of priority.

**Comment by charlag** [comment]
It is actually possible to book it via Settings -> Groups -> Add group  but some functionality is unfinished (e.g. signature)

**Comment by cyb3n3tic** [comment]
OK, that's interesting - I will see how that works. Thanks
